### ISSUE TITLE
AWS Elastic Search service 5.3 with curator

### ISSUE THREAD

**Issue by srivarunlokku** [elastic/curator#1002]
Right now We have all servers in AWS environment. We are using AWS elastic search to maintain log files and for forwarding we are using Logstash. We are planning to use Elastic Curator to delete indices after particular period of time.

I have installed Curator in logstash instance itself. Created curator.yml in /root/.curator/curator.yml and created one more file named action.yml in /home/ubuntu/action.yml. Following are configurations inside curator.yml and action.yml

**curator.yml:**

client:
  hosts:
    - https://search-sf-logs-ytamvk4k5ct6wsnvrrzpttzhi.us-east-1.es.amazonaws.com
  port: 443
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

**action.yml:**

actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 180 (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 180
      exclude:

**I am getting following message**
 curator /home/ubuntu/action.yml
2017-07-20 17:29:11,135 INFO      Preparing Action ID: 1, "delete_indices"
2017-07-20 17:29:11,152 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 180 (based on index name), for logstash- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2017-07-20 17:29:11,739 INFO      Deleting selected indices: [u'logstash-iis-webservice360-2017.07.13', u'logstash-iis-msgapp-2017.07.16', u'logstash-iis-msgapp-2017.07.15', u'logstash-iis-msgapp-2017.07.14', u'logstash-iis-msgapp-2017.07.13']
2017-07-20 17:29:11,739 INFO      ---deleting index logstash-iis-webservice360-2017.07.13
2017-07-20 17:29:11,739 INFO      ---deleting index logstash-iis-msgapp-2017.07.16
2017-07-20 17:29:11,740 INFO      ---deleting index logstash-iis-msgapp-2017.07.15
2017-07-20 17:29:11,740 INFO      ---deleting index logstash-iis-msgapp-2017.07.14
2017-07-20 17:29:11,740 INFO      ---deleting index logstash-iis-msgapp-2017.07.13
2017-07-20 17:29:12,830 INFO      Action ID: 1, "delete_indices" completed.
2017-07-20 17:29:12,830 INFO      Job completed.
root@ip-10-0-0-181:/home/ubuntu# curator /home/ub

Still i can see log files coming back to AWS elastic search service .Following are the one's i can see
logstash-iis-msgapp-2017.07.13
logstash-iis-webservice360-2017.07.13

**Comment by untergeek** [comment]
It might be helpful to get the `creation_date` of the `logstash-iis-msgapp-2017.07.13` indices.  I would not be surprised to find that the creation date is after the timestamp `2017-07-20 17:29:11,740`.

### If I am right...
```
curl localhost:9200/logstash-2017.08.01/_settings?pretty
{
  "logstash-2017.08.01" : {
    "settings" : {
      "index" : {
        "refresh_interval" : "5s",
        "number_of_shards" : "5",
        "provided_name" : "logstash-2017.08.01",
        "creation_date" : "1501549004079",
        "number_of_replicas" : "1",
        "uuid" : "5N50CzJxQN6RQCnIDIg_HA",
        "version" : {
          "created" : "5040399"
        }
      }
    }
  }
}
```
Take the value for `creation_date`, which is epoch + milliseconds, and feed it into https://www.epochconverter.com, which will auto-compensate for milliseconds.  The above value yields a timestamp of `GMT: Tuesday, August 1, 2017 12:56:44.079 AM`.

If I am correct, then what is going on is that Logstash is still receiving stray values for those older indices, and they are being recreated.  

Another easy way to tell is to use the `_count` API.

```
curl localhost:9200/logstash-2017.08.01/_count?pretty
{
  "count": 1319,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  }
}
```
If the count does not look like a full day's worth of records, that's another indicator.

### If I am wrong
If somehow the indices are not being deleted—and I see no evidence in your log files to support that—then what you would be experiencing is your cluster failing, or giving up on deleting after trying for 30 seconds, and not getting an update of the master state.  **This is not observable in your log file.** Your logs indicate that the cluster immediately responded in the affirmative (with a difference of barely over a second).

This is basic API call stuff.  If Curator were failing to delete, then regular API calls would too.  I am 99.99% sure of my initial response.

**Comment by srivarunlokku** [comment]
creation_date
https://search-sf-logs-ytamvk4k5ct6wsnvrrzpttyzhi.us-east-1.es.amazonaws.com/logstash-iis-msgapp-2017.07.13/_settings?pretty

{
  "logstash-iis-msgapp-2017.07.13" : {
    "settings" : {
      "index" : {
        "creation_date" : "1501710194333",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "Nt3njSgrSOGa9FX-Sle70A",
        "version" : {
          "created" : "5030299"
        },
        "provided_name" : "logstash-iis-msgapp-2017.07.13"
      }
    }
  }
}

Count:

https://search-sf-logs-ytamvk4k5ct6wsnvrrzpttyzhi.us-east-1.es.amazonaws.com/logstash-iis-msgapp-2017.07.13/_count?pretty

{
  "count" : 34681,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  }
}

**Comment by srivarunlokku** [comment]
![screenshot](https://user-images.githubusercontent.com/16951654/28930066-b695e366-783f-11e7-960c-0887eb84ef69.PNG)

**Comment by untergeek** [comment]
Thanks for sharing, and sorry for the delayed response.  I was on a camping vacation with my son.

That timestamp (`1501710194333`) confirms exactly what I suspected.  That means that even though the index is named `logstash-iis-msgapp-2017.07.13`, indicating data from the 13th of July, it was created on August 2.  Logstash is still sending data with timestamps from July 13th to Elasticsearch—apparently, at least 34,681 lines worth.

My conclusion is that Curator is working just fine, and you have stale data that is being reread and/or resent by Logstash.

**Comment by srivarunlokku** [comment]
@untergeek 

Thank you for the kind response.  Can you please tell me the steps to correct it?

**Comment by untergeek** [comment]
That's a different question altogether, and not one related to Curator, unfortunately.

I'd ask for help in the Logstash discussion forum at https://discuss.elastic.co.

**Comment by untergeek** [comment]
Going to close this now, as it's not a Curator issue.
