### ISSUE TITLE
add support for filtering indices in a snapshot upon restore

### ISSUE THREAD

**Issue by jpcarey** [elastic/curator#1006]
Currently, for the restore functionality, you can filter the snapshots within a repository to get the desired snapshot. Within the snapshot, you could provide a static list of indices to restore - or restore everything. It would be useful to select the indices to restore by using a filter prefix/regex.

**Comment by untergeek** [comment]
In the meanwhile,  in Curator, indices to be restored must be specified using YAML array notation, which could be:

```
options:
  indices:
    - index1
    - index2
```
or
```
options:
  indices: ['index1', 'index2']
```
Importantly, though, you can use [multi-index syntax](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/multi-index.html) for each array element, for example: `test*` or `*test` or `te*t` or `*test*`, and the ability to "exclude" (`-`), for example: 
```
options:
  indices: [`test*`, `-test3`]
```
for your `indices` option to get the desired effect (to an extent).

**Comment by DaveyDevOps** [comment]
I think multi-index syntax fits the requirements here. 
I also wonder if filtering the indices into separate snapshots would be useful.

**Comment by untergeek** [comment]
> filtering the indices into separate snapshots 

I'm not following. This issue is about restoring. Is this comment about having a single action filter into multiple target snapshots (which cannot currently be done in parallel, but only one after another), rather than building multiple snapshot actions to achieve the same?

**Comment by DaveyDevOps** [comment]
> filtering the indices into separate snapshots

Here I wasn't suggesting a new feature but a change in operational process to make use of advanced filtering while creating the snapshots. It would require multiple snapshots actions and be limited by sequential operations. It mainly comes to mind since filtering is available on the snapshot to restore names. 

Again, I am thinking multi-index syntax may be an adequate solution here.
