### ISSUE TITLE
Monthly reindex works but claims it failed

### ISSUE THREAD

**Issue by DPattee** [elastic/curator#1008]
After automatically creating a monthly index with date math, I reindex all the daily indexes in to it using date math and a wild card. This works but is only "successful" (success exit code) if I've statically named the destination index. 

As you can see from this partial index list, all 3 reindex runs worked correctly. But only the "*-bar-*" one actually reported success.

>yellow open   filebeat-bar-monthly wSwjAfaKRounkqh1IvrcAg   5   1     503571            0    105.7mb        105.7mb
>yellow open   filebeat-foo-monthly TseDd9_oQEaqFTxIcAmY0Q   5   1     503563            0    105.5mb        105.5mb
>yellow open   filebeat-2017.07-monthly _7ndFTFdRnGeV52wFErsmA   5   1     503668            0    105.6mb        105.6mb

(ignore the minor difference in doc count, this test cluster had data going in to one of the daily indices)

The request bodies for each are as follows. There seems to be a problem with the date math indicator even when no date math is performed..

Works and "succeeds"
> 
      request_body:
          source:
            index: '<filebeat-{now/M{YYYY.MM}}.*>'
          dest:
            index: 'filebeat-foo-monthly'

Works but "fails"
> 
      request_body:
          source:
            index: '<filebeat-{now/M{YYYY.MM}}.*>'
          dest:
            index: '<filebeat-bar-monthly>'

Works but "fails"
>
       request_body:
          source:
            index: '<filebeat-{now/M{YYYY.MM}}.*>'
          dest:
            index: '<filebeat-{now/M{YYYY.MM}}-monthly>'

The error messages are in the format

2017-07-22 16:20:52,421 ERROR     curator.actions.reindex  _post_run_quick_check:1266 **Index "<filebeat-{now/M{YYYY.MM}}-monthly>" not found after reindex operation**. Check Elasticsearch logs for more information.

**Comment by untergeek** [comment]
The problem with the 'works but "fails"' is that Curator cannot extrapolate the correct destination index name from Elasticsearch date math.  That's why the one which is statically named succeeds and the others give a failure message.

I will have to see if there's a way I can get a date-math name back through a noop API call to make that possible.

**Comment by untergeek** [comment]
I have a workaround.  Putting a fix in now.
