### ISSUE TITLE
pip install of curator cannot find elasticsearchearch installed by yum

### ISSUE THREAD

**Issue by mrchang7** [elastic/curator#1013]
I've installed elasticsearch.rpm (5.4.3) by yum install. And then trying to pip install elasticsearch-curator-5.0.1.tar.gz without internet connection. It complains:

Processing ./elasticsearch-curator-5.0.1.tar.gz
Collecting elasticsearch<6.0.0,>=5.3.0 (from elasticsearch-curator==5.0.1)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3254f90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/elasticsearch/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3254c90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/elasticsearch/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3254150>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/elasticsearch/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x3254e90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/elasticsearch/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2999f50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/elasticsearch/
  Could not find a version that satisfies the requirement elasticsearch<6.0.0,>=5.3.0 (from elasticsearch-curator==5.0.1) (from versions: )
No matching distribution found for elasticsearch<6.0.0,>=5.3.0 (from elasticsearch-curator==5.0.1)

**Comment by untergeek** [comment]
The RPM installed elasticsearch, the Java program.  It did not install elasticsearch the python module, which is what Curator depends on.  The elasticsearch python module is currently at version 5.4.0, and apparently your pip is unable to download that dependency.

I recommend installing Curator from [the YUM repository](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html), rather than via pip.

**Comment by untergeek** [comment]
And if that doesn't work, you can always [download the RPMs directly](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html#_direct_package_download_link_2).

The problem with a pip install is that it will attempt to download dependencies.  If you have no internet access from the device you're trying to install Curator on, you should definitely use the RPMs provided in the link above.  They are fully-bundled with all dependencies.  You don't even need to have python installed for them to work.

**Comment by untergeek** [comment]
Since there's an explanation for what happened, as well as a path forward, I'm closing this issue.
