### ISSUE TITLE
[FEATURE] allow for absolute time in `period` filter

### ISSUE THREAD

**Issue by HonzaKral** [elastic/curator#1047]
It would be useful to be able to filter all indices from January 2017:
```
 - filtertype: period
   source: name
   timestring: '%Y.%m.%d'
   range_from: 2017.01
   range_from_format: "%Y.%m"
   range_to: 2017.01
   range_to_format: "%Y.%m"
   unit: months
```
Especially paired with env variables this could be very powerful!

**Comment by untergeek** [comment]
If it proves difficult to make schema validation work with this, I will roll a new filter (absolute_period).
