### ISSUE TITLE
[Feature] Log curator output directly to elasticsearch

### ISSUE THREAD

**Issue by geekpete** [elastic/curator#1048]
Might be nice to have the ability to store curator logging output directly to Elasticsearch.
Then you can query/alert on particular failures with Elastic Alerting with a watch. 

This logging might better be directed at a dedicated monitoring cluster to avoid issues with production affecting the ability to alert about those issues.

**Comment by netanel246** [comment]
+1

**Comment by DaveyDevOps** [comment]
Should Curator handle this or would a Filebeat solution be recommended?

**Comment by untergeek** [comment]
It's a good question. I think it only should be handled by Curator if the logs are intended to go to the same cluster. If not, it would mean a separate client configuration for logging. But perhaps that's a desired thing? I'm flexible. I could have a client configuration definition in the `logging` block. If none was there, and Elasticsearch is the target, it would use the default client configuration.
