### ISSUE TITLE
Clarify/add URL syntax values for hosts parameter in configuration file?

### ISSUE THREAD

**Issue by joshuar** [elastic/curator#1053]
It appears that the hosts parameter in the config file does not support a URL syntax, for example a value of `https://localhost:9200`?  This is confusing as in a lot of our other products, such a syntax is a valid way to refer to Elasticsearch, in addition to just a plain `localhost` or `localhost:9200` value.  

I'm not sure whether this amounts to a documentation issue or a feature request to add support for URL values for this parameter?

**Comment by untergeek** [comment]
This is mostly because of [this](http://elasticsearch-py.readthedocs.io/en/5.4.0/connection.html#urllib3httpconnection-default-connection-class).  Curator uses this class.  I'm sure I could parse the URL down and populate these.

**Comment by untergeek** [comment]
This has been completed for Curator 8
