### ISSUE TITLE
Implement chunking based on number of indices

### ISSUE THREAD

**Issue by bechtoldt** [elastic/curator#1064]
There's chunk_index_list() (curator/utils.py#L535) that uses 3KB as chunk size when applying actions in actions.py. It should be used when getting indices in IndexList (curator/indexlist.py#L11), too. The request getting index metadata can be too long (see below).

I think we should:

* use chunking in IndexList class
* **additionally** use a configurable number of indices as chunk size too

```
- [21/Sep/2017:15:59:09 +0000] "GET /_cluster/state/metadata/.kibana,nico-test-,nico-test-100,nico-test-101,nico-test-102,nico-test-103,nico-test-104,nico-test-105,nico-test-106,nico-test-107,nico-test-108,nico-test-109,nico-test-110,nico-test-111,nico-test-112,nico-test-113,nico-test-114,nico-test-115,nico-test-116,nico-test-117,nico-test-118,nico-test-119,nico-test-122,nico-test-123,nico-test-124,nico-test-125,nico-test-126,nico-test-127,nico-test-128,nico-test-129,nico-test-131,nico-test-140,nico-test-150,nico-test-151,nico-test-152,nico-test-153,nico-test-154,nico-test-155,nico-test-156,nico-test-157,nico-test-158,nico-test-159,nico-test-160,nico-test-161,nico-test-162,nico-test-163,nico-test-164,nico-test-165,nico-test-166,nico-test-167,nico-test-168,nico-test-169,nico-test-170,nico-test-171,nico-test-172,nico-test-173,nico-test-174,nico-test-175,nico-test-176,nico-test-178,nico-test-179,nico-test-180,nico-test-181,nico-test-182,nico-test-183,nico-test-184,nico-test-185,nico-test-186,nico-test-187,nico-test-188,nico-test-189,nico-test-190,nico-test-191,nico-test-192,nico-test-193,nico-test-194,nico-test-195,nico-test-196,nico-test-197,nico-test-198,nico-test-199,nico-test-200,nico-test-201,nico-test-202,nico-test-203,nico-test-204,nico-test-205,nico-test-206,nico-test-207,nico-test-208,nico-test-209,nico-test-210,nico-test-211,nico-test-212,nico-test-213,nico-test-214,nico-test-215,nico-test-216,nico-test-217,nico-test-218,nico-test-219,nico-test-220,nico-test-221,nico-test-228,nico-test-230,nico-test-231,nico-test-232,nico-test-233,nico-test-234,nico-test-235,nico-test-236,nico-test-237,nico-test-238,nico-test-239,nico-test-240,nico-test-241,nico-test-242,nico-test-243,nico-test-244,nico-test-245,nico-test-246,nico-test-247,nico-test-248,nico-test-249,nico-test-250,nico-test-251,nico-test-259,nico-test-260,nico-test-261,nico-test-262,nico-test-263,nico-test-264,nico-test-265,nico-test-266,nico-test-267,nico-test-268,nico-test-269,nico-test-270,nico-test-271,nico-test-272,nico-test-273,nico-test-274,nico-test-275,nico-test-276,nico-test-277,nico-test-282,nico-test-286,nico-test-288,nico-test-289,nico-test-290,nico-test-291,nico-test-292,nico-test-293,nico-test-294,nico-test-295,nico-test-296,nico-test-297,nico-test-298,nico-test-299,......... HTTP/1.1" 413 0 "-" "-" 3215 0.075 [kube-system-elasticsearch-8080] 35.157.154.192:80 0 0.075 413
```

**Comment by untergeek** [comment]
> It should be used when getting indices in IndexList 

The chunking utility is for preventing a URL-length overrun when making requests.  Elasticsearch can't handle it when a URL longer than 4K bytes is sent.  How exactly would I limit this on the _request_ end?

As it stands, the flow is as follows:

1. At the end of Class instance initialization, it calls [`self.__get_indices()`](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L31).
1. Instance method `__get_indices` calls utility function [`get_indices`](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L66)
1. Utility function `get_indices` calls the [`get_settings` API](https://github.com/elastic/curator/blob/v5.2.0/curator/utils.py#L566-L569) and extracts a list of indices.
1. [If there are indices](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L68), it will [loop through all discovered indices](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L69), and [create an empty dictionary schema for index metadata](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L74-L90).  No API calls are made in this step.
1. It populates the metadata [by calling a function](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L71), which actually uses the [chunking utility function](https://github.com/elastic/curator/blob/v5.2.0/curator/indexlist.py#L148).

So far as using chunking in the IndexList class is concerned, it sounds more appropriate to use Elasticsearch's wildcarding and/or regular expressions to pull in a limited number of matching indices _first._  This is a feature I've long contemplated adding but have not yet gotten around to implementing.

> **additionally** use a configurable number of indices as chunk size too

This cannot be done for the reasons stipulated already: Chunking is about URL line length, not a count of index names.  It could be possible to define the chunk size, but that is less effective, I think than changing the index count to start with, as already suggested.  I may still add it.

**Comment by untergeek** [comment]
The aforementioned pre-loading feature will be coming in Curator v6.  Closing this ticket for now.
