### ISSUE TITLE
[FEATURE] Add support for returning indices smaller than `disk_space` in space filter (PR enclosed)

### ISSUE THREAD

**Issue by dustin-decker** [elastic/curator#1066]
Feature request:
Support returning indices *smaller* than `disk_space` in the space filter.

I needed a good way to use the shrink API on a bunch of different small indices (smaller than `disk_space` setting) that had too many shards. By adding a toggle for the comparison operator in the space filter, I was able to do this. I will add the pull request to this issue.

**Comment by sevoma** [comment]
PR enclosed in https://github.com/elastic/curator/pull/1067

**Comment by untergeek** [comment]
Closed by #1067
