### ISSUE TITLE
`permit_masters` triggers on master-eligible nodes

### ISSUE THREAD

**Issue by dandrestor** [elastic/curator#1068]
The `permit_masters` default value of `False` will also exclude the unelected _master-eligible_ nodes. For instance, in a cluster with three nodes, all of which are master-eligible, but only one is the elected master, of course, the `shrink` action will not run.

I'm not sure if this is intended behaviour or not.

**Comment by untergeek** [comment]
It is.  If you're using master-eligible nodes as data nodes, you need to use this flag.  I probably need to document it better, though.

**Comment by untergeek** [comment]
Making the flag `permit_master_eligible` felt too long.  Most people think, "I have 3 dedicated master nodes," when they build a cluster.  Even though only one of those is the elected master, they still consider it 3 master nodes.  All of these would be considered "masters" for the purposes of this flag.

**Comment by dandrestor** [comment]
I submitted a PR with a small change in the docs.

**Comment by untergeek** [comment]
Closed by #1069
