### ISSUE TITLE
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by karthikyedavalli** [elastic/curator#1099]
Getting 'datetime.timedelta' object has no attribute 'total_seconds' when running on python2.6

**Comment by untergeek** [comment]
Python 2.6 is not supported.  I immediately assume that you're using RHEL or CentOS 6 if you're stuck with Python 2.6.

If you need to use the Curator API, then you will need to upgrade or use a separate Python installation.

If you only need the Curator binary functionality, then by all means, [install the RPM package for your distribution](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/yum-repository.html), as it is a stand-alone version with all required libraries bundled.  It will not affect the system Python in any way.
