### ISSUE TITLE
curator 5.3 with password protected elastic

### ISSUE THREAD

**Issue by hsafe** [elastic/curator#1103]
Hi,
How could I use the curator-cli to connect to the elastic 5.4 which is password protected? I see that the command line options does not include any method to pass uname:password to the elastic backend...

**Comment by untergeek** [comment]
May I draw your attention to the `--http_auth` flag?

```
# curator_cli --help
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...

Options:
  --config PATH       Path to configuration file. Default:
                      ~/.curator/curator.yml
  --host TEXT         Elasticsearch host.
  --url_prefix TEXT   Elasticsearch http url prefix.
  --port TEXT         Elasticsearch port.
  --use_ssl           Connect to Elasticsearch through SSL.
  --certificate TEXT  Path to certificate to use for SSL validation.
  --client-cert TEXT  Path to file containing SSL certificate for client auth.
  --client-key TEXT   Path to file containing SSL key for client auth.
  --ssl-no-validate   Do not validate SSL certificate
  --http_auth TEXT    Use Basic Authentication ex: user:pass
  --timeout INTEGER   Connection timeout in seconds.
  --master-only       Only operate on elected master node.
  --dry-run           Do not perform any changes.
  --loglevel TEXT     Log level
  --logfile TEXT      log file
  --logformat TEXT    Log output format [default|logstash|json].
  --version           Show the version and exit.
  --help              Show this message and exit.

Commands:
  allocation        Shard Routing Allocation
  close             Close indices
  delete_indices    Delete indices
  delete_snapshots  Delete snapshots
  forcemerge        forceMerge index/shard segments
  open              Open indices
  replicas          Change replica count
  restore           Restore a snapshot
  show_indices      Show indices
  show_snapshots    Show snapshots
  snapshot          Snapshot indices
```

You'd use `curator_cli --http_auth 'user:pass'` ...

**Comment by sheilman16** [comment]
If you wanted to replace the username and password variables with environment variables, do you know if the colon would prove an issue? 
Hypothetically speaking, if the elasticsearch username and password were assigned to environment variables (docker) elasticsearch_username and elasticsearch_password, respectively. Would the declaration of `http_auth: '${ES_USERNAME}':'{ES_PASSWORD}}'` in the .YAML file properly reference the assigned values?

**Comment by untergeek** [comment]
Yes, it absolutely does. It won't work. Also, I don't even think you can use single quotes with environment variable replacement.

I'm having to revisit all of this for a future release due to how pyYAML 5.x was updated. This legacy behavior may not persist into the next major release.

**Comment by sheilman16** [comment]
For the single quotes, I was following [this guide](https://www.elastic.co/guide/en/beats/metricbeat/current/using-environ-vars.html) (see the bottom). I did not originally mention the inclusion on Ansible in my environment. Correct me if I'm wrong.

@untergeek the future release sounds like it will fix the issue at hand. Currently, it looks like my options are limited. Though, `http_auth` could be its own environment variable.

**Comment by untergeek** [comment]
> `http_auth` could be its own environment variable.

Correct. And that's how many people work around this.

**Comment by sheilman16** [comment]
@untergeek thanks for the help!
