### ISSUE TITLE
create a new alias 

### ISSUE THREAD

**Issue by Strijd** [elastic/curator#1104]
Hi
Is there any way you can create an alias with curator? 
If such action exists, can you please update  the docs
Thanks

**Comment by untergeek** [comment]
I'm sorry you had a hard time navigating the documentation, but [the alias action](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/alias.html) is clearly at the top of the list of [actions](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/actions.html) available in Curator.

To create an alias, you only need to [name](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/option_name.html) it, and then use the [add](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/alias.html) filter block to select which indices you want associated with the [name](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/option_name.html) you selected.  You can even apply [extra settings](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.4/option_extra_settings.html#_link_linkend_alias_alias_link) to your alias.

**Comment by Strijd** [comment]
Thanks
