### ISSUE TITLE
Document OpenSSL 1.0.2 requirement for Curator 5.4

### ISSUE THREAD

**Issue by ppf2** [elastic/curator#1124]
Somewhere between 5.0 -> 5.4 version of curator, it started requiring OpenSSL 1.0.2 libraries for it to work on Centos/RHEL environments.

https://discuss.elastic.co/t/curator-5-4-ssl-module-is-not-available/108009/5

Would be helpful to document this accordingly.

**Comment by untergeek** [comment]
I will add this dependency to the RPM package, rather than merely document it.

**Comment by bosinm** [comment]
I can confirm that in Red Hat 7.0 this happens even when downgrading to Curator 5.3. Upgrading the openssl library version to 1.0.2 is a must. The documentation needs to also be updated

**Comment by CamiloSierraH** [comment]
i have the same issue, workaround if needed (updating "openssl-libs" package): 
$sudo yum update openssl-libs

**Comment by untergeek** [comment]
The dependency has been addressed in the build scripts.
