### ISSUE TITLE
Current docs for Curator source install list missing/404 urls for dependencies

### ISSUE THREAD

**Issue by geekpete** [elastic/curator#1128]
On the source install page in the docs:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/python-source.html

A number of urls for dependencies are not working.

### Expected Behavior
URLs listed should resolve to downloadable tarballs rather than a HTTP 404.

### Actual Behavior
URLs are coming back as 404s due to either removed/missing tarball or possibly altered path to the file on the remote site.

### Steps to Reproduce the Problem

Go to:
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/python-source.html

try the urls for the listed dependencies and some fail:

- https://pypi.python.org/packages/source/u/urllib3/urllib3-1.20.tar.gz
  - possible alternates:
    - https://github.com/shazow/urllib3/archive/1.20.tar.gz
    - https://pypi.python.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz#md5=0da7bed3fe94bf7dc59ae37885cc72f7
- https://pypi.python.org/packages/source/c/click/click-6.7.tar.gz
  - possible alternates:
  - https://pypi.python.org/packages/95/d9/c3336b6b5711c3ab9d1d3a80f1a3e2afeb9d8c02a7166462f6cc96570897/click-6.7.tar.gz#md5=fc4cc00c4863833230d3af92af48abd4
  - https://github.com/pallets/click/archive/6.7.tar.gz
- https://github.com/certifi/python-certifi/archive/2017.1.23.tar.gz
  - possible alternates:
    - https://github.com/certifi/python-certifi/archive/2017.01.23.tar.gz
    - https://github.com/certifi/python-certifi/archive/2017.11.05.tar.gz
- https://codeload.github.com/elastic/elasticsearch-py/tar.gz/5.4.1
  - possible alternates:
    - https://pypi.python.org/packages/78/76/502a8e76e60d1fb3bf8326d94001465db8b7a4dd4df6c70b6f8ab3d87e33/elasticsearch-5.5.1.tar.gz#md5=91e0ddaf8952ef371005e9c6696b2f67
    - https://github.com/elastic/elasticsearch-py/archive/5.5.1.tar.gz

## Detailed Description
Potentially listed Install urls could be regularly tested to detect if they're not returning a valid url.
The equiv detail contained in the requirements.txt could be documented on this page to show minimum versions for a particular Curator version and potentially all dependency versions that have been tested as working with a particular Curator version.

**Comment by untergeek** [comment]
Well, crap.  It seems that PyPI has changed its URL schema.  Will have to work at this a bit.

**Comment by untergeek** [comment]
I can't find the `https://codeload.github.com/elastic/elasticsearch-py/tar.gz/5.4.1` anywhere, or even any instance of `codeload`.  I do see:
```
=== elasticsearch (python module)
Download and install the https://github.com/elastic/elasticsearch-py[elasticsearch-py] dependency:

. `wget https://github.com/elastic/elasticsearch-py/archive/`+pass:attributes[{es_py_version}].tar.gz -O elasticsearch-py.tar.gz+
. `pip install elasticsearch-py.tar.gz`

or uncompress and run `python setup.py install`
```
So it appears to already be using the github archive location.

I'll use the github pages for each of these.
