### ISSUE TITLE
The symlink /usr/bin/curator is giving error "Fatal error: unable to stat executable"

### ISSUE THREAD

**Issue by satish-chef** [elastic/curator#1137]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

### Expected Behavior
I have one old/existing node with Centos 6.6 on which the command /usr/bin/curator runs fine.
Its an AWS EC2 instance with HVM virtualization and root file system as instance store:
```
[root@elasticsearch-01 ~]# /usr/bin/curator
Usage: curator [OPTIONS] ACTION_FILE

Error: Missing argument "action_file".
[root@elasticsearch-01 ~]# more /etc/system-release
CentOS release 6.6 (Final)
<production>[root@elasticsearch-01 ~]# ls -lrth /usr/bin/curator
lrwxrwxrwx 1 root root 34 Mar 27  2017 /usr/bin/curator -> /opt/elasticsearch-curator/curator
<production>[root@elasticsearch-01 ~]# lsattr /opt/elasticsearch-curator/curator
--------------- /opt/elasticsearch-curator/curator
```

### Actual Behavior
I migrated curator to a new EC2 instance with the same HVM virtualization and root file system as EBS.  It is giving error like this:
```
[root@elasticsearch-02 ~]# /usr/bin/curator
Fatal error: unable to stat executable
[root@elasticsearch-02 ~]# more /etc/system-release
CentOS release 6.9 (Final)
[root@elasticsearch-02 ~]# ls -lrth /usr/bin/curator
lrwxrwxrwx 1 root root 34 Jan 26 17:20 /usr/bin/curator -> /opt/elasticsearch-curator/curator
[root@elasticsearch-02 ~]# lsattr /opt/elasticsearch-curator/curator
-------------e- /opt/elasticsearch-curator/curator
```

### Steps to Reproduce the Problem
As shown above, you can launch an EC2 instance with HVM virtualization and root File system as EBS and install elasticsearch-curator to reproduce the issue.

### Specifications

  - Version: elasticsearch-2.4.1, elasticsearch-curator-4.2.6
  - Platform: Linux
  - Subsystem: AWS EC2 instance with CentOS 6.9

## Context (Environment)

Pruning of old indexes is impacted due to this issue.

I have posted all the details above.  May be this is a linux file system issue, i googled a lot but didn't find any solution for it.

Curator when migrated to a newer EC2 instance gives error.
## Detailed Description

I am looking for a solution that might be system related, but i am not sure, that's why creating this issue.

**Comment by untergeek** [comment]
Are you 100% sure you got the 4.2.6 release of Curator installed?  Can you reinstall from the RPM just to be sure?  That error can happen if a binary was compiled against the wrong version of libc.  RedHat tends not to change libc versions in minor point releases.

**Comment by untergeek** [comment]
Even double-checking by doing 

```
ls -l /opt/elasticsearch-curator/bin/curator
file /opt/elasticsearch-curator/bin/curator
md5sum /opt/elasticsearch-curator/bin/curator
``` 
on both machines to fully compare would be a good idea.

Also, what is the `e`?

```
<production>[root@elasticsearch-01 ~]# lsattr /opt/elasticsearch-curator/curator
--------------- /opt/elasticsearch-curator/curator
```
**vs**
```
[root@elasticsearch-02 ~]# lsattr /opt/elasticsearch-curator/curator
-------------e- /opt/elasticsearch-curator/curator
```
Second dash from the right, just before `/opt/elasticsearch-curator`?

**Comment by satish-chef** [comment]
@untergeek Thank you very much for your reply.  
I un-installed and re-installed the rpm of elasticsearch-curator-4.2.6-1.x86_64 three times but it didn't help.  
I ran all the 3 command that you gave and it has the same results from both the nodes:

```
## Results from old node:
[root@elasticsearch-01 ~]# ls -l /opt/elasticsearch-curator//curator
-rwxrwxr-x 1 root root 2633352 Jan 27  2017 /opt/elasticsearch-curator//curator
[root@elasticsearch-01 ~]# file /opt/elasticsearch-curator//curator
/opt/elasticsearch-curator//curator: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped
[root@elasticsearch-01 ~]# md5sum /opt/elasticsearch-curator//curator
6427474f1fc8d25af26f549d476cc4cc  /opt/elasticsearch-curator//curator
```
```

## Results from new node
[root@elasticsearch-02 ~]# ls -l /opt/elasticsearch-curator//curator
-rwxrwxr-x 1 root root 2633352 Jan 27  2017 /opt/elasticsearch-02-indexer-elastic-us-east-1e-30.mashery.com ~]# file /opt/elasticsearch-curator//curator
/opt/elasticsearch-curator//curator: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped
[root@elasticsearch-02 ~]# md5sum /opt/elasticsearch-curator//curator
6427474f1fc8d25af26f549d476cc4cc  /opt/elasticsearch-curator//curator
```
The "e" is the extent format - https://en.wikipedia.org/wiki/Chattr#Attributes
That "e" is not relevant because the binary /opt/elasticsearch-curator/curator_cli has the same attribute but is still executable using the symink present in /usr/bin/:
[ Apologies for providing extra but irrelevant info, i thought this might be the issue, but its not ]
```
## Results from new node
[root@elasticsearch-02 ~]# /usr/bin/curator_cli
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...

Options:
  --config PATH       Path to configuration file. Default:
                      ~/.curator/curator.yml
  --host TEXT         Elasticsearch host.
  --url_prefix TEXT   Elasticsearch http url prefix.
  --port TEXT         Elasticsearch port.
  --use_ssl           Connect to Elasticsearch through SSL.
  --certificate TEXT  Path to certificate to use for SSL validation.
  --client-cert TEXT  Path to file containing SSL certificate for client auth.
  --client-key TEXT   Path to file containing SSL key for client auth.
  --ssl-no-validate   Do not validate SSL certificate
  --http_auth TEXT    Use Basic Authentication ex: user:pass
  --timeout INTEGER   Connection timeout in seconds.
  --master-only       Only operate on elected master node.
  --dry-run           Do not perform any changes.
  --loglevel TEXT     Log level
  --logfile TEXT      log file
  --logformat TEXT    Log output format [default|logstash|json].
  --version           Show the version and exit.
  --help              Show this message and exit.

Commands:
  allocation        Shard Routing Allocation
  close             Close indices
  delete_indices    Delete indices
  delete_snapshots  Delete snapshots
  forcemerge        forceMerge index/shard segments
  open              Open indices
  replicas          Change replica count
  show_indices      Show indices
  show_snapshots    Show snapshots
  snapshot          Snapshot indices
[root@elasticsearch-02 ~]# ls -lrth /usr/bin/curator_cli
lrwxrwxrwx 1 root root 38 Jan 26 17:20 /usr/bin/curator_cli -> /opt/elasticsearch-curator/curator_cli
[root@elasticsearch-02 ~]# file /opt/elasticsearch-curator/curator_cli
/opt/elasticsearch-curator/curator_cli: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped
```

Below is the list of libc packages installed on the node on which i created rpm for elasticsearch-curator(i used fpm tool to create the rpm):

```
[root@rpm-server ~]# rpm -qa  | grep -i libc
glibc-headers-2.12-1.166.el6_7.7.x86_64
glibc-common-2.12-1.166.el6_7.7.x86_64
libcgroup-0.40.rc1-5.el6_5.1.x86_64
libcom_err-1.41.12-18.el6_5.1.x86_64
libcap-ng-0.6.4-3.el6_0.1.x86_64
libcap-2.16-5.5.el6.x86_64
glibc-devel-2.12-1.166.el6_7.7.x86_64
libcurl-7.19.7-37.el6_5.3.x86_64
glibc-2.12-1.166.el6_7.7.x86_64
libcom_err-devel-1.41.12-18.el6_5.1.x86_64
[root@rpm-server ~]# more /etc/system-release
CentOS release 6.5 (Final)
```

**Comment by untergeek** [comment]
So `curator_cli` is working but `curator` does not?  That seems odd.  Did I read that correctly?

What happens if you execute `/opt/elasticsearch-curator/curator` directly, instead of via the symlink?

**Comment by satish-chef** [comment]
Yes you read that correctly, curator_cli is getting executed correctly but curator is not.

When i execute /opt/elasticsearch-curator/curator directly, it runs fine.  As a temporary patch, i have setup the cron to use this binary, but frankly i need the symlink `/usr/bin/curator` to work as it used to work on the old instance :

```
<production>[root@ elasticsearch-02 ~]# /opt/elasticsearch-curator/curator
Usage: curator [OPTIONS] ACTION_FILE

Error: Missing argument "action_file".
```

**Comment by untergeek** [comment]
This is an anomaly which has been observed in RedHat/CentOS machines before.  It's something unusual about how they do things that nobody (not even at RedHat) has been able to explain satisfactorily.

My recommendation is to (as root or via sudo) remove the symlink at `/usr/bin/curator` and re-link it again to see if that does anything differently.

**Comment by satish-chef** [comment]
I tried deleting the creating the symlink `/usr/bin/curator`.  I also tried creating symlink on other paths on the instance, but none of it works.  
Is it possible to compile the rpm for elasticsearch-curator-4.2.6 for Centos 6.9 ?
If yes, can you please share the steps, i will spin up an instance and create the rpm using fpm.

**Comment by untergeek** [comment]
> I tried deleting the creating the symlink `/usr/bin/curator`. I also tried creating symlink on other paths on the instance, but none of it works.

This seems to me to indicate something amiss with RedHat, if a functioning binary cannot be effectively symlinked.

> Is it possible to compile the rpm for elasticsearch-curator-4.2.6 for Centos 6.9 ?

You can try to use the scripts that I used [here](https://github.com/elastic/curator/tree/v4.2.6/unix_packages).

**Comment by joernott** [comment]
We have the same problem. A colleague of mine tested the following:
- Relative symlink works as intended, the absolute symlink doesn't
- curator residing on XFS file system or on ext4 does not change anything

Version in use: 4.2.6 on RHEL 7.4

**Comment by jamshid** [comment]
FWIW upgrading to elasticsearch-curator 4.3.1 (that's the latest in repo http://packages.elastic.co/curator/4/centos/6 and 7) fixed this weird symlink problem.

**Comment by untergeek** [comment]
Stale. Cannot replicate.
