### ISSUE TITLE
add max_size as valid option for rollover.

### ISSUE THREAD

**Issue by evilezh** [elastic/curator#1140]
```
--- option_defaults.py
+++ option_defaults.py
@@ -10,6 +10,7 @@
     return {
         Optional('conditions'): {
             Optional('max_age'): Any(str, unicode),
+            Optional('max_size'): Any(str, unicode),
             Optional('max_docs'): Coerce(int)
         }
     }

```

**Comment by untergeek** [comment]
That has to go in a lot more places than just the option defaults. It also has to have version detection for the versions of Elasticsearch that Curator supports, but that don't support this new feature.

**Comment by evilezh** [comment]
I just put idea. 
For me it worked - just patching that file.

**Comment by untergeek** [comment]
What I mean is that you can't just add it there.  It also has to be documented.  And documented that this feature is only acceptable in certain versions of Elasticsearch.  For example, it's listed in the [6.1 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/indices-rollover-index.html) but not in the [6.0 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/indices-rollover-index.html).  This means that if that is added and some user tries to use it in any version older than 6.1, they'll get an error.  This has to be properly caught.
