### ISSUE TITLE
filed_stats equivalent for Elasticsearch 6.x

### ISSUE THREAD

**Issue by burandobata** [elastic/curator#1155]
Hey,

field_stats API has been removed in version 6 of elasticsearch. I still want to delete the indexes based on maximum timestamp value with curator.

Elasticsearch docs says this can be achieved with aggregations. Are there any plans to add it to curator? Or support in any other way?

**Comment by untergeek** [comment]
Excellent question.  [It's already resolved in 5.4](https://github.com/elastic/curator/blob/v5.4.1/curator/indexlist.py#L254-L276).  It's still called "field_stats" in Curator, but it is actually just queries/aggregations.

So, long story short: You're already covered.

**Comment by untergeek** [comment]
And, yes, Curator 5.4 supports Elasticsearch 6
