### ISSUE TITLE
Rollover suffix not resetting on daily rollover

### ISSUE THREAD

**Issue by danielkasen** [elastic/curator#1174]
So I have an issue where the rollover index works nicely except 1 bug. When the new daily index gets created it gets created with the next rollover ID:

test-2018.03.18-000009
test-2018.03.19-000010

I fear that this will eventually lead me to run out of IDs as it's not respecting the date. Is there a way to correct this problem?

Creating the Alias:

#Rollover index
```
PUT /%3Ctest-%7Bnow%2Fd%7D-1%3E
{
  "aliases": {
    "test": {}
  }
}
```

Curator action to rollover
```actions:
  1:
    action: rollover
    description: >-
      Rollover the index associated with index 'name', which should be in the
      form of prefix-000001 (or similar), or prefix-YYYY.MM.DD-1.
    options:
      name: test
      conditions:
        max_age: 1d
        max_docs: 1000
      disable_action: False```

**Comment by untergeek** [comment]
The behavior you are seeing is exactly what is described [in the Elasticsearch documentation for the Rollover API](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-rollover-index.html#_using_date_math_with_the_rollover_api).  Curator has no control over this.

There is an undocumented `new_index` option for rollover that allows you to specify what the new index name should be.  I should document this feature for the 5.5 release.

**Comment by danielkasen** [comment]
ok, I can live with this for now and fix it when the new version is released. Thanks.
