### ISSUE TITLE
Error: Elasticsearch version 6.1.2 incompatible with this version of Curator (6.1.2)

### ISSUE THREAD

**Issue by matisku** [elastic/curator#1186]
Hi,

ElasticSearch: 6.1.2
Curator: 6.1.2

Error I get
```Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 6.1.2 incompatible with this version of Curator (6.1.2)
run-parts: /etc/periodic/daily/elasticsearch-curator: exit status 1
```

TBH this is really strange to me:
```Error: Elasticsearch version 6.1.2 incompatible with this version of Curator   (6.1.2)```

**Comment by untergeek** [comment]
That's an old bug, where the Curator version was incorrectly reported.  It's been fixed. See #1089

**Comment by amccool** [comment]
hmmm on debian got this
`Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 6.2.4 incompatible with this version of Curator (6.2.4)`

**Comment by untergeek** [comment]
Sorry.  There's not much I can do with old versions misreporting due to a bug I've since fixed.

**Comment by untergeek** [comment]
@topkool this is a fixed bug. You are installing an older version of Curator.  Please update to version 5.5.4 of Curator, as [compiled for Debian 9](
https://packages.elastic.co/curator/5/debian9/pool/main/e/elasticsearch-curator/elasticsearch-curator_5.5.4_amd64.de)b.
