### ISSUE TITLE
Allow elasticsearch 6.x in requirement

### ISSUE THREAD

**Issue by triat** [elastic/curator#1187]
I've been running the tests with elasticsearch 6.2.0 and I can't see any tests failing.

Is there any main blocker to not allow the upgrade or is it just historical?

**Comment by untergeek** [comment]
That requirement is for the [Elasticsearch-py](https://github.com/elastic/elasticsearch-py) python module, not Elasticsearch itself.  As you can see in the [compatibility matrix](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/version-compatibility.html), Elasticsearch 6.x is supported in the current versions of Curator 5.x (support was added in Curator 5.4).

**Comment by triat** [comment]
Yes sorry, I saw about the support of elasticsearch 6 and that was about `elasticsearch-py` 6.2, there is a limit in the requirement file of curator saying `elasticsearch>=5.4.0,<6.0.0` but I couldn't see any issue with letting `elasticsearch-py` install the 6.x. 

I am certainly missing something but I wanted to check

**Comment by triat** [comment]
Ok, I guess we're misunderstanding each other, my apologize: what I am doing:

```
pip install elasticsearch-curator
pip install elasticsearch==6.2.0
python setup.py test
```
Which results in no tests error. Is there any other reason than your requirement that you keep `elasticsearch>=5.4.0,<6.0.0` ?

**Comment by untergeek** [comment]
That's because the tests do not cover SSL.  The errors for `elasticsearch-py` versions greater than 5.5.2 show up when you use SSL.

This will be addressed in a future version.  Until then, the requirement stays tied to `5.5.2`.
