### ISSUE TITLE
Elasticsearch Curator API Exception "NoIndices: index_list object is empty."

### ISSUE THREAD

**Issue by keshara** [elastic/curator#1194]
###  I am currently working with Elsticsearch Curator Python API version 5.5.0 and it works fine with Close, Open, Delete actions. 

My code is;

```
import elasticsearch
import curator

client = elasticsearch.Elasticsearch()

ilo = curator.IndexList(client)
ilo.filter_by_regex(kind='prefix', value='logstash-')
ilo.filter_by_age(source='name', direction='older', timestring='%Y.%m.%d', unit='days', unit_count=30)
delete_indices = curator.Close(ilo)
delete_indices.do_action()
```

### However, when executed a Close action on a index which is already in Close state the script itself throws following exception;
NoIndices: index_list object is empty.

### Specifications

  - Version: Elasticsearch Curator 5.5.0
  - Platform: Ubuntu 16.04
  - Subsystem:

**Comment by keshara** [comment]
First of all, thank you very much for the quick response.

Yes, indeed it worked. However, this is a python work-around. Don't we actually have a stanza to set this "ignore_empty_list: True" in a python script.

Thanks.

**Comment by untergeek** [comment]
No.  That's how it's actually handled in Curator's command-line code.  That setting is parsed from the `option` block of the `action`, and then used to catch errors before proceeding accordingly.  The code for this behavior is [here](https://github.com/elastic/curator/blob/v5.5.1/curator/cli.py#L160-L180).  `ignore_empty_list` is not handled in the action code itself, but between actions, based on how the previous action behaved.  This is why it is caught where it is.

**Comment by keshara** [comment]
Well that is clear enough to understand the concept behind this curator python implementation.

Thanks for your valuable time.
