### ISSUE TITLE
Use python >= 2.7.9 in Dockerfile to avoid SSL Warning 'SNIMissingWarning'

### ISSUE THREAD

**Issue by beckjim** [elastic/curator#1196]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

Building curator with the provided Dockerfile currently leads to python SSL warnings: 'SNIMissingWarning', when connecting to an SSL secured ES database.

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version: curator 5.5.1
  - Platform: Linux/Docker
  - Subsystem:

## Detailed Description

Dockerfile currently uses python 2.7.8 (maybe for good reason, but not obvious for me).
This leads to python SSL warnings: 'SNIMissingWarning', when using curator within the resulting docker image and connecting to an SSL secured ES database:

```
SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

```
Details for this warning can be found here: 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Easiest ways to supress this warning is to use python >= 2.7.9 (or disable those warnings from within python script itself).

This is actually not a bug, but a bit annoying. Moreover usage of SNI could be useful for some people anyway.
Everybody can easily change the Dockerfile himself, but maybe it's a good idea to increase python version in the provided Dockerfile directly.

Thank you!

**Comment by DaveyDevOps** [comment]
This should be closed by #1111
