### ISSUE TITLE
Document new_index for use in rollover action

### ISSUE THREAD

**Issue by danielkasen** [elastic/curator#1197]
Hello, I'm using curator 5.5 and ES 6.2 and am trying to get the index name in the creation during the rollover step. I can go it manually but can't find an option to do this in curator. Is there a way to do this currently, or can I use this bug as a feature request?

Manual API Call
`POST /filebeat/_rollover/%3Cfilebeat-%7Bnow%2Fm%7BYYYY.MM.dd.HH.mm%7D%7D-1%3E
{
  "conditions": {
    "max_age":   "1d",
    "max_size": "1mb"
  },
  "settings": {
    "index.number_of_shards": 1
  }
}`

Curator Call
`actions:
  1:
    action: rollover
    description: >-
      Rollover the filebeat index
    options:
      name: filebeat
      conditions:
        max_age: 1d
        max_size: 1mb`

**Comment by danielkasen** [comment]
NVM found it as new_index as an option. Looks like the docs to specify this though, had to dig through a commit: https://github.com/elastic/curator/commit/2bb0f377f5285028d5eb08f2db53ccb243eb8735

**Comment by danielkasen** [comment]
Also, important not for anyone trying this. It only accepts date format so you have to do something like 
new_index: "<nginx-{now/H{YYYY.MM.dd.HH}}-1>"

**Comment by untergeek** [comment]
Added in #1214
