### ISSUE TITLE
Python 2.7 unicode error

### ISSUE THREAD

**Issue by RameshRM** [elastic/curator#1198]
Unable to Create Index Aliases for ES 5.5 and Curator version 5.4 and Python 2.7

Error is **'`Failed to complete action: alias.  <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)
`**

**Comment by untergeek** [comment]
Don't use Python 2.7 if you can, as its Unicode support is horrible, and will be [EOL as of 1 Jan 2020](https://pythonclock.org/).  The pre-compiled versions available as RPM and DEB packages are built with self-contained versions of Python 3.6, and should not suffer from this shortcoming.

Also, which _release_ of Python 2.7 are you using?  Anything older than 2.7.7 may not be fully supported anyway.  I'm trying to get away from supporting 2.7 as much as I can with all of my Python projects, but there are just too many users of Linux distributions (which shall remain unnamed) which not only ship with but depend on ancient versions of Python.

**Comment by untergeek** [comment]
Closing for now.  If you believe this is in error, please feel free to re-open with a comment.
