### ISSUE TITLE
Bug in Rollover _check_max_size() call

### ISSUE THREAD

**Issue by diranged** [elastic/curator#1202]
https://github.com/elastic/curator/blob/d1a603b0a18cc40700644f3229801ea8067c3c71/curator/actions.py#L863

https://github.com/elastic/curator/blob/d1a603b0a18cc40700644f3229801ea8067c3c71/curator/actions.py#L884

https://github.com/elastic/curator/blob/d1a603b0a18cc40700644f3229801ea8067c3c71/curator/actions.py#L889-L899

This method expects a dict to be passed to it that has the key `conditions` inside of it. However, it seems that you are instead passing the _value_ of the `conditions` dict to it. This basically means that https://github.com/elastic/curator/blob/v5.5.1/curator/actions.py#L890-L899 always raises an exception, and the overall function does nothing but return back the data it was passed.

**Comment by untergeek** [comment]
Thanks for catching this.

**Comment by untergeek** [comment]
Fixed in #1212
