### ISSUE TITLE
Curator should ignore indices with index.lifecycle.name set

### ISSUE THREAD

**Issue by eskibars** [elastic/curator#1207]
In an upcoming version of Elasticsearch, we expect to have built-in index lifecycle management (ILM) for several common cases.  In order to avoid ILM and Curator "fighting for" control of an index (e.g. allocating and reallocating to different nodes based on partially or fully duplicative policies), we should check for indices that ILM is "in control of" and ignore them.  Having `index.lifecycle.name` set is such an indicator.

**Comment by untergeek** [comment]
👍 
The more context and information you can give me about these pending changes, the better.  I'll be sure to add this functionality soon.

**Comment by eskibars** [comment]
Relates https://github.com/elastic/elasticsearch/issues/29823

**Comment by untergeek** [comment]
Closed by #1218
