### ISSUE TITLE
How can I run curator with many "actions.yml" file?

### ISSUE THREAD

**Issue by sergii-rolskii** [elastic/curator#1217]
I have one "actions.yml" file with over 2000+ strings, I would like to separate this.
How can I run curator with many actions.yml file?
For example:
I have many indexes and many actions (alias, delete, snapshot, etc)
I want to create many actions file: my_index.alias.yml, my_index.snapshot.yml ... etc and run command like this:
curator --config CONFIG.YML /path/to/folder_with_actions_files/*.yml
When I try this, I got an error:
`Error: Invalid value for "action_file": Path "/curator/actions/*.yml" does not exist.`

**Comment by untergeek** [comment]
Curator does not support file globbing, and probably never will.  It is more likely that action storage in Elasticsearch will happen first.

**Comment by untergeek** [comment]
Also, Curator v6 will allow you to define multiple actions to run against a single filter-set, removing the need for redundancy, saving some of that configuration length.

**Comment by sergii-rolskii** [comment]
@untergeek thanks for your reply.
