### ISSUE TITLE
curator does not start (no errors and nothing does)

### ISSUE THREAD

**Issue by vdmitrief** [elastic/curator#1225]
Hi, Experts
I have CentOS 7, install curator latest version (5.5.3)
My config (/etc/curator/curator.yml) is:
client:
  hosts:
      - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile: /var/log/curator.log
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

My Action-config (/etc/curator/delete_indices.yml) is:
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 7 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
     - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
     - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
      exclude:

I use launch command:
/usr/bin/curator --config /etc/curator/curator.yml --dry-run /etc/curator/delete_indices.yml
or
/usr/bin/curator --config /etc/curator/curator.yml /etc/curator/delete_indices.yml

but nothing happens and no errors
log-file in debug-mode is:
2018-05-23 11:37:10,095 DEBUG                curator.cli                    run:108  Client and logging options validated.
2018-05-23 11:37:10,095 DEBUG                curator.cli                    run:112  default_timeout = 30
2018-05-23 11:37:10,095 DEBUG                curator.cli                    run:116  action_file: /etc/curator/delete_indices.yml

Same config and action files working on Ubuntu 16.04 + curator 5.4.1
I tried to downgrade the curator to 5.4.1 but it did not help

Can I install any libraries for the curator work?

**Comment by vdmitrief** [comment]
Fixed !
deleted files, created them again with the same content and worked

**Comment by untergeek** [comment]
Since you didn't encapsulate your file data with triple back ticks, e.g.

    ```
    PASTE HERE
    ```

I can't tell, but that error only happens when your YAML file is improperly indented.
