### ISSUE TITLE
Branch off master and tag versions against it.

### ISSUE THREAD

**Issue by willejs** [elastic/curator#1230]
### Expected Behavior
When I browse the project, I should see the latest code on master, and tags (and releases) against it like most other projects. Alternatively the latest code branch could be the default branch in github.

### Actual Behavior
There are many branches, and the default branch is old.

I guess this is because you are trying to maintain backwards compatibility and patch old versions? Right now its a bit confusing and I ended up making a patch against master, not knowing this was the case. I also presumed the project was inactive as the default master branch hadnt had commits since 2017.

**Comment by untergeek** [comment]
I'm working on a huge change to the API for 6.0 and it's taken a long time to put it in.  I don't want anyone pushing to master until that's in.  I've just been instructing people to patch against the `5.x` branch.

**Comment by untergeek** [comment]
I just back ported everything from 5.x into master in https://github.com/elastic/curator/commit/736f6fde34cc4989b93ba553c930983848d90883
