### ISSUE TITLE
Filter by count excludes despite exclude=False when at least one index does not match the pattern

### ISSUE THREAD

**Issue by epellizzer** [elastic/curator#1251]
Hi,

I'm desperately trying to explicitly select the last index of a sequence (`index-000001`, `index-000002`, ...), and the best filter for that is `count`. However, the 'inclusion' behavior that I need here does not work.

After digging into the code, I realized the following line in the `filter_by_count` method, which is executed when at least one index does not match the provided pattern (which is almost always the case), overwrites the parameter `exclude` and the 'include' behavior is lost.

https://github.com/elastic/curator/blob/5fdcc337625c6a7e9aeeb90de625b54b92cbbcb7/curator/indexlist.py#L943

Do you see any workaround I could use for my situation? I'd like to avoid selecting by age, which is kind of uncertain depending on when the action will be executed.

**Comment by untergeek** [comment]
Can you please elaborate a bit more on what you're seeing?  I don't have as much time this week to dedicate to this, so a slightly more in-depth description will be helpful.

**Comment by epellizzer** [comment]
Ok, sorry for not being very clear.

I have an action where I want to select the latest index of a sequence. I would do that with:
```yaml
filtertype: count
  count: 1
  pattern: ^(myindex)-\d{6}$
  exclude: false
  reverse: true
```

Except the `exclude: false` part is ignored. I still get all _but_ the last index of the sequence, that is exactly the same result as if I had used `exclude: true`.

Though I'm not use to Python, I can see from the code of the function `filter_by_count` in `indexlist.py` that as soon as at least one index is rejected because it doesn't match the regex, the variable `exclude` is set to `True`. But this variable is the method's parameter, and as a result the rest of the method effectively behaves as if `exclude` had been set to `True`.

Now I realize I should be able to work around that by first filtering with a `pattern` filter. That way, the `count` filter would not reject any index based on the regex, and the `exclude` parameter should not be overwritten.

I hope it's clearer :).

**Comment by untergeek** [comment]
> Now I realize I should be able to work around that by first filtering with a `pattern` filter. That way, the `count` filter would not reject any index based on the regex, and the `exclude` parameter should not be overwritten.

Bingo! 

I was pretty sure this is what you meant, and it looks like you found the way to use the `pattern` filter to only catch the ones you want (which is exactly what I would have recommended).  

I'm sorry it wasn't as simple as using an advanced regex to do both in one step—which _does_ make a lot of sense.  Unfortunately, Curator isn't quite smart enough to do that, since the indices don't come from the Elasticsearch API sorted or formatted.  I'm kind of forced to take a more naïve approach, and not presuppose what the end user wants to do, hence the need for multiple filters.

If you're good to go, feel free to close this.  If you need anything else, please let me know.

**Comment by untergeek** [comment]
Also, the `pattern` feature here was to fulfill a slightly different purpose.  See https://github.com/elastic/curator/issues/1046#issue-254002362 and #1044 for more information.  The idea was that you be able to do counts across _several_ matching patterns and keep _n_ indices for each of those patterns.

**Comment by epellizzer** [comment]
It works with the workaround. Thank you, I'm closing.
