### ISSUE TITLE
Grooming not deleting data with timestring '%Y.%m.%d.%H'

### ISSUE THREAD

**Issue by bamb00** [elastic/curator#1253]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue
Grooming is not deleting data correctly with timestring set at %Y.%m.%d.%H

### Expected Behavior
After an hours has passed the grooming logs show deleting empty indices 

### Actual Behavior

       2018-08-07 17:43:00,787 INFO      Preparing Action ID: 1, "delete_indices"
       2018-08-07 17:43:00,807 INFO      Trying Action ID: 1, "delete_indices": Clean up ES by deleting 
       logstash indices
       2018-08-07 17:43:01,009 INFO      Skipping action "delete_indices" due to empty list: &lt;class 
       'curator.exceptions.NoIndices'&gt;
       2018-08-07 17:43:01,010 INFO      Action ID: 1, "delete_indices" completed.
       2018-08-07 17:43:01,010 INFO      Action ID: 2: "delete_indices" not performed because 
       "disable_action" is set to True
       2018-08-07 17:43:01,010 INFO      Job completed.

### Steps to Reproduce the Problem

      1:
        action: delete_indices
        description: "Clean up ES by deleting logstash indices"
        options:
          timeout_override:
          ignore_empty_list: True
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d.%H'
          unit: hours
          unit_count: 1
          field:
          stats_result:
          epoch:
          exclude: False
        - filtertype: space
          disk_space: .01
          use_age: True
          source: creation_date
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: closed
          exclude: true

### Specifications

  - Version: 5.5
  - Platform: CentOS 7.5
  - Subsystem:

**Comment by untergeek** [comment]
This is not a problem:
```
   2018-08-07 17:43:00,787 INFO      Preparing Action ID: 1, "delete_indices"
   2018-08-07 17:43:00,807 INFO      Trying Action ID: 1, "delete_indices": Clean up ES by deleting 
   logstash indices
   2018-08-07 17:43:01,009 INFO      Skipping action "delete_indices" due to empty list: <class 
   'curator.exceptions.NoIndices'>
```
This is telling you that there were no indices matching your patterns, resulting in an empty list, so nothing was deleted.

The second error says that action 2 (which was not included here) was not performed due to `disable_action` being set to `True`, which is also not a problem.

It sounds more like you have no indices, or something in your pattern matching is wrong.  What do you see if you enable `loglevel: DEBUG` in the `logging` block of the client yaml file?  You'll see all of the indices being evaluated with this set, which will be helpful for troubleshooting.

**Comment by bamb00** [comment]
This is the idex at the time of the grooming,

       green open logstash-2018.08.07 WnIpi4-yTDqPtT9e30iHZg 5 1 4464 0 8.1mb 4mb

**Comment by untergeek** [comment]
> 
```
timestring: '%Y.%m.%d.%H'
```
Does not match
```
logstash-2018.08.07
```
This is why you get an empty list.

Try dropping the `.%H` off, and change the `units`:
```
timestring: '%Y.%m.%d'
units: days
```
This will still not match `logstash-2018.08.07`, but it will match `logstash-2018.08.06` and older.

**Comment by bamb00** [comment]
@untergeek Thanks for pointing out.

I have a question regarding having multiple filtertype in action.  There are three filter type in the action.  For the grooming to trigger all three condition has to be met in age, space, and pattern not just one filtertype.

**Comment by untergeek** [comment]
It is `AND`.

**Comment by untergeek** [comment]
Also, the `space` filter is the sum total of primaries and all replicas.

**Comment by bamb00** [comment]
can you pls explain?

**Comment by untergeek** [comment]
When the `space` filter calculates disk usage per index, it uses the sum of all primaries and replicas for that index.  It is the `store.size`, rather than just the primaries.

**Comment by bamb00** [comment]
For index1 store size is 3 gb and index2 store size is 2.5 gb and the disk_space is set to 5GB.  Then index index1 is deleted.  Is that the behavior?

**Comment by bamb00** [comment]
I ran it in debug mode.  The log show index that is actionable remain in the list to be deleted and index that was not actionable removed from list.

Thanks for the help.

**Comment by untergeek** [comment]
You are welcome.
