### ISSUE TITLE
Add .security to Kibana filter

### ISSUE THREAD

**Issue by cpats007** [elastic/curator#1267]
Hi. We have had na issue recently when using Curator to close indexes that it has closed the .security index, meaning our cluster went down due to elements not being able to connect.

Upon reviewing, I can see there is a Kibana filter which removes the .kibana indexes from the list. Is it possible to either:

a) Add the .security files to this filter
b) create a new filter type of "system" or "security" which will basically omit all of the main system index files (or possibly anything beginning with .)

I know we can create a prefix filter to do this, it just seems that seen as we have the Kibana filter, it would make sense to add something to that really?

Many thanks

**Comment by untergeek** [comment]
This is moot now that Elastic is protecting system indices.
