### ISSUE TITLE
Invalid Request with Long URL

### ISSUE THREAD

**Issue by Careidas77** [elastic/curator#1285]
I'm using Curator 5.5 to try to delete old indices. This is my action file:

> 1:
    action: delete_indices
    description: >-
      Delete indices [...].
    options:
      ignore_empty_list: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: whatever-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 45

I get this error when executing that says:

`ERROR     Failed to complete action: delete_indices.  <class 'KeyError'>: 'indices'`

I removed the black-listed applications to see more of what's going on, and can see that there are some requests resulting in a `400`, like:

`GET http://127.0.0.1:9200/very,long,list,of,very,many,different,indices [status:400 request:0.000s]`

If I copy the request and run it elsewhere, I get the same result. If I shorten the list of indices in the request though, it's OK.

**Comment by untergeek** [comment]
Question: What version of Elasticsearch are you using? Is it behind a proxy or load balancer of any kind?

Elasticsearch does have an out-of-the-box 4k URL size limit, but [Curator knows how to compensate for this, and generally limits the URL size to around 3k bytes, preventing this from happening](https://github.com/elastic/curator/blob/v5.5.4/curator/utils.py#L606-L627).  Every call Curator makes that might require this batched approach uses it.

It is possible—but not very likely—that you have found a way around this, but it would require a single index name that exceeds the difference between 4k and 3k bytes, which would be a rather long index name, indeed (but Elasticsearch doesn't allow more than 255 character index names). If you follow the above link and read the code, it adds indices and commas one by one until the URL crosses the 3k byte threshold. You might be able to grab the entire URL from the logs and do a byte count on the string and see just how long it actually is.

It is possible that this URL size limit has been _decreased_ in the configuration, which would also defeat this limit.  Conversely, it is possible to increase the limit above the 4k limit in the Elasticsearch configuration.

To troubleshoot, it would be helpful to run Curator with DEBUG logging and the logging `blacklist` set to an empty array (I can't tell if you added both DEBUG logging _and_ removed the blacklist):

```
logging:
    loglevel: DEBUG
    # ... any other settings here
    blacklist: []
```
Set this in your client configuration yaml file and run again.  There will be much more information, especially from the `urllib3` library which actually is what captures the 400 error.  Hopefully there is much more information contained there to explain what is happening.

**Comment by Careidas77** [comment]
@untergeek I don't think Curator is the culprit. There seems to be a proxy in between Curator and Elastic that's messing things up. I managed to bypass it, and now the request batches goes through just fine.

So, sorry for taking up your time, but thank you again for responding.
