### ISSUE TITLE
用pip下载下来的，本身没有自带yml配置文件，查看命令行，也没有生成命令的命令

### ISSUE THREAD

**Issue by 17721524631** [elastic/curator#1314]
用pip下载下来的，本身没有自带yml配置文件，查看命令行，也没有生成命令的命令

windows环境    作者大大帮忙看看怎么回事？

**Comment by 17721524631** [comment]
> RPM和DEB安装程序也不提供默认的YAML配置文件。
> 
> 有关[示例](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/examples.html)和[客户端配置文件说明，](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/configfile.html)请参阅[官方文档](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/index.html)。[](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/examples.html)[](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/configfile.html)

已经创建了这个目录   当执行这段命令时   依然报错
curator --config ~/.curator/curator

**Comment by 17721524631** [comment]
> > RPM和DEB安装程序也不提供默认的YAML配置文件。
> > 有关[示例](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/examples.html)和[客户端配置文件说明，](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/configfile.html)请参阅[官方文档](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/index.html)。
> 
> 已经创建了这个目录 当执行这段命令时 依然报错
> curator --config ~/.curator/curator.yml

**Comment by 17721524631** [comment]
> 还有许多其他[示例操作文件](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/examples.html)。
> 
> 这是一个[`delete_indices`行动](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/ex_delete_indices.html)。

原来是要一次性配置两个   用您的这种格式试了一遍    成功配置了   谢谢

**Comment by untergeek** [comment]
Glad you got it figured out. Closing this issue.
