### ISSUE TITLE
Curator should not exit with an error when delete_indices has nothing to delete

### ISSUE THREAD

**Issue by kciredor** [elastic/curator#1317]
## To submit a bug or report an issue
We have a cleanup cronjob that removes all indices older than 14 days, except for those starting with a . like .kibana:

`curator_cli --host foo delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":14},{"filtertype":"pattern","kind":"regex","value":"^\\..*","exclude":true}]'`

### Expected Behavior
When running the cleanup job on a cluster which has no data older than 14 days, curator will exit with an error, because there's nothing to delete.

### Actual Behavior
If there's nothing to do, that is just fine, it's should not result in an error.

### Steps to Reproduce the Problem
Run the curator_cli command I have mentioned before on a cluster without indices older than 14 days.

### Specifications
  - Version: ES 6.3.0, curator@30fe0410 (which fixed the '_' vs '-' bug parameter parser bug)
  - Platform: ES: Linux; Curator: alpine 3.8 container running in k8s cron
  - Subsystem:

## Context (Environment)
The error makes our cronjob fail and an alert being sent out. This should only happen upon actual errors. If there's nothing to delete, there's nothing to delete, which is fine.

## Detailed Description
My suggestion would be not to error out when Curator's filters result in an empty list. If this would raise concerns about backwards compatibility, adding an opt-in flag would be the way to go.

**Comment by TBeijen** [comment]
This effectively prevents curator from running without errors on new cluster that not yet have a certain amount of indexes.

**Comment by untergeek** [comment]
There's already a flag that covers this: `--ignore_empty_list`

```
$ curator_cli delete_indices --help
Usage: curator_cli delete_indices [OPTIONS]

  Delete Indices

Options:
  --ignore_empty_list             Do not raise exception if there are no actionable indices
...
```

This is the difference between running with and without `--ignore_empty_list` (yes, I know that this uses `show_indices`, but it works the same for all actions) :
```
$ curator_cli show_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"netfloo"}'
$ echo $?
1
$ curator_cli show_indices --ignore_empty_list --filter_list '{"filtertype":"pattern","kind":"prefix","value":"netfloo"}'
$ echo $?
0
```

**Comment by kciredor** [comment]
Awesome, thx @untergeek
