### ISSUE TITLE
Retry snapshot action 

### ISSUE THREAD

**Issue by mrtmexx** [elastic/curator#1320]
In the action of removing snapshots, there is a re-try implementation if there are processes that create snapshots.

There is a lack of the same functionality when creating a snapshot. I would like the curator not to give an error `cannot snapshot while a snapshot deletion is in-progress` or error `cannot snapshot while a snapshot creation is in-progress` when create the snapshot, but wait some time and try again create the snapshot

**Comment by untergeek** [comment]
Pseudo-duplicate of #1294, which functionality covers this.
