### ISSUE TITLE
Weekly Index Creation Problem

### ISSUE THREAD

**Issue by 32328254** [elastic/curator#1324]
- Version:curator5.6.0
  - Platform:centos
  - system:Centos7.2
  - Elasticesearch Version:5.6.12

local_time：2018-12-05:16:50

actions:
    action: create_index
    description: "create next week after new time-based index for test-commit"
    options:
        continue_if_exception: True
        name: '<test-commit-{now/w+4w{YYYY-ww}}>'

real result：test-commit-2018-01
expect result is test-commit-2019-01

**Comment by untergeek** [comment]
Please see the update provided by the Elasticsearch developers at 
https://github.com/elastic/elasticsearch/issues/36265#issuecomment-470924219
