### ISSUE TITLE
SSL_UNKOWN error on RedHat 7.5

### ISSUE THREAD

**Issue by hueyg** [elastic/curator#1328]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

Ran into problem where curator was simply ending when attempted to run.  DEBUG option seemed to show it ending sometime after certificate verification but no returned errors at this level.  I emptied the blacklist option and received the following errors:

 File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:847)

Reading post from others I attempted the following:

curl --cacert /etc/pki/tls/certs/logstash-forwarder.crt https://localhost:9200

       curl: (35) SSL received a record that exceeded the maximum permissible length.

Following up on that error I found several reports of this on the RedHat forums related to various other products which I assume all have to do with how SSL is handled with the included python libraries.  The workaround was to use http:// in the url instead of https:// and sure enough that resolved my curl error above.

I don't know if it is possible to change this in curator without changing source code so my fix for now is to use curator without SSL and this workaround has resolved my initial problem with curator although I would not consider it a permanent fix.

**Comment by untergeek** [comment]
This appears to be a `pip` based install. Have you tried the [all-in-one RPM](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.6/yum-repository.html#_direct_package_download_link_2)? You could also add the yum repo and go that route, if you like.

This all-in-one bundles all necessary Python libraries/modules, so it should hopefully not be bound by system dependencies the same way.

**Comment by untergeek** [comment]
For the record, this RPM also has a dependency on a higher release version of OpenSSL than the out-of-the-box RHEL/CentOS, which may also address the SSL issue on its own.

**Comment by hueyg** [comment]
Thanks unter.  I definitely installed via yum repo so not sure what dependency is off on my side.  Will check for updates on my openssl.

**Comment by untergeek** [comment]
Which yum repo? The [Curator one](
https://www.elastic.co/guide/en/elasticsearch/client/curator/5.6/yum-repository.html#_repository_configuration_)2?

**Comment by untergeek** [comment]
I will try to set up a clean CentOS 7.5 install and see if I can replicate this.

**Comment by hueyg** [comment]
Here is what I used.  Installed this a few weeks ago without configuring because I was pulled off on another project.

[curator-5]
name=CentOS/RHEL 7 repository for Elasticsearch Curator 5.x packages
baseurl=https://packages.elastic.co/curator/5/centos/7
gpgcheck=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1

**Comment by untergeek** [comment]
This should be addressed in Curator 5.8 as it bundles a compiled library from OpenSSL 1.1.1c
