### ISSUE TITLE
Correctly report task runtime in seconds

### ISSUE THREAD

**Issue by jkelastic** [elastic/curator#1335]
### Expected Behavior
Print the full time in nanos without 0. The correct time is 32663955100000003 nanos.

### Actual Behavior
Print the time as 0.32663955100000003

### Steps to Reproduce the Problem

  1. Run Curator for reindexing
  2.  Its adding a "0." while printing run time in nanos.

  For example, here the actual time was 326639551 nano seconds, but the curator added "0." before that which is wrong.

running_time_in_nanos = 0.32663955100000003

### Specifications

  - Version: Curator 5.6
  - Platform: Windows 7
  - Subsystem:

**Comment by untergeek** [comment]
This is just a reporting/logging error. It’s correct if it instead says, “run time in seconds” instead of nanoseconds, which is _very_ hard to visually correlate with seconds. The change will be to report seconds instead of nanoseconds.

**Comment by harshbajaj16** [comment]
Hi @untergeek ,

Can i change this from `running_time_in_nanos` to `running_time_in_seconds` and can create a pull against this?

Please confirm.

**Comment by untergeek** [comment]
Please, by all means. I will always accept and review pull requests.
