### ISSUE TITLE
forcemerge exits code 1 when index list empty

### ISSUE THREAD

**Issue by waxie** [elastic/curator#1340]
## To submit a bug or report an issue

curator_cli exits with return code 1 if force merge runs with empty index list

curator version: 5.6.0

`2019-01-04 09:32:03,994 CRITICAL  Failed to complete action: forcemerge.  <class 'curator.exceptions.NoIndices'>: index_list object is empty.`

### Expected Behavior

To exit 0

### Actual Behavior

Process exits with return code 1

### Steps to Reproduce the Problem

  1. Run curator_cli with arguments that result in empty index list
 
### Specifications

  - Version: 5.6.0
  - Platform: Ubuntu
  - Subsystem: Docker

## Context (Environment)

This is a problem, because if you run curator in docker in a container orchestration engine, the scheduler will think the job has failed and keep restarting it (based on exit code 1) and never succeed.

## Detailed Description

See also: https://github.com/elastic/curator/issues/1245 which was closed with no resolution

**Comment by untergeek** [comment]
I'm closing this too, because if you follow the instructions in #1245 and run with the `--ignore_empty_list` flag, you will still see an empty list error, but it will exit with a 0, and not a 1. This has been addressed for quite some time.

**Comment by untergeek** [comment]
```
$ curator_cli show_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"netfloo"}'
$ echo $?
1
$ curator_cli show_indices --ignore_empty_list --filter_list '{"filtertype":"pattern","kind":"prefix","value":"netfloo"}'
$ echo $?
0
```
