### ISSUE TITLE
Environment variable substitution expects only one colon in the string 

### ISSUE THREAD

**Issue by osigida** [elastic/curator#1343]
Environment variable substitution expects only one colon per string

In curator config file I can define only one colon if there is a environment variable substitution 
following examples won't work and fail with exception

```
client:
  hosts:
    - ${ELASTIC_SEARCH_HOST:logstash.host.com}:${ELASTIC_SEARCH_PORT:80}
    - ${ELASTIC_SEARCH_HOST:logstash.host.com:80}
    - ${ELASTIC_SEARCH_HOST:logstash.host.com}:80
```
note: curator configuration allows to define host together with a port

Exception:
```
File "/usr/local/lib/python3.7/site-packages/curator/utils.py", line 45, in single_constructor 
envvar, default = proto.split(':')
ValueError: too many values to unpack (expected 2)
```

Curator version: 5.6

**Comment by untergeek** [comment]
What you are trying to do is also not permitted: https://www.elastic.co/guide/en/elasticsearch/client/curator/5.6/envvars.html

You are adding additional values via additional environment variables. This cannot be property interpreted. YAML permits one key and one string value, and the environment variables can provide a default value in case there is no value via that colon. The one value, if an env var, must be inside double quotes. The extra colon will _always_ result in an inability to be properly evaluated.

The only acceptable way around this is to create a third environment variable built from the other two. You are correct in assuming this precludes using a colon delimitation for a port number.

**Comment by osigida** [comment]
I don't try to create additional values, I have one host per line, but I wan't to be able to config HOST and PORT
and I cannot do it in the HOST part of the config
