### ISSUE TITLE
Add ignore `resource_already_exists_exception` option to Create Index Action

### ISSUE THREAD

**Issue by breml** [elastic/curator#1352]
If curator executes a _Create Index_ action for an index, that already exists a `resource_already_exists_exception` exception is returned and curator exit with status code `1`. With the option `continue_if_exception: true` all exceptions can be ignored (and the status code is `0`).

For the _Create Index_ action I would prefere to be able to just ignore the `resource_already_exists_exception` exception as I am describing a state (I would like to have this index) and I am fine with having no error, if this index already exists.

This would be similar to `ignore_empty_list: true` for other actions.

**Comment by iamnotvk** [comment]
can you provide the sample code or mappings to demonstrate the same?

**Comment by breml** [comment]
@iamnotvk No, sorry I can't, I am no longer on the project where I faced this issue.

**Comment by breml** [comment]
@untergeek Thanks for the fix.

**Comment by mih-kopylov** [comment]
@breml could you please advice when can we expect a release with this fix?

**Comment by untergeek** [comment]
@mih-kopylov, @breml won't have any insight on that 😂 as Curator is my baby.

I am trying to squeeze as many fixes into the master branch as possible before releasing 5.8, which could be in a week or so. Feel free to try one of the following if you need something sooner:

1. Clone the repo and build/install the master branch from inside the downloaded `curator` directory, e.g. `pip install -U .` or `python setup.py install.
2. On a VM, or separate machine where you have `root` or your user has `sudo` privileges, clone the repo and run `unix_packages/build_package_from_source.sh`. This will build an RPM or DEB package, depending on what machine you run the script on. The caveat to this is that the package will not be signed by Elastic, so it could gum up the works.
3. Some variant of the above that works for you in a `virtualenv` or the like.

**Comment by mih-kopylov** [comment]
Oh, thanks, @untergeek :) 
I'll just wait for a week then :)

**Comment by mih-kopylov** [comment]
Hi, @untergeek, any luck with a release?

**Comment by untergeek** [comment]
I started the release process last night but hit a major snag with the `requests` module somehow not being detected by the `elasticsearch` module after freezing the build. It works when installed via `pip`, or `python setup.py install`, but does not when `cx_freeze` processes it.

Still trying to work it out. It will delay release some, unfortunately.
