### ISSUE TITLE
No actionable items in list with Forcemerge

### ISSUE THREAD

**Issue by gauchoux** [elastic/curator#1353]
Hi,

So I am trying to forcemerge old indexes, older than 5 days, with a certain pattern but I won't get it to work as I keep getting a message saying `Unable to complete action "forcemerge".  No actionable items in list: <class 'curator.exceptions.NoIndices'>`

I can't find where I could have done a mistake and strangely all the indexes are removed at the `_get_segment_counts` stage but I don't have any filters that require to have the amount of segments.

I am using curator 5.6 and a 5.6.8 AWS Elasticsearch cluster

Here is my config file
[config.txt](https://github.com/elastic/curator/files/2782770/config.txt)

My action file
[ForceMergeOldLogs.txt](https://github.com/elastic/curator/files/2782767/ForceMergeOldLogs.txt)

My Debug Level Log File
[log.txt](https://github.com/elastic/curator/files/2782761/log.txt)

Thanks in advance for your help.

**Comment by gauchoux** [comment]
I forgot to mention that I have an action file that deletes indexes older than 10 days and works without any problem so it shouldn't be a connection issue.

**Comment by gauchoux** [comment]
Strangely enough, today it worked but only for a few indexes.
[log2.txt](https://github.com/elastic/curator/files/2786438/log2.txt)

**Comment by gauchoux** [comment]
So it seems that only logs with more than 10 segments get Forcemerged, is that a normal behavior ?

**Comment by untergeek** [comment]
> So it seems that only indexes with more than 10 segments get Forcemerged, is that a normal behavior ?

Curator checks to see if there are more segments than what you've set to `max_num_segments` and will only proceed if that is the case.

**Comment by gauchoux** [comment]
First, thank you very much for your help !

Okay so I added,
```        
        - filtertype: forcemerged
          max_num_segments: 1
          exclude: True
```
to my Action file but the same outcome still happens.
Every index has more than 1 segment, so shouldn't every index be selected (and forcemerged), or am I missing something ?

**Comment by untergeek** [comment]
That's the `max_num_segments` _per shard,_ rather than per index. How many shards does your index have? If it's the default 5 primary + 1 replica that would be 10 total segments, explaining why you saw the behavior you did.

**Comment by gauchoux** [comment]
Okay I didn't get the part that it was _per shard_.
It all makes sense now.

Thanks again for your help.
