### ISSUE TITLE
Kibana filtertype is not catching some Kibana indices

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/curator#1363]
### Expected Behavior
Kibana filtertype should cover most of the possibilities for kibana indices (`.kibana*`?)

### Actual Behavior
Kibana filtertype only covers `.kibana`, `.kibana-5` and `.kibana-6` - https://github.com/elastic/curator/blob/v5.6.0/curator/indexlist.py#L653-L671 . 

As part of successive upgrades in Kibana needing reindexing the indices, the cluster may end up with an index name for Kibana not included in the previous list and a `.kibana` alias pointing to it.

### Steps to Reproduce the Problem
  1. Install Elasticsearch (trial) and Kibana, 6.4
  2. Upgrade to 6.5 which includes spaces
  3. Kibana index is re-indexed into a new one that is not included in the previous indices names list, and therefore, it will not be caught by the kibana filtertype. 

## Context (Environment)
If we have an action to delete indices older than X days (filtertype `age`, source `creation_date`) in which we are excluding the kibana filtertype, if the index name is not one of the 3 names stated in the code the delete action can remove the Kibana index.

**Comment by untergeek** [comment]
I'm sorry you had a bad experience. The `kibana` filtertype will go away for the next major release due to continued development and underlying changes. You will be required to manually exclude Kibana on your own, using a `pattern` filtertype.

**Comment by kostasb** [comment]
With current versions (as of now v7.2) of the Elastic Stack, Kibana creates a `.kibana` alias associated with a backend index which follows the naming convention `.kibana_1`, `.kibana_2` etc (iterated, dependent on upgrade steps).

As of the current latest version (v5.7), Curator hasn't caught up with this naming convention change, so the kibana filtertype fails to exclude the actual Kibana indices, leaving them in the list of indices for deletion.

**Comment by reidca** [comment]
Instead of removing the kibana filtertype why not just make it work and keep it in sync with changes in Elastic? As a user who has been bitten by these changes and had to waste many hours investigating and restoring indices that were inadvertently curated it's deeply disappointing that Elastic cannot keep both products in sync. It's not a customer focused approach.

**Comment by kostasb** [comment]
Until an update that fixes the issue (or removes kibana filtertype) is released, it would be good to add a note in the documentation that the Kibana filtertype does not exclude modern kibana index names of the `.kibana_*` pattern.

**Comment by untergeek** [comment]
I have a PR building now. I'm going with a regex to match anything `^\.kibana.*$`.
