### ISSUE TITLE
Unable to delete snapshots

### ISSUE THREAD

**Issue by Tonysykes** [elastic/curator#1366]
We have created a curator job that runs on AWS lambda, once triggered it creates snapshot of the kibana index (using the .kibana alias) and then deletes snapshots older the the most recent 8.

### Actual Behavior
When lambda executes the delete snapshot action we get the following error in the cloudwatch logs;
Failed to complete action: delete_snapshots. <class 'TypeError'>: '<' not supported between instances of 'NoneType' and 'int'

I have this working locally (not AWS)  without an issue on ES 6.6.1, curator 5.6, python 3.6. I cannot upgrade the Production system to ES 6.6.1 until our next next update schedule (A few months away). I don't see how the ES version would cause this error though.

### Specifications
  - Version: 5.6
  - Platform: AWS Lambda
  - ES 6.5.4

**Comment by nerophon** [comment]
This has been tested on ES 6.5.4 in a local environment and it works as expected. Therefore we may have confidence that the version isn't the problem here.

**Comment by nerophon** [comment]
Here is an action-file that can be used to reproduce the problem. Had to change the extension from .yml to .txt to post it here.
[hb-curator-monitoring.txt](https://github.com/elastic/curator/files/2993383/hb-curator-monitoring.txt)

**Comment by nerophon** [comment]
The delete action from the above file causes a failure for any snapshot that doesn't match the date-pattern expressed by `timestring: '%Y%m%d%H%M%S'` (assuming a match of the prefix pattern). In our case the `kibana-index` snapshot name caused this failure and error.
We would have expected no error or failure, but rather a deliberate ignore of the snapshot.
