### ISSUE TITLE
Snapshot stuck in INIT - elasticsearch 2.4.6

### ISSUE THREAD

**Issue by timm088** [elastic/curator#1406]
I've done a fair bit of searching and I can't come up with a fix here

A curator snapshot in our cluster has become stuck (around 7TB of data).

About the 

- ES 2.4.6
- Running on AWS with the cloud plugin

Here's what I have tried so far

- delete API (obviously doesnt work, job is in progress still)
- rolling restart of all nodes, no change
- replaced all nodes with new nodes (data and master), no change
- checked for failed shards on the data nodes, there are none

I am now at a loss, and I am unable to snapshot the indices... Any help?

**Comment by untergeek** [comment]
What version of Curator are you using with Elasticsearch 2.4.6? 

Regardless, Curator only makes API calls. If there is a stall, it’s inside Elasticsearch. You might have to clear out a stalled snapshot using other API calls.

**Comment by timm088** [comment]
Thanks for replying. I'll reply in the forum thread instead https://discuss.elastic.co/t/curator-snapshot-stuck-in-init/182796/2
