### ISSUE TITLE
Please pin pyyaml  to 3.13 until the pyyaml 5.1 fixes are done for python 3.7 support

### ISSUE THREAD

**Issue by bryder** [elastic/curator#1407]
pyyaml-3.12 will not build the c extensions when using python 3.7 so I can not build curator using python 3.7.

pyyaml-3.13 added support for python-3.7 but curator is pinned to 3.12 at the moment.

[reference to changes in pyyaml](https://pyyaml.org/wiki/PyYAML)

This relates to #1368 

### Expected Behavior

pyyaml-3.13 should be the requirement so curator can be used  with python 3.7

### Actual Behavior

I can not build curator using python 3.7 if the requirements are respected 

### Steps to Reproduce the Problem

I use an internal build system behind a firewall so can't easily show the steps here.

I suspect installing python 3.7 and building with pip will show the error when trying to build pyyaml-3.12 which emit the same errors I've been getting but unfortunately I can't do that from where I am.

### Specifications

  - Version: curator 5.7.6
  - Platform: ubuntu 16.04/18.04, Python 3.7.3

**Comment by untergeek** [comment]
This is done. Curator 5.8 is currently pinned ti pyyaml=3.13
