### ISSUE TITLE
Close action fails when index has unassigned shards

### ISSUE THREAD

**Issue by psypuff** [elastic/curator#1412]
### Expected Behavior
Close action should be able to close indices with unassigned shards.

### Actual Behavior
Close action fails closing indices with unassigned shards.

### Steps to Reproduce the Problem
  1. Spin up a cluster with at least 2 data nodes
  1. Create an index
  1. Terminate a data node containing at least one of its shards (make the index go red)
  1. Invoke Curator's close action on the index

### Specifications

  - Version: 5.4.1 (By looking at the code it seem to also affect the latest, 5.7.6 as of today, but haven't tested yet)
  - Platform: Docker on Ubuntu 18.04
  - Subsystem: Python 2.7

## Context (Environment)
We use Curator for periodically restoring prod data on another cluster, the flow consists of 3 actions - close -> restore -> open (in case the restore fails and the index is left closed). Normally it works well, once every now and then a node gets terminated and we're left with unassigned shards (not an issue, intentionally not using replicas here), as we're constantly restoring the data we expect the restore flow to work in this case as well but we find ourselves manually closing indices each time it happens.

## Detailed Description
The `_close` API has no issues with unassigned shards, the actual part that fails is the `_flush` [API call right before that](https://github.com/elastic/curator/blob/master/curator/actions.py#L307). Obviously, in most cases, one would want to flush before closing an index, but the current implementation renders Curator's ability to restore pretty useless where it's most needed (e.g. data loss).
2 suggestions on how to overcome this issue:
1. Make the `_flush` API call optional via a `--skip-flush` flag.
2. Check for unassigned shards for each index and avoid flushing those.

Anyway - the `_flush` API is not an integral part of the `_close` API so it's kinda weird to enforce it in Curator's close action IMO

**Comment by untergeek** [comment]
> Anyway - the `_flush` API is not an integral part of the `_close` API so it's kinda weird to enforce it in Curator's close action IMO

I chose to do this due to the "principle of least surprise." Back before the creation of the synced flush, an index which was closed would almost _always_ end up rebuilding its replicas when re-opened. So, in order to save most users the hassle, `close` does a synced flush before closing.

> but the current implementation renders Curator's ability to restore pretty useless where it's most needed (e.g. data loss).

While I feel your frustration here, yours is an edge case—not the restore part, but that you have nodes terminating randomly. In what cluster would that normally be acceptable? 

I can see where skipping the flush is a benefit, so I'll add it.  I can't promise I'll get there quickly, though.

**Comment by psypuff** [comment]
> I chose to do this due to the "principle of least surprise." Back before the creation of the synced flush, an index which was closed would almost always end up rebuilding its replicas when re-opened. So, in order to save most users the hassle, close does a synced flush before closing.

Gotcha, sounds the right thing to do in most cases, worth adding a word about it in the docs though.

> but that you have nodes terminating randomly. In what cluster would that normally be acceptable?

The perks of running on a public cloud 😄. Normally we'd have replicas to overcome a node failure but this specific cluster is non-production and it's not worth the cost, if the restore flow will also work after a node failure it should be enough.

Thanks @untergeek , I'll try to invest some time and create a basic PR by myself.
