### ISSUE TITLE
Sync with inBackground doesnt complete if curator client is closed

### ISSUE THREAD

**Issue by shiveshr** [elastic/curator#1419]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

Calling sync with a callback on a closed client doesnt fail synchronously. Nor is the callback invoked with failure details. 

```
client.close();
client.sync().inBackground(callback, executor).forPath(path);
```
### Expected Behavior
Callback should be called with IllegalStateException or any other appropriate failure. But the callback should be invoked just like it is for all other types of calls. 

### Actual Behavior
The callback is never called. Neither is the call to invoke sync failed synchronously. 

### Steps to Reproduce the Problem

```
client.close();
client.sync().inBackground(callback, executor).forPath(path);
```

### Specifications

  - Version: 4.0.1
  - Platform: linux
  - Subsystem: ubuntu

## Context (Environment)
My application make asynchronous calls to zookeeper using curator and registers a callback. 
During shutdown curator client could be shutdown while other modules still use the client. 
Their calls into curator should fail if it is shutdown. All other calls fail except `sync`.

**Comment by untergeek** [comment]
Are you sure you have the correct product here? This is Elasticsearch Curator, which is currently on version 5.7.6, (you listed 4.0.1), and is a Python-based tool for managing Elasticsearch indices.  The "client" object in Curator is from the [Elasticsearch Python](https://github.com/elastic/elasticsearch-py) project. I don't think it even supports the kind of calls you're describing.

Zookeeper Curator is a different product altogether from Elasticsearch Curator.
