### ISSUE TITLE
Curator_cli: filter suffix pattern behaves like a regex pattern for matching indicies

### ISSUE THREAD

**Issue by Daniel314** [elastic/curator#1439]
Hello,

When the following command was executed, the filter pattern matched every single index (and consequently deleted every index). Is this expected behavior? From the documentation, it appears that a suffix match should be a substring match, NOT a regex match.

> $ curator_cli delete_indices --ignore_empty_list --filter_list '{"filtertype":"pattern","kind":"suffix","value":"/?"}'

The suffix pattern above ("/?") should not have matched any indicies. 
All of my indicies had a name of logstash-%Y.%m.%d, .kibana_1, .kibana_task_manager, or .reporting-%Y.%m.%d

Here's the output for a dry run:

> $ curator_cli --dry-run delete_indices --ignore_empty_list --filter_list '{"filtertype":"pattern","kind":"suffix","value":"/?"}'
> 2019-08-01 13:05:47,922 INFO      DRY-RUN MODE.  No changes will be made.
> 2019-08-01 13:05:47,922 INFO      (CLOSED) indices may be shown that may not be acted on by action "delete_indices".
> 2019-08-01 13:05:47,922 INFO      DRY-RUN: delete_indices: .kibana_1 with arguments: {}
> 2019-08-01 13:05:47,922 INFO      DRY-RUN: delete_indices: .kibana_task_manager with arguments: {}
> 2019-08-01 13:05:47,922 INFO      DRY-RUN: delete_indices: logstash-2019.07.29 with arguments: {}
> 2019-08-01 13:05:47,922 INFO      DRY-RUN: delete_indices: logstash-2019.07.30 with arguments: {}
> 2019-08-01 13:05:47,922 INFO      DRY-RUN: delete_indices: logstash-2019.07.31 with arguments: {}
> 2019-08-01 13:05:47,923 INFO      DRY-RUN: delete_indices: logstash-2019.08.01 with arguments: {}
> 2019-08-01 13:05:47,923 INFO      DRY-RUN: delete_indices: logstash-2019.08.02 with arguments: {}
> 2019-08-01 13:05:47,923 INFO      "delete_indices" action completed.

This is on Ubuntu Linux (14.04.6 LTS), installed from the http://packages.elastic.co/curator/5/debian APT repository.
I was initially using version 5.7.5 of the elasticsearch-curator APT package.  Upgrading to version 5.7.6 did not change the behavior.

If this is expected behavior, could the documentation please be updated to clarify that suffix patterns are also regex patterns?
If this is not the expected behavior, could this please be fixed (so that suffix patterns are substring matches and not regex matches)?

Thank you,

    - Daniel

**Comment by untergeek** [comment]
This is expected behavior. Both `prefix` and `suffix` are regexes:

`prefix`: `^{PREFIXVAL}.*$`
`suffix`: `^.*{SUFFIXVAL}$`

If you would like this to be different, please feel free to submit a pull request to change the behavior. It can be reviewed and discussed there, and potentially merged.

**Comment by untergeek** [comment]
Comments are in #1443. Will not be changing to use substring matching as that will be a breaking change for users, even if it is simpler code-wise.
