### ISSUE TITLE
Feature Request: Drop setup_requires in setup.cfg

### ISSUE THREAD

**Issue by redbaron4** [elastic/curator#1444]
We run curator in an Internet disconnected setup where Pip is used to fetch packages from an internal PyPI mirror. For some reason, I am unable to install newer curator packages (5.7.x) in that environment. On my Internet connected machine, I can easily install latest version.

On further inverstigation, I found that removing the `setup_requires` section in `setup.cfg` makes the package install smooth even on the disconnected server. In the [setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html), I see

> setuptools will attempt to obtain these (even going so far as to download them using EasyInstall) before processing the rest of the setup script or commands

so it appears that since I have only configured pip to work with internal pypi mirror, easy_install fails.

Is it possible to drop this section from `setup.cfg` considering this is not even used in `setup.py`?

**Comment by untergeek** [comment]
I tried getting rid of this once, and it failed older tests (Python 2.7) and the like on my CI setup.

When Python 2.7 is completely deprecated later this year I will likely try again. It is certainly on my "want to do this" list.

**Comment by redbaron4** [comment]
@untergeek Thanks. FWIW, all our infra is on Python2.7. Eventually, I worked around the issue by configuring pypi mirror for `easy_install` using the `~/.pydisutils.cfg` file.

**Comment by untergeek** [comment]
Python 2.7 is no longer supported by Curator. Curator depends on 3.8 to 3.11 at this time.
