### ISSUE TITLE
aws4auth not being recognized

### ISSUE THREAD

**Issue by DDSloan96** [elastic/curator#1455]
I'm using the untergeek/curator image and when I try to use the aws auth I get 
`2019-08-20 15:50:28,458 DEBUG              curator.utils             get_client:813  Attempting to verify SSL certificate.
2019-08-20 15:50:28,460 DEBUG              curator.utils             get_client:884  Not using "requests_aws4auth" python module to connect.
2019-08-20 15:50:28,461 DEBUG     urllib3.connectionpool              _new_conn:813  Starting new HTTPS connection (1) `

Followed by a 403.  Any idea why this is

**Comment by untergeek** [comment]
How do you know it's using AWS authentication? 

Also, how was Curator installed?

**Comment by DDSloan96** [comment]
This is using your curator docker image.  I know because I set up the configs and it works outside the docker image

**Comment by untergeek** [comment]
It would be very helpful to see debug output from everything in `curator.utils get_client`, rather than just this line.

**Comment by untergeek** [comment]
AWS is no longer supported.
