### ISSUE TITLE
Compatibility matrix is slightly confusing

### ISSUE THREAD

**Issue by nerophon** [elastic/curator#1478]
The compatibility matrix here: https://www.elastic.co/guide/en/elasticsearch/client/curator/5.x/version-compatibility.html

Shows that Curator 5 is compatible with ES 7. However, a customer running Curator 5.6 found that it was not compatible with ES 7.2.

Obviously this is because ES 7.2 (or indeed any 7.x) didn't exist when Curator 5.6 was released. However, the Matrix seems to suggest that ANY Curator 5 will work with ES 7.x. Now, if I change the docs version to Curator 5.6, then the ES 7.x column disappears, so it's correct. But a Google search tends to take you to the latest doc, so I can understand how the customer made the mistake.

I propose, therefore, a slight change to the rows of the table, to create a delineation between 5.6- and 5.7+. Or something similar.

**Comment by untergeek** [comment]
Can probably put in a `X.Y+` or something in that column, rather than a check mark. Or an asterisk or something which has a footnote to indicate at which version this support was added.
