### ISSUE TITLE
Add Freeze action to docs

### ISSUE THREAD

**Issue by sastorsl** [elastic/curator#1479]
## Add Freeze action to the documentation for Curator.
Freeze action has been added to Curator in PR #1454 / issue #1399 
It is however not documented as pr https://www.elastic.co/guide/en/elasticsearch/client/curator/current/actions.html

### Expected Behavior
The new action to freeze should be documented.

### Actual Behavior
Docs are missing.

### Steps to Reproduce the Problem
N/A

### Specifications
  - Version: 5.8.1

## Context (Environment)
N/A

## Detailed Description
N/A

**Comment by trondhindenes** [comment]
wow I had no idea. This definitely needs to go in the docs.
