### ISSUE TITLE
[RFC] Add `retry_count` and `retry_interval` options to `delete_indices` action

### ISSUE THREAD

**Issue by chris-griffin** [elastic/curator#1507]
### Expected Behavior
The [`delete_indices` action](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/delete_indices.html) should have the [`retry_interval`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_retry_interval.html) and [`retry_count`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_retry_count.html) options to handle `TransportError`s

### Actual Behavior

The [`delete_indices` action](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/delete_indices.html) does not have any type of retry option.

### Steps to Reproduce the Problem

  1. Startup a snapshot
  1. Run the `delete_indices` action
  1. Encounter the `snapshot_in_progress_exception` `TransportError`

### Specifications

  - Version: All
  - Platform: All
  - Subsystem: All

## Context (Environment)

We take a snapshot of our cluster fairly frequently so we often run into the following error when running the delete indices action:

_TransportError(400, u'snapshot_in_progress_exception', u'Cannot delete indices that are being snapshotted: [[omitted]]. Try again after snapshot finishes or cancel the currently running snapshot.')_

## Detailed Description

While the `delete_indices` action does have the [`continue_if_exception`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_continue.html) option, this simply continues execution of other actions. But similar to the [`delete_snapshots` action](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/delete_snapshots.html), we would really like to retry this action especially since it is inherently idempotent.

@untergeek would you accept a PR that implemented these existing options on the `delete_indices` action?

**Comment by Smriti-OSS** [comment]
Hi @chris-griffin @untergeek Were you able to achieve this? I am also facing the same problem, and any help is appreciated!!

**Comment by chris-griffin** [comment]
Closing since we never got an answer from a project maintainer and didn't get much community support
