### ISSUE TITLE
Displaying none proper error when mapping is incorrect

### ISSUE THREAD

**Issue by namreg** [elastic/curator#1525]
## To submit a bug or report an issue

Displaying incorrect error when mapping is incorrect. Similar issue https://github.com/elastic/curator/issues/1524.
### Expected Behavior

Expected to see error 
```
Failed to complete action: create_index.  <class 'elasticsearch.exceptions.RequestError'>: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [type : {properties={name={type=keyword}}}]')
```
### Actual Behavior

See the error 
```
Failed to complete action: create_index.  <class 'curator.exceptions.FailedExecution'>: Index testing already exists.
```
### Steps to Reproduce the Problem

When I trying to make request via curl 
```
curl -X PUT "localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
  {
    "mappings" : {
      "type": {
        "properties": {
          "name": { "type": "keyword" }
        }
      }
    }
  }
  '
```
I see the the following response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [type : {properties={xyz={type=keyword}}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [type : {properties={xyz={type=keyword}}}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [type : {properties={xyz={type=keyword}}}]"
    }
  },
  "status": 400
}
```
But when I try to run action file with the same mapping I see the error `Index test already exists`.
It seems confused for users.
### Specifications

  - Version: `5.8.2`

**Comment by alexhornbake** [comment]
Just hit this as well. Seems this was introduced with `ignore_existing` flag.
https://github.com/elastic/curator/commit/1f3607c8575c349274caffa21a482ee8a28549a6#diff-01706e4abbbd393c879806998079c494R471

**Comment by kiddom-kq** [comment]
I just hit this as well :(.

Based on this ticket: https://github.com/elastic/curator/issues/1524

I am assuming that the mappings that I am trying to create are incorrect, but it's not 100% clear to me how as I can trigger the behavior using the  _exact_ example for [`create_index`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_extra_settings.html#_create_index):

```yaml
actions:
  0:
    action: create_index
    description: "Create index as named"
    options:
      name: myindex
      extra_settings:
        settings:
          number_of_shards: 1
          number_of_replicas: 0
        mappings:
          type1:
            properties:
              field1:
                type: string
                index: not_analyzed
```

produces this output:

```
{"@timestamp": "2021-02-19T21:53:52.976Z", "function": "parse_date_pattern", "linenum": 1478, "loglevel": "DEBUG", "message": "Fully rendered name: myindex", "name": "curator.utils"}
{"@timestamp": "2021-02-19T21:53:52.976Z", "function": "process_action", "linenum": 103, "loglevel": "DEBUG", "message": "Doing the action here.", "name": "curator.cli"}
{"@timestamp": "2021-02-19T21:53:52.976Z", "function": "do_action", "linenum": 573, "loglevel": "INFO", "message": "Creating index \"myindex\" with settings: {'settings': {'number_of_shards': 1, 'number_of_replicas': 0}, 'mappings': {'type1': {'properties': {'field1': {'type': 'string', 'index': 'not_analyzed'}}}}}", "name": "curator.actions.create_index"}
{"@timestamp": "2021-02-19T21:53:53.077Z", "function": "run", "linenum": 213, "loglevel": "ERROR", "message": "Failed to complete action: create_index.  <class 'curator.exceptions.FailedExecution'>: Index myindex already exists.", "name": "curator.cli"}
```

I can promise you that there is no index called `myindex` in the cluster. As soon as i remove the `mappings:` block, the index is created immediately.  I have tried various permutations of the `mappings:` block, but still the same results:


```yaml
# No good
        mappings:
            properties:
              field1:
                type: string
# Also no good
        mappings:
              field1:
                type: string
```

I am targeting an AWS managed ES cluster:

```shell
GET /

{
  "name" : "01ad714<...>9",
  "cluster_name" : "286112170654:app-development",
  "cluster_uuid" : "JDq<...>DIw",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2020-06-22T06:09:23.151801Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```

Using curator 5.8.3

```shell
❯ curator --version
curator, version 5.8.3
```




-----


In the process of drafting this post, I had one of those "wait a sec..." moments. I explicitly set `blacklist: []` in the logging config in order to get the _actual_ error from ES:

```
2021-02-19 14:18:03,472 DEBUG              elasticsearch       log_request_fail:161  > {"settings":{"number_of_shards":1,"number_of_replicas":0},"mappings":{"properties":{"field1":{"type":"string"}}}}
2021-02-19 14:18:03,472 DEBUG              elasticsearch       log_request_fail:166  < {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [field1]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: No handler for type [string] declared on field [field1]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [field1]"}},"status":400}
2021-02-19 14:18:03,473 ERROR                curator.cli                    run:213  Failed to complete action: create_index.  <class 'curator.exceptions.FailedExecution'>: Index myindex already exists.
```


Somewhere around ES 6, `string` became `text`. As soon as I saw the "no handler for type..." I knew what the problem was. 

*doh*. 

Change the index type to the new/mo-bettah `text` cleared that right up!


SO, for anybody else that finds this thread in the future.... the ` Index myindex already exists.` error might be a red-herring. Check your mappings... _carefully_.

**Comment by untergeek** [comment]
Stale, and appears to be Elasticsearch 6.0 to 7.0 specific

**Comment by alexhornbake** [comment]
8.x has the same error handling logic that assumes all create index requests fail for the same reason.

https://github.com/elastic/curator/blob/8.x/curator/actions/create_index.py#L77

if it would be helpful, I can open a PR to fix, similar to https://github.com/elastic/curator/pull/1537

**Comment by untergeek** [comment]
Thank you @alexhornbake! That would be appreciated.

**Comment by untergeek** [comment]
This is addressed now, albeit manual adaptation of code from PRs that are out of date. Watch for acknowledgement in the ChangeLog.
