### ISSUE TITLE
Failed installation on centos8 container

### ISSUE THREAD

**Issue by crossbill** [elastic/curator#1532]
Have tried all methods 
 
 pip3 install elasticsearch-curator
 python setup.py install 
 pip install elasticsearch-curator-5.8.1.tar.gz

All throwing the same error below

ERROR:

Building wheels for collected packages: elasticsearch-curator
  Building wheel for elasticsearch-curator (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /var/lib/awx/venv/ansible/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lce0m02w --python-tag cp36
       cwd: /tmp/pip-req-build-mofl7a4_/
  Complete output (74 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/curator
  copying curator/actions.py -> build/lib/curator
  copying curator/cli.py -> build/lib/curator
  copying curator/singletons.py -> build/lib/curator
  copying curator/logtools.py -> build/lib/curator
  copying curator/config_utils.py -> build/lib/curator
  copying curator/indexlist.py -> build/lib/curator
  copying curator/snapshotlist.py -> build/lib/curator
  copying curator/__main__.py -> build/lib/curator
  copying curator/repomgrcli.py -> build/lib/curator
  copying curator/exceptions.py -> build/lib/curator
  copying curator/_version.py -> build/lib/curator
  copying curator/utils.py -> build/lib/curator
  copying curator/__init__.py -> build/lib/curator
  copying curator/curator_cli.py -> build/lib/curator
  running egg_info
  writing elasticsearch_curator.egg-info/PKG-INFO
  writing dependency_links to elasticsearch_curator.egg-info/dependency_links.txt
  writing entry points to elasticsearch_curator.egg-info/entry_points.txt
  writing requirements to elasticsearch_curator.egg-info/requires.txt
  writing top-level names to elasticsearch_curator.egg-info/top_level.txt
  reading manifest file 'elasticsearch_curator.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'Changelog.rst'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  warning: no previously-included files matching '*.pyc' found under directory 'curator'
  warning: no previously-included files matching '*.pyo' found under directory 'curator'
  warning: no previously-included files matching '*.pyc' found under directory 'docs'
  warning: no previously-included files matching '*.pyo' found under directory 'docs'
  warning: no previously-included files matching '*.pyc' found under directory 'test'
  warning: no previously-included files matching '*.pyo' found under directory 'test'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'docs/asciidoc/html_docs'
  writing manifest file 'elasticsearch_curator.egg-info/SOURCES.txt'
  creating build/lib/curator/cli_singletons
  copying curator/cli_singletons/__init__.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/alias.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/allocation.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/close.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/delete.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/forcemerge.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/freeze.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/object_class.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/open_indices.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/replicas.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/restore.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/rollover.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/show.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/shrink.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/snapshot.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/unfreeze.py -> build/lib/curator/cli_singletons
  copying curator/cli_singletons/utils.py -> build/lib/curator/cli_singletons
  creating build/lib/curator/defaults
  copying curator/defaults/__init__.py -> build/lib/curator/defaults
  copying curator/defaults/client_defaults.py -> build/lib/curator/defaults
  copying curator/defaults/filter_elements.py -> build/lib/curator/defaults
  copying curator/defaults/filtertypes.py -> build/lib/curator/defaults
  copying curator/defaults/option_defaults.py -> build/lib/curator/defaults
  copying curator/defaults/settings.py -> build/lib/curator/defaults
  creating build/lib/curator/validators
  copying curator/validators/__init__.py -> build/lib/curator/validators
  copying curator/validators/actions.py -> build/lib/curator/validators
  copying curator/validators/config_file.py -> build/lib/curator/validators
  copying curator/validators/filters.py -> build/lib/curator/validators
  copying curator/validators/options.py -> build/lib/curator/validators
  copying curator/validators/schemacheck.py -> build/lib/curator/validators
  running build_exe
  error: [Errno 2] No such file or directory: 'run_curator.py'
  ----------------------------------------
  ERROR: Failed building wheel for elasticsearch-curator
  Running setup.py clean for elasticsearch-curator
Failed to build elasticsearch-curator
Installing collected packages: elasticsearch-curator
    Running setup.py install for elasticsearch-curator ... error
    ERROR: Command errored out with exit status 1:
     command: /var/lib/awx/venv/ansible/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_md0j6qh/install-record.txt --single-version-externally-managed --compile --install-headers /var/lib/awx/venv/ansible/include/site/python3.6/elasticsearch-curator
         cwd: /tmp/pip-req-build-mofl7a4_/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/lib/awx/venv/ansible/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mofl7a4_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_md0j6qh/install-record.txt --single-version-externally-managed --compile --install-headers /var/lib/awx/venv/ansible/include/site/python3.6/elasticsearch-curator Check the logs for full command output.

**Comment by untergeek** [comment]
Try to build from the `master` branch, please. There are a number of fixes that might make it work.

**Comment by crossbill** [comment]
Thanks build from master branch worked.
