### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER at normal execution

### ISSUE THREAD

**Issue by DrissiReda** [elastic/curator#1534]
Launching a simple snapshot action causes this error. I'm running elasticsearch and minio locally, I managed to create snapshots manually but wanted to use curator for automating snapshots. 

```bash
HTTP N/A error: HTTPSConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))
```

These are my files 

<details>
<summary>curator.yml</summary>

```yaml
client:
    hosts:
        - 127.0.0.1
    port: 9200
    aws_key: minioadmin
    aws_secret_key: minioadmin 
    aws_region: default
    use_ssl: False
logging:
    loglevel: INFO
```
</details>

<details>
<summary>actions.yml</summary>

```actions.yml
actions:
  1:
    action: snapshot
    options:
      repository: backup_minio
      name: backup-%Y-%m-%-d-%H:%M:%S
      ignore_unavailable: False         
      include_global_state: True
      partial: False    
      wait_for_completion: True
      skip_repo_fs_check: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash
```
</details>

This is what happens: 
```bash
$ curator --dry-run actions.yml                                                                                                        
2020-04-06 15:34:12,054 INFO      Preparing Action ID: 1, "snapshot"
2020-04-06 15:34:12,054 INFO      Creating client object and testing connection
2020-04-06 15:34:12,056 INFO      Instantiating client object
2020-04-06 15:34:12,056 INFO      Testing client connectivity
2020-04-06 15:34:12,083 ERROR     HTTP N/A error: HTTPSConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)')))
2020-04-06 15:34:12,083 CRITICAL  Curator cannot proceed. Exiting.

```

Environment:

OS: ubuntu 19.10

elasticsearch: 7.6.2
minio: RELEASE.2020-03-25T07-03-04Z
curator: 5.8.1

**Comment by sethmlarson** [comment]
This error probably means that HTTPS was being used on the client side and the server was speaking HTTP. I see the `use_ssl=False`, that's just my addition to this issue. TLS error messages are mysterious things. :)

**Comment by DrissiReda** [comment]
Yes I also thought that's the problem, but since I disabled SSL I don't know what else to do, hence the ticket :)

**Comment by DaveyDevOps** [comment]
I believe if server is using https but you want to bypass validation 

```
use_ssl: True
ssl_no_validate: True
```

**Comment by untergeek** [comment]
It does sound like a two-way protocol mismatch. 

To see more, I recommend turning off log blacklisting to get the full debug:

```
logging:
  # ... other settings
  blacklist: [] # set to empty array
```
By default both the `elasticsearch` and `urllib3` python modules' logging are hidden (they are quite chatty at INFO level). Setting `blacklist` to an empty array will show you all of the cross-talk and SSL responses and all that.

**Comment by untergeek** [comment]
Stale. No updates. Re-open if still experiencing.
