### ISSUE TITLE
Is curator compatibile with python 3.x?

### ISSUE THREAD

**Issue by aggarwalShivani** [elastic/curator#1540]
Is python a run-time dependency of curator? Is there a fixed compatibility check between python & curator? Does curator work with python 3.x?

## Context
I use curator rpms (elasticsearch-curator-5.6.0-1.x86_64.rpm & elasticsearch-curator-5.8.1-1.x86_64.rpm) on centos 7 , with python 2.7 and now want to upgrade to python3.

Do both these curator rpm versions also work with python 3.x? And is there a specific version of python 3.x to use?

### Specifications
  - Version:   elasticsearch-curator-5.6.0 & elasticsearch-curator-5.8.1
  - Platform: Centos 7.7

**Comment by DaveyDevOps** [comment]
This question might be better suited for [discuss.elastic.co](https://discuss.elastic.co/). 

I would not expect rpm's to be cross compatible between python versions.

Installing with pip seems like it could address your compatibility concerns. 
Curator is available under pip3. 
```
pip3 search elasticsearch-curator
elasticsearch-curator (5.8.1)           - Tending your Elasticsearch indices
```

**Comment by untergeek** [comment]
This is a trick question. The answer is, of course, **it depends.**

Yes, curator depends on a python binary. However, the RPM and DEB packages are _frozen_ in Python terms. What it means is that the come bundled with their own small subset of the necessary Python libraries and a frozen binary that works with them. In other words, the RPM and DEB packages provided in the official repository do not have a Python dependency and will run regardless of what system they are on.
