### ISSUE TITLE
curator error run as cronjob.

### ISSUE THREAD

**Issue by rizvaughan** [elastic/curator#1546]
Hi,
I have two nodes where I cleanup old elasticsearch indices using curator. I have a cronjob which runs at midnight and cleanup old indices. While there aren't any problems with one node, the second node gives me the following errors.
`/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 1: ---: command not found
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 2: actions:: command not found
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 3: 1:: command not found
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 4: action:: command not found
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 5: description:: command not found
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 6: syntax error near unexpected token `('
/usr/src/script/curator/es_kibana-prod-indices_cleanup.yml: line 6: `      Delete indices older than 31 days (based on index name), for logstash-'`
Here is my es_kibana-prod-indices_cleanup.yml file:
`---

actions:

  1:
    action: delete_indices  

    description: >-  
      Delete indices older than 31 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.  

    options:  

      ignore_empty_list: True  

      timeout_override:  

      continue_if_exception: False  

      disable_action: False  

    filters:  

    - filtertype: age  

      source: name  

      direction: older  

      timestring: '%Y.%m.%d'  

      unit: days  

      unit_count: 31  

      exclude:`  

and my config file is:

`---

client:

  hosts:

    - https://vpc-xxxxxxxxx.es.amazonaws.com

  port: 9200

  url_prefix:

  use_ssl: False

  certificate:

  client_cert:

  client_key:

  ssl_no_validate: False

  http_auth:

  timeout: 30

  master_only: False

logging:

  loglevel: INFO

  logfile:

  logformat: default

  blacklist: ['elasticsearch', 'urllib3']`

The settings is exactly the same for my other node where curator does what it's supposed to do. The strange thing is, if I run it manually, it gets executed without any issues but in crontab it doesn't. The file permissions etc are all similar in both cases.
Could somebody tell me what's going on, what am I doing wrong?

**Comment by untergeek** [comment]
You're sharing the Curator yaml files, but the problem (according to the error you're sharing) appears to come from the script your crontab is calling. Perhaps if you shared that?

**Comment by rizvaughan** [comment]
Hi @untergeek ,
What a stupid mistake by me. Indeed the problem was crontab not curator. I was not even calling curator in crontab. The call was without "curator", that's why the message "command not found" :/
Thank you very much.
