### ISSUE TITLE
httpauth from another file

### ISSUE THREAD

**Issue by kfox1111** [elastic/curator#1548]
I'm trying to use the helm chart for curator against a cluster launched via the elastic operator. They place passwords in a secret by default and don't have certs.

The httpauth field is only specifyable via a configmap in the chart. Which is the wrong place to put a password.

It would be nice if there was a way to specify that the httpauth password was in a separate file.

**Comment by untergeek** [comment]
This is addressed by using the most recent release of Curator (8.0.3 right now) and providing the passwords on the command-line using ENV variables. If there are further concerns, please open a new issue.
