### ISSUE TITLE
When using a snapshot by curator, is it possible to start with an older index？

### ISSUE THREAD

**Issue by xidiandb** [elastic/curator#1552]
## To submit a bug or report an issue
When a snapshot is taken, is the index sorted by time

### Expected Behavior
Older indexes should be backed up first

### Actual Behavior
Snapshots are completely out of order

### Specifications

  - Version: 5.6
  - Platform: docker
  - Subsystem: 

## Context (Environment)

        action: snapshot
        description: "Snapshot selected indices to s3_repository"
        options:
          repository: s3_repository
          name: '<{now/d}>'
          wait_for_completion: True
          max_wait: 1200
          wait_interval: 10
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^test.*$'
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m'
          unit: months
          unit_count: 0

**Comment by untergeek** [comment]
This is immaterial to Snapshotting in general. In the versions of Elasticsearch described here, all of the segments in all indices to be snapshotted are marked by Elasticsearch and prevented from changing while the snapshot takes place. There is no reason for concern about which of the selected indices are being copied first. Elasticsearch's snapshot technology is not analogous to tape backups or the like.
