### ISSUE TITLE
LD_LIBRARY_PATH is not the answer.

### ISSUE THREAD

**Issue by TJM** [elastic/curator#1553]
We recently upgraded to curator 5.8.1 from 5.6.0, and found that `/opt/elasticsearch-curator/curator` no longer works. After some digging, we found that `/usr/bin/curator` had changed from a symlink to a "script" that sets LD_LIBRARY_PATH. This is a *hack* for relocating C Libraries. It should not be needed when software is installed in the "default" location.

### Expected Behavior
The code should be re-compiled with appropriate "cflags" (-R?) for the libraries in the location they are expected to be in at runtime so that no hacks are needed and the binary can be called directly without a wrapper script.

### Actual Behavior
```
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/opt/python/3.7.4/lib/python3.7/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
Aborted
```

### Steps to Reproduce the Problem

  1. /opt/elasticsearch-curator/curator --help

We actually had a cron job that ran our backups that produced the same error output, but that is the most simple steps.

### Specifications

  - Version: `elasticsearch-curator-5.8.1-1.x86_64`
  - Platform: CentOS 7.8.2003
  - Subsystem: rpm?

## Context (Environment)

* Several (10+) elasticsearch clusters ranging from 5.6.x -> 7.8.x, all running on CentOS 7.8+patches

We were previously using "pip" installed versions of curator, but they kept breaking during system updates, so we switched to the RPM packages. As a result of switching, the "/usr/bin/curator" link was not reliably created (or it was being removed by pip in some cases), so we pointed our cron jobs directly at the installed binary instead of the "convenience" link.

## Detailed Description

Re-compile and re-package the code with appropriate CFLAGS as mentioned above.

**Comment by untergeek** [comment]
To my knowledge, there is no way to "compile" Python, but you can "Freeze" Python code. This project uses cxFreeze to render an executable binary. If there is some way to turn Python code into a compiled binary with properly set CFLAGS, I'm very keen to know. However, libraries can be copied and included with frozen Python code. This is how the necessary libraries get copied to `/opt/elasticsearch-curator`. This has the added advantage of making the "frozen" package highly portable.

However, this requires that Curator point exclusively to the libraries included in the frozen package. This is why the `LD_LIBRARY_PATH` approach is taken, and execution should be via the `/usr/bin/curator` script to ensure that only those libraries are used. Hack? Perhaps. I'm making use of the tools available in a way that does not interfere with any other code on the target machine. This seems like a good compromise to me.

**Comment by TJM** [comment]
Hmmm, admittedly I don't have a lot of experience with "cxFreeze" but at least that gives me something to search for. Maybe instead, compile python to live somewhere under /opt/elasticsearch-curator/python? I will piddle around a bit, and see what we can find out here. 

Another idea (perhaps) would be to release it integrated with the OS provided python packages, or as something like a "virtualenv" so that its completely self contained (which is what I thought was happening before).

**Comment by untergeek** [comment]
Freezing effectively does make a virtualenv, it's just packaged with any necessary libraries to make a portable runtime environment. The "freezing" process is what assigns `/opt/elasticsearch-curator` as the path for everything and copies any necessary libraries in with it. That's why I am obliged to use the `LD_LIBRARY_PATH` route, so that when Curator is executed, it uses its own libraries to the exclusion of anything in the system.  The breakage you describe with `pip` installs is the same reason I package it this way. In particular the RHEL/CentOS distros suddenly upgraded OpenSSL with breaking changes, and I previously had to pick a dependency, which could force a user to upgrade SSL or _not_ upgrade (if they wanted to). Neither of these outcomes appealed to me, so I took to this build/freeze/include so everything was up-to-date and included.

**Comment by TJM** [comment]
It is sooo much fun releasing software. As an added bonus, now that you are releasing embedded dependent libraries, you get to track all the security vulnerabilities in all those and make sure you release fixes when they come out. sounds like fun, right? :(

**Comment by untergeek** [comment]
Tell me about it. It was not a decision without side-effects and consequences, but it's what I chose.

**Comment by untergeek** [comment]
I changed how Curator is built and packaged and this should no longer happen.
