### ISSUE TITLE
Documentation does not explain how to freeze indices

### ISSUE THREAD

**Issue by arizonagroovejet** [elastic/curator#1556]
### Expected Behaviour
That Curator documentation at https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/actions.html includes an action for freezing an index as that functionality was apparently added a year ago https://github.com/elastic/curator/releases/tag/v5.8.0

### Actual Behaviour
Curator documentation does not explain how to freeze indexes.

**Comment by untergeek** [comment]
Moot. Elasticsearch has deprecated index freezing altogether.
