### ISSUE TITLE
Missing packages for CentOS8 and aarch64

### ISSUE THREAD

**Issue by mnasiadka** [elastic/curator#1564]
OpenStack Kolla project is building container images with Elasticsearch and curator - we've used pip packages in the past, but would like to move to RPM/DEB based packages.
I noticed that those packages are available at packages.elastic.co - but it's missing CentOS 8 packages at all (latest is CentOS 7) and aarch64 for both CentOS and Debian/Ubuntu.
Is that something that could be fixed?

**Comment by cturbe** [comment]
Hello,
I have the same problem. Until now, I used the Yum repositories to install the RPM Curator.
`baseurl=https://packages.elastic.co/curator/5/centos/7`

I can't find the URL for the Centos 8 pakage.
Is it planned to create the repo for Centos 8

Thanks

**Comment by untergeek** [comment]
Yes, there will be a repo for CentOS 8. 

It is doubtful there will be packages for aarch64 any time soon, though I do have machines capable of compiling there.

**Comment by untergeek** [comment]
Technically, the package for 7 _should_ work because pretty much everything included is self-contained and will not interfere with any other RPM. 

You can manually download it from [this page](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html) if you'd like to try.

**Comment by Fabian1976** [comment]
So... still no CentOS/RHEL 8 packages?

**Comment by untergeek** [comment]
This is addressed by:

1. No longer releasing RPM/DEB packages
2. Releasing Docker builds in both aarch64(arm64) and amd64

This is already released for Curator 7 and Curator 8 at https://hub.docker.com/repository/docker/untergeek/curator/general
