### ISSUE TITLE
5.8.2 unreleased

### ISSUE THREAD

**Issue by jsoucheiron** [elastic/curator#1565]
A PR was merged recently to allow a wider range of urllib3 versions. Could we release it as 5.8.2?
Thanks!

**Comment by vodwood** [comment]
Second the question. Not sure why [this issue](https://github.com/elastic/curator/issues/1560) is closed.
My understanding is that currently there is no way to pip install dependencies with curator 5.8.1 and botocore on python3.6.

**Comment by t3chn0m4g3** [comment]
Will 5.8.2 fix #1567?

**Comment by jsoucheiron** [comment]
@t3chn0m4g3, it should

**Comment by jsoucheiron** [comment]
@vodwood in theory the changes fixing it had been merged, but the release failed, so it needs reopening.

**Comment by t3chn0m4g3** [comment]
@jsoucheiron Thanks. Fingers crossed for working release :)

**Comment by disfluxly** [comment]
Anybody have any ideas when this will be released?

**Comment by jsoucheiron** [comment]
cc @untergeek

**Comment by untergeek** [comment]
Today, hopefully. I'm sorry for the prolonged delays.

**Comment by untergeek** [comment]
I have just released 5.8.2 to PyPi. RPM/DEB packages will likely be released tomorrow.

**Comment by t3chn0m4g3** [comment]
@untergeek Thank you :bowtie:
