### ISSUE TITLE
Binary, installation files for Windows are missing -  link is broken (404)

### ISSUE THREAD

**Issue by flamaniac** [elastic/curator#1573]
### Steps to Reproduce the Problem
Go here: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/windows-msi.html
Try do dowanload msi file.
You will see NoT Found - 404 code.

**Comment by lwille** [comment]
@untergeek last release was performed by you, is there anything I can do to help publishing the missing downloadable artifacts?

**Comment by untergeek** [comment]
I had to rebuild my windows build environment, and rebuild my linux package building scripts. I should hopefully be able to publish soon.

**Comment by lwille** [comment]
Thank you for your efforts, and season's greetings!

**Comment by untergeek** [comment]
I've had some weird stuff happen with my new build system. I have to fix it before I can fully publish. Please bear with me.

**Comment by lwille** [comment]
@untergeek let me know if you need a second pair of :eyes: - I'd be glad to help!

**Comment by untergeek** [comment]
I got everything fixed late last night. I should be pushing these today. There's a brand new package building script for Windows (not yet merged), and a brand new Docker-based package building tool for Linux (merged just now).

**Comment by untergeek** [comment]
They'd already be published if I hadn't realized I'd forgotten to migrate my 2FA codes when I got my new phone at Christmas. Had to get the Infrastructure team involved to get that reset.

**Comment by lwille** [comment]
Alright, looking forward :-) Than you for the effort!
