### ISSUE TITLE
Links to 5.8.3 .deb packages are broken

### ISSUE THREAD

**Issue by lwille** [elastic/curator#1578]
Documentation contains invalid links to the current version's `deb` packages

### Expected Behavior
* Clicking a "Direct Package Download Link" will download the current version's `.deb` package

### Actual Behavior
* Clicking one of the `.deb` download links in the documentation page results in a `404` error

### Steps to Reproduce the Problem
* Live documentation: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html
* Source: https://github.com/elastic/curator/blob/master/docs/asciidoc/installation.asciidoc

It seems there are no `.deb` packages for 5.8.3 or 5.8.2. Do you need support building / publishing them?

**Comment by lwille** [comment]
Related to https://github.com/elastic/curator/issues/1573

**Comment by untergeek** [comment]
Verified the links are working now.
