### ISSUE TITLE
v5.8.2 tag git conflict breaks the package

### ISSUE THREAD

**Issue by Babarberousse** [elastic/curator#1579]
Due to a merge conflict left unresolved, tag v5.8.2  is broken when trying to use it as a dependency.
https://github.com/elastic/curator/blob/v5.8.2/curator/defaults/client_defaults.py 

This is annoying as this is the latest git tag version at the moment. It should be pretty easy to release a v5.8.3 fixing this error while waiting for the next actual release.

**Comment by untergeek** [comment]
[5.8.3 is already out](https://github.com/elastic/curator/releases/tag/V5.8.3), for that exact reason.
