### ISSUE TITLE
filter_by_age is not calendar-aware

### ISSUE THREAD

**Issue by emmett9001** [elastic/curator#1580]
### Expected Behavior

When `IndexList.filter_by_age` is called with a `unit` of `months` or `years`, it should take into account the fact that
not all months contain 30 days, and not all years contain 365 days (because of leap years).

### Actual Behavior

When `IndexList.filter_by_age` is called with a `unit` of `months` or `years`, it performs a simple multiplication of
time units without taking leap years or variable-length months into account.

### Steps to Reproduce the Problem

Given a set of timestamped indices with names

```
2020.11.01
2019.11.01
2018.11.01
```

a call to `filter_by_age` like this

```
filter_by_age(
    source="name",
    direction="older",
    unit="years",
    timestring="%Y.%m.%d",
    unit_count=2,
    epoch=datetime.datetime(2020, 11, 1).timestamp(),
)
```

will exclude the `2018.11.01` index from the result set even though a human reader would consider it not to be "older
than two years" from the given `epoch`. This happens because that `epoch` minus 365 days * 24 hours * 60 minutes *
60 seconds * 2 years results in the timestamp of 2018.11.02 since February 2020 had an extra day because of the leap
year (referencing the [`age` documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html#_age_calculation)).

### Specifications

  - Version: 5.6.0
  - Platform: Ubuntu 18.04.4
  - Subsystem:

## Context (Environment)

I maintain an Elasticsearch cluster that uses timestamped indices for aggregation of metrics data, and I use curator to
delete indices that are older than a customer's contractual retention period. The lack of calendar awareness in curator
could cause indices that have not yet exceeded their contractual retention limit to be deleted too early, and requires
me to write application logic that takes leap years into account.

**Comment by untergeek** [comment]
Perhaps you should look into the [`period`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_period.html) filter.

**Comment by emmett9001** [comment]
Yup, that does what I'm looking for.
