### ISSUE TITLE
Dependency pinning urllib and click

### ISSUE THREAD

**Issue by vibpe** [elastic/curator#1589]
### Expected Behavior
The most current dependencies should be used.

### Actual Behavior
In setup.py the dependency of urrlib3 is pinned to a version  <1.26 and the version of click is pinned to <7.0.

However curator 5.8.3 compiles here and works with urllib3 1.26.2 and click 7.1.2. Tested with Python 3.8 and Python 3.9.

What is the intention on pinning this dependencies? Are there any plans on upgrading this dependencies?

**Comment by vibpe** [comment]
Gentoo bug regarding old dependencies of curator: https://bugs.gentoo.org/714860

**Comment by untergeek** [comment]
The urllib dependency is because of upstream co-dependencies (Namely: boto3) that were broken at the time of last release. Click testing was similarly non-functional in the past. I can revisit these dependencies if `boto3` is finally properly functional with the latest `urllib3` releases.

**Comment by sethmlarson** [comment]
@untergeek iirc boto3 now allows urllib3 1.26.x so you should be good to unpin.

**Comment by untergeek** [comment]
These have been unpinned as of 5.8.4
