### ISSUE TITLE
Curator doesn't delete indices if only one index has wrong name.

### ISSUE THREAD

**Issue by rizvaughan** [elastic/curator#1593]
Hi,
We use curator for index retention in aws managed elasticsearch service. The filter config for our curator is 
`    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 20
      exclude:
`
I noticed that curator didn't do it's jobs for few days and upon checking the logs, I found out that curator failed to delete older indices because one of the index had wrong date in it's name. This is the error I got
 `Failed to complete action: delete_indices.  <type 'exceptions.ValueError'>: time data '2021.24.02' does not match format '%Y.%m.%d'` 
It doesn't mentioned exactly what index had this issue. So I manually searched and deleted that and now it's working fine. 
In our second elasticsearch service domain I have almost the same issue. In that domain I changed daily indexes to weekly and while testing I ended up making few indixes with wrong name instead of date in the end. these indices have 'indexname-%{+yyyy.ww}'. Now the issue I face here is that I can't manually delete them like I did for the previously mentioned domain.
I end up with `400 bad request`.
Could anyone help me delete these indices?
Plus, it would be great if curator just ignore the problematic index and complete it's job with other indixes.
Thank you

**Comment by untergeek** [comment]
Hi @rizvaughan 

Have you enabled DEBUG logging? It will outline which indices are being processed. 

You should also remove the [default blacklist](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/configfile.html#blacklist) to not hide the `elasticsearch-py` and `urllib` logging messages. This will help explain where the 400 message is.

The logging block should look like this (having at least these 3 lines):

```
logging:
  loglevel: DEBUG
  logfile: /path/to/filename.log
  blacklist: []
```

**Comment by rizvaughan** [comment]
ok...so I did what you asked me to do. I had logging set to INFO. As we (should)have ~1k indices but I see double that of 1k. At the moment I can't explain how. Because I see indices with postfix `*-space.graphql.app-1991.11`. I first need to confirm with application team if it's something they are responsible. It can't be anyway related to enabling debug log I believe . Anyway, coming back to the issue of delete a particular index, I don't get `indexname-%{+yyyy.ww}` in the delete list at all. The curator settings is to delete indices older than 2 weeks. The mentioned index is definitely 2 weeks older. 
With the debug log this is what I get.
`2021-03-14 18:46:57,997 DEBUG          curator.indexlist          filter_by_age:552  Index "ad-rs-ms-qa2-proxysql-error-%{+yyyy.ww}" does not meet provided criteria. Removing from list.`

**Comment by untergeek** [comment]
The next question is, "what `timestring` are you using for year+week dates? Can you please share your Curator filter list here?

**Comment by rizvaughan** [comment]
This is my filter file 
`---

actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 2 weeks (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%W'
      unit: weeks
      unit_count: 2
      exclude:`
We had daily indices in the begining, created by td-agent. While changing those indices to weekly, I made a mistake and created few 'indexname-%{+yyyy.ww}' indices.
Now they are just sitting there and I can't find a way to delete them.

**Comment by untergeek** [comment]
Okay, so you _literally_ have indices with `%{+yyyy.ww}` in the title?

If so, you may find this FAQ question helpful: [Q: Can Curator handle index names with strange characters?](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/faq_strange_chars.html)

**Comment by rizvaughan** [comment]
yes I have literally these characters in the title!
This is what I wanted. Now I need to just make a regex and that's it.
Thank you @untergeek for your help and time. Much appreciated.
