### ISSUE TITLE
Failed to try to create an index with the name of the month

### ISSUE THREAD

**Issue by Kledenai** [elastic/curator#1594]
Hello, good morning.

I am using curator version curator, **version 5.8.1** I am trying to create indices but it shows me this error !
**Failed to complete action: create_index.  <class 'curator.exceptions.FailedExecution'>: Index <kotaka-{now/d{dd-MMM-yyyy}}> already exists.**

This index does not exist at the moment, this error occurs only when I use date format passing **MMM**

I am basically unable to apply the customization I want on the date, returning the name of the month instead of the number, and whenever I place some customization based on the documentation that the curator proposes to follow, it ends up giving this error.

documentation I'm following to make the changes: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/date-math-index-names.html

website that I used to get to this setting: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

what is expected is that it will create in this format:

```text
kotaka-15-mar-2021
```

My action:

```text
actions:
  1:
    action: create_index
    description: "Create index with date format"
    options:
      name: '<kotaka-{now/d{dd-MMM-yyyy}}>'
```

**Comment by untergeek** [comment]
Curator only does a pass-through with date math. If Curator is getting an error, chances are very good you'd also see the same error when creating directly using Elasticsearch.

In the Kibana Dev Tools, that would look like:

```
PUT /%3Ckotaka-%7Bnow%2Fd%7Bdd-MMM-yyyy%7D%7D%3E
```

And when I try that myself, this is what I see:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "invalid_index_name_exception",
        "reason" : "Invalid index name [kotaka-15-Mar-2021], must be lowercase",
        "index_uuid" : "_na_",
        "index" : "kotaka-15-Mar-2021"
      }
    ],
    "type" : "invalid_index_name_exception",
    "reason" : "Invalid index name [kotaka-15-Mar-2021], must be lowercase",
    "index_uuid" : "_na_",
    "index" : "kotaka-15-Mar-2021"
  },
  "status" : 400
}
```
This is why Curator is failing. Indices must be all lowercase. If there is a formatting option that returns all lower-case, then that would work. My quick look over the Java Time doc suggests that no such option exists, unfortunately.
