### ISSUE TITLE
Support setting index blocks or metadata to readonly

### ISSUE THREAD

**Issue by cite** [elastic/curator#160]
It would be nifty if curator could set index blocks or index metadata to readonly for indices exceeding a certain age - even better if the user could chose whether only blocks or full metadata should be marked as readonly.

This way, if older data are not considered too valuable, there would be no need to optimize older indices several times.

And yes, in an ideal world, no index above a certain age would get new data :)

**Comment by untergeek** [comment]
The functionality is still not there.  When it is, this can be added.

**Comment by untergeek** [comment]
I've tested this and it does work as expected in recent versions.  This will be back on the menu for a future release of Curator.

**Comment by cembree** [comment]
Following up from #360 marked as duplicate.  Sorry, my search for read only didn't find this as readonly. :-/ 
Our case is for ES in a non-logstash config.  We're dumping a couple billion documents per hour to highly optimized indexes.   We did some extensive performance testing last summer w/ ES 1.3.x and found that after a few hours ES performance would begin to degrade quickly.  After a consultation w/ ES support, we tweaked the blocks.write and codec.bloom.load, ES was able to keep up again.   I think we peaked out around 700k dps.

**Comment by untergeek** [comment]
Thanks for the info.  I know that the bloom filter cache would explain the behavior you described, all by itself, even.

Bloom is irrelevant to this issue as there's already a bloom feature in Curator, and bloom filter cache is disabled by default since 1.4.x.  I'm actually wondering what the change would be with _just_ the blocks.write, since bloom is no longer an issue.  Do you have any data on that front?

**Comment by cembree** [comment]
Hm.  I do not.  We've seen a few items in 1.4 and 1.5.x that make us want to re-test, but I haven't had a chance to spin it up.

**Comment by untergeek** [comment]
**Update:** There's a problem with setting indices to read-only (at least in Elasticsearch 1.6 and using the elasticsearch python module):

### Create index
```python
>>> client.indices.create(index=“foo”)
{u’acknowledged’: True}
```

### Index a document
```python
>>> client.index(index=“foo”, doc_type=“mytype”, body={“name”:”James”})
{u’_type’: u’mytype’, u’_id’: u’AU345CoLYzProjwnt2EQ’, u’created’: True, u’_version’: 1, u’_index’: u’foo’}
```

### Set index to read-only
```python
>>> client.indices.put_settings(index=“foo”, body=‘blocks.write=True’)
{u’acknowledged’: True}
```

### Attempt index operation to read-only index (will fail)
```python
>>> client.index(index=“foo”, doc_type=“mytype”, body={“name”:”Steve”})
Traceback (most recent call last):
  File “<stdin>”, line 1, in <module>
  File “/Library/Python/2.7/site-packages/elasticsearch/client/utils.py”, line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File “/Library/Python/2.7/site-packages/elasticsearch/client/__init__.py”, line 254, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File “/Library/Python/2.7/site-packages/elasticsearch/transport.py”, line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File “/Library/Python/2.7/site-packages/elasticsearch/connection/http_urllib3.py”, line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File “/Library/Python/2.7/site-packages/elasticsearch/connection/base.py”, line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthorizationException: TransportError(403, u’ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]’)
```

This much is expected.  I set `blocks.write` to `True` and I can’t write.  

*But then I set it to `False`, which should allow writes again, and I still can’t write…*

### Set index to allow writes
```python
>>> client.indices.put_settings(index=“foo”, body=‘blocks.write=False’)
{u’acknowledged’: True}
```
### I still can't write
```python
>>> client.index(index=“foo”, doc_type=“mytype”, body={“name”:”Steve”})
Traceback (most recent call last):
  File “<stdin>”, line 1, in <module>
  File “/Library/Python/2.7/site-packages/elasticsearch/client/utils.py”, line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File “/Library/Python/2.7/site-packages/elasticsearch/client/__init__.py”, line 254, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File “/Library/Python/2.7/site-packages/elasticsearch/transport.py”, line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File “/Library/Python/2.7/site-packages/elasticsearch/connection/http_urllib3.py”, line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File “/Library/Python/2.7/site-packages/elasticsearch/connection/base.py”, line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthorizationException: TransportError(403, u’ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]’)
```

Until this is reversible, this feature will not be incorporated into Curator.

**Comment by untergeek** [comment]
This is now reversible:
```
>>> client.indices.put_settings(index="foo", body={"index.blocks.write":False})
{u'acknowledged': True}
>>> client.index(index="foo", doc_type="mytype", body={"name":"Steve"})
{u'_type': u'mytype', u'_shards': {u'successful': 1, u'failed': 0, u'total': 2}, u'_index': u'foo', u'_version': 1, u'created': True, u'result': u'created', u'_id': u'AVtY857GaUWcUuzD7SWs'}
```

As such, this feature will now be added as part of #656, rather than be its own dedicated feature
