### ISSUE TITLE
5.8.3 is it decommission ??

### ISSUE THREAD

**Issue by vikas1389** [elastic/curator#1603]
While installing curator 5.8.3 we have been getting error on ubuntu 18.04:

Command: sudo apt-get update && sudo apt-get install elasticsearch-curator=5.8.3

error:

Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '5.8.3' for 'elasticsearch-curator' was not found

**Comment by untergeek** [comment]
Install 5.8.4. Yes, older versions get dropped from the repo. It’s a bad artifact I hope to address in the future.

**Comment by vikas1389** [comment]
Thank you- Also whenever we add new version to repo- is it always dropping older versions? reason to ask is on few server older versions may be cached and they are still working. with python upgrade - do u see any precautions to consider!

**Comment by untergeek** [comment]
Stale. RPM/DEB packages are no longer being built.
