### ISSUE TITLE
Curator doesn't compatible with OpenSearch 1.0.0.

### ISSUE THREAD

**Issue by balar06** [elastic/curator#1617]
## To submit a bug or report an issue
If the curator is installed by setting disable_action: false, then the curator pod failed to start.
This is due to Opensearch version incompatibility

 **Questions**
will curator work with Opensearch ?
Is there any plan to release curator to work with Opensearch?

### Expected Behavior
Pods should be up and running successfully

### Actual Behavior
Curator pod is not up and running

Error
{"@timestamp": "2021-06-02T15:35:11.576Z", "function": "do_version_check", "linenum": 926, "loglevel": "ERROR", "message": "Opensearch version 1.0.0 incompatible with this version of Curator (5.8.4)", "name": "curator.utils"}
{"@timestamp": "2021-06-02T15:35:11.576Z", "function": "do_version_check", "linenum": 927, "loglevel": "CRITICAL", "message": "Curator cannot continue due to version incompatibilites. Exiting", "name": "curator.utils"}

### Steps to Reproduce the Problem

1. Install Opensearch and Curator [i.e setting disable_action:false] in a curator
2. Check Curator pods .
3. It throws error in curator pods.

### Specifications

  - Version: opensearch 1.0. Curator 5.x

## Context (Environment)

Indices are not deleted

## Detailed Description
If the curator is installed by setting disable_action: false, then the curator pod failed to start.
This is due to Opensearch version incompatibility

**Comment by dberuben** [comment]
Yes same issue on my side, using OpenSearch with curator

`2021-09-29 11:31:12,008 ERROR     Unable to connect to Elasticsearch cluster. Error: The client noticed that the server is not Elasticsearch and we do not support this unknown product`

curator, version 5.8.4

**Comment by k3a** [comment]
For OpenSearch may want to use integrated ISM (index state management) instead of Curator. It is actually very easy to configure and can also be configured via UI / OpenSearch Dashboard.

See the example policy in the doc https://opensearch.org/docs/latest/im-plugin/ism/policies/#example-policy
See the Amazon doc https://aws.amazon.com/premiumsupport/knowledge-center/opensearch-low-storage-ism/

**Comment by OlleLarsson** [comment]
ISM does not fully replace the functionality of Curator, so is there any update regarding this topic?

**Comment by ranjeet0702** [comment]
Is Curator is compatible with opensearch 2.x and above version? if yes then which version is compatible

**Comment by untergeek** [comment]
Curator will never be written to be compatible with OpenSearch. It is _Elasticsearch_ Curator. While previous versions may be easily modified or even work with a compatibility mode, when Curator v8 comes out it will not be due to using the version-tied Python module.

**Comment by ranjeet0702** [comment]
Can i use the Curator py for OpenSearch in place of elastic Curator which is used earlier with open distro.

**Comment by untergeek** [comment]
@ranjeet0702 I cannot guarantee it will work at all. It may for the earliest versions of OpenSearch using compatibility mode, but otherwise, not likely.
