### ISSUE TITLE
Manage system indices with Curator in Elasticsearch 7.14.x

### ISSUE THREAD

**Issue by rdrgporto** [elastic/curator#1627]
### Specifications

  - Version: 5.8.4

## Detailed Description

Hi, everyone

I have seen a **warning message** in **Curator** in which **Elasticsearch** reports that in a future major version **direct access to system indices will be prevented by default**. Here you are the message:

```
/opt/bitnami/python/lib/python3.6/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: this request accesses system indices: [.apm-agent-configuration, .apm-custom-link, .async-search, .kibana_1, .kibana_7.14.2_001, .kibana_task_manager_1, .kibana_task_manager_7.14.2_001, .security-7, .tasks], but in a future major version, direct access to system indices will be prevented by default
```

Is it planned to deal with system indices in the near future?

Thanks in advance

**Comment by marcing** [comment]
I would be interested how to disable the Warning. We get a lot of e-mails with it.
