### ISSUE TITLE
Currator exit silently when issue with connection

### ISSUE THREAD

**Issue by buker** [elastic/curator#1632]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue
Curator exit with 0 when it has issue with connection to ES.
for examplem, network issue, wrong credentials

### Expected Behavior
Exit with error

### Actual Behavior
Exit with 0, no log which will tell about issue even when DEBUG level

### Steps to Reproduce the Problem
Configure host which is behind firewall or use wrong credentials

### Specifications

  - Version: 5.7.6
  - Platform: docker image/kubernetes
  - Subsystem:

**Comment by OvervCW** [comment]
That bug was fixed in 5.8.0. If you're using the deprecated Helm chart, like I am, then you can fix it using:

```yaml
image:
  tag: "5.8.4"
```

**Comment by untergeek** [comment]
Indeed. This is also no longer an issue with Curator 8
