### ISSUE TITLE
Use regional endpoints for s3 repositories

### ISSUE THREAD

**Issue by jacoor** [elastic/curator#1633]
### Expected Behavior

Snapshot should be created. 

### Actual Behavior
I am trying to run backups using curator on s3 in Bahrain, me-south-1 region. 
When I try to run create_repo, it passes. Create snapshot fails with: 
```
{
    "error": {
        "root_cause": [
            {
                "type": "repository_exception",
                "reason": "[2030_07] Could not determine repository generation from root blobs"
            }
        ],
        "type": "repository_exception",
        "reason": "[2030_07] Could not determine repository generation from root blobs",
        "caused_by": {
            "type": "i_o_exception",
            "reason": "Exception when listing blobs by prefix [index-]",
            "caused_by": {
                "type": "amazon_s3_exception",
                "reason": "The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to. (Service: Amazon S3; Status Code: 400; Error Code: IllegalLocationConstraintException; Request ID: G9V20T83GEFTE9AP; S3 Extended Request ID: tQzSrRdUqpTqIe7fFOB/WKqWJBsr4Vj7p+6ImpZnN7xiboEkVrbDRLtjXoXWaNy6FvsYuMGsNIw=)"
            }
        }
    },
    "status": 500
}
```
The same error occurs when trying to just use POST on Elasticsearch itself. 
Simple solution is to add             "endpoint": "s3.me-south-1.amazonaws.com" when creating repo, at least while using POST.
Could this be added?

Bahrain is peculiar AWS region not enabled by default and S3 has also specific settings there.

### Steps to Reproduce the Problem
Try to create repo and a snapshot to s3 in me-south-1

### Specifications
  - Version: 5.8.x

**Comment by untergeek** [comment]
This is not Curator's problem. This is something elasticsearch replied with. I hope it's since been resolved.

All Curator can do is receive a named repository. It does not know who provides it, or anything about it.
