### ISSUE TITLE
Update Click dependency to 8

### ISSUE THREAD

**Issue by ghost** [elastic/curator#1637]
### Expected Behavior
Can use elasticsearch-curator with other packages that depend on click version 8.

### Actual Behavior
```
ERROR: Cannot install -r sysadmin/requirements-to-freeze.txt (line 14) and -r sysadmin/requirements-to-freeze.txt (line 3) because these package versions have conflicting dependencies.

The conflict is caused by:
    black 22.1.0 depends on click>=8.0.0
    elasticsearch-curator 5.8.4 depends on click<8.0 and >=7.0
```

### Steps to Reproduce the Problem
`pip install black==22.1.0 elasticsearch-curator==5.8.4`

### Specifications

  - Version: 5.8.4
  - Platform: all

## Context (Environment)
Many other Python packages require Click 8, such as Black.

## Detailed Description
Update elasticsearch-curator to work with click version 8

**Comment by untergeek** [comment]
This is resolved with the release of Curator v8 (and v7 and v6)
