### ISSUE TITLE
Curator month unit set to 31 days

### ISSUE THREAD

**Issue by hemant-mamtora** [elastic/curator#1646]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue
can we pls set 1 month unit in curator to 31 days instead of 30 days?

### Expected Behavior
This will avoid moving of shards from current month index on 31st days of the month from hot tier to warm tier

### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications

  - Version: elasticsearch-curator-5.8.4-1.x86_64
  - Platform: Linux
  - Subsystem: OL6

## Context (Environment)
 Due to this one of my active index(which was being written with more docs started to move from hot nodes to warm nodes, thereby causing a lot of back pressure from elastic cluster to the logstash nodes.

We have 7 months in a year which are 31 days, hence it will make more sense to change unit of 1 month from 30 to 31 days. For months that are 30 days shard allocation or any action will be taken on 01st or 02nd date of the next month

Change 1 month unit from 30 to 31

## Detailed Description

Let me know pls if you have any question.

**Comment by untergeek** [comment]
It sounds like you need the [`period`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_period.html) filtertype. This functionality already exists.
