### ISSUE TITLE
build the curator 7 arm docker image error

### ISSUE THREAD

**Issue by KevinLiangX** [elastic/curator#1664]
Hello 

i need use the curator7 to manage the es7 by arm node,  i docker build the curator source code by Dockerfile ,it seem that is arm image,
![image](https://user-images.githubusercontent.com/40968187/217481107-c498199a-94df-4a2c-9b11-ffd01c400aeb.png)

but when docker run to test the image, it show error:
![image](https://user-images.githubusercontent.com/40968187/217480645-185ec5df-54f0-45a5-a9d6-688ed04862d2.png)

i see the dockerfile have some x86 codes ,  does it need to replace? need your help for the arm image

thanks

**Comment by untergeek** [comment]
I haven't built for `arm64` yet. I can give it a try and see.

**Comment by untergeek** [comment]
Hi @KevinLiangX 

This took a bit of effort. I had to change a few things in the `Dockerfile` to get it working on multiple architectures and yet work for v6, v7, and v8. So far, it looks like I've succeeded.

An official image + tag will come later, but would you please test this image:

`untergeek/curator:multiarch-test7`

I tested it on one of my ARMv8 SBCs, and it seems to function just fine. If you run into any issues, let's fix them before I commit these changes and release a new version.

Thanks!

**Comment by KevinLiangX** [comment]
Thanks  @untergeek 
I will test it,.Any issues ,fix it and feedback to you

**Comment by untergeek** [comment]
Closing this now. You may need to `docker pull untergeek/curator:7.0.0` again, but it now has fully functional amd64 and arm64 builds.

**Comment by untergeek** [comment]
Gonna mark this closed. The current release (you may need to do `docker pull untergeek/curator:7.0.0` again) has arm64 and amd64 builds that are working.
