### ISSUE TITLE
curator cronjob error

### ISSUE THREAD

**Issue by rshiva777** [elastic/curator#1678]
## For usage questions and help
Please create a topic at https://discuss.elastic.co/c/elasticsearch

Perhaps a topic there already has an answer for you!

## To submit a bug or report an issue

curator cronjob is not applied to cluster

### Expected Behavior

curator cronjob should be deployed into cluster without any issues

### Actual Behavior

curator cronjob should be applied to cluster

### Steps to Reproduce the Problem

  1.
  1.
  1. Install

### Specifications

  - Version: curator 5.8.5
  - Platform: kubernetes 1.23
  - Subsystem:

## Context (Environment)

Indices are not getting deleted as curator job is not deployed to clear the old indices

## Detailed Description

Curator yaml:

apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-5.8.5-gks.1
    heritage: Helm
    release: elasticsearch-curator
  name: elasticsearch-curator
  namespace: efk-system-logging
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch-curator
        release: elasticsearch-curator
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: elasticsearch-curator
            release: elasticsearch-curator
        spec:
          containers:
          - args:
            - --config
            - /etc/es-curator/config.yml
            - /etc/es-curator/action_file.yml
            command:
            - /usr/local/bin/curator
            image: curator:5.8.5
            imagePullPolicy: IfNotPresent
            name: elasticsearch-curator
            volumeMounts:
            - mountPath: /etc/es-curator
              name: config-volume
            - mountPath: /etc/certs
              name: es-certs
              readOnly: true

When i try to apply the above yaml, getting the below error

Error from server (InternalError): error when creating "cronjob.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value

**Comment by rshiva777** [comment]
I tried to add the annotation on the template section as below, even then no luck


```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
     
```

getting the below error

`Error from server (InternalError): error when creating "cj4": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`

**Comment by untergeek** [comment]
Those errors are not from Curator. Those error messages are ostensibly from Kubernetes. I can't help with that.
