### ISSUE TITLE
How to Install without AWS feature

### ISSUE THREAD

**Issue by metalalive** [elastic/curator#1730]
Hi, I try to install curator without AWS-related packages like `boto3` or `requests-aws4auth` because I don't need them in my application.
I don't know which flag or option to use with my installation command (I use poetry and pip) , I tried to find relevant information from the GitHub issue page but not found anything yet. Thanks.

**Comment by untergeek** [comment]
Curator has not included these libraries since the 5.x releases. You can review all dependencies [here](https://github.com/elastic/curator/blob/d80a7a5fc7626e7ca81e92ba7eb483cc7e450f7e/pyproject.toml#L31).
