### ISSUE TITLE
Daily snapshots

### ISSUE THREAD

**Issue by bobrik** [elastic/curator#174]
I want to keep backups of my daily indices forever and I want daily snapshots where each snapshot only contains index for specific day. Like this:
- snapshot `sessions-2014-06-10` contains index `sessions-2014-06-10`
- snapshot `sessions-2014-06-11` contains index `sessions-2014-06-11`

Looks like this isn't supported by curator currently. What is supported:
- Incremental snapshot with fixed name: `sessions` will contain each index as another "layer".
- Daily snapshots with all indices (?). Not sure how to use that to solve my problem.

My option would allow to automatically fix broken snapshots and skip duplicate snapshots for indices.

Am I missing something? Should I add PR for this?

**Comment by trompx** [comment]
Hello,

I got the way elasticsearch store data as segments on the repository but so I have one more question, similar to http://elasticsearch-users.115913.n3.nabble.com/Delete-index-after-backup-td4070371.html but the answer does not appears obvious.

Say I make a snapshot of my cluster : mycluster_2015-08-27 and 10 days later I remove some data from my cluster that the snapshot point to.

How is the segments persisted in S3 with the incremental nature of the backup process ? In the doc at https://www.elastic.co/guide/en/elasticsearch/guide/current/retiring-data.html, the "Achiving Old Indices" is not really detailing what is going on.

So can I be sure that as long as a snapshot exists on the repository, all indexes deleted in the cluster would still be restorable from S3 ?

Thank you for the clarification.

**Comment by untergeek** [comment]
@trompx 

Until all snapshots which reference an index (and therefore by extension, a segment) are deleted, the segment (or index) is not deleted.

So, short answer: Yes.  As long as the snapshot exists (and is not corrupted), you can restore.

**Comment by trompx** [comment]
@untergeek 

Thank you very much for the fast answer and precisions.

**Comment by syndy1989** [comment]
Hi,
Is it possible to take snapshot of only certain data within indices using curator?

**Comment by untergeek** [comment]
No. Not even Elasticsearch can do that. And since Curator is really only an index selection wrapper around the Elasticsearch API calls, Curator cannot do this.

**Comment by syndy1989** [comment]
Thank you very much @untergeek

**Comment by syndy1989** [comment]
Nginx: How do i forward http request to another port?

I have three ES nodes.

Node 1(primary ):http://localhost:9200

Node 2:http://localhost:9201

Node 3:http://localhost:9202

what i want to do is, if primary node fails ES will make node 2 as primary but i want the page should redirect automatically to localhost:9201 and how would i do that using nginx on windows or is there any other way to do that. Thanks in advance

**Comment by untergeek** [comment]
@syndy1989 please ask usage questions in the Elasticsearch area of https://discuss.elastic.co

That question is totally unrelated to Curator

**Comment by ssukumar-conga** [comment]
Hi,
will it be possible for curator to take all indices backup once a day and incremental for every 15 minutes
