### ISSUE TITLE
archive old indexes with best_compression

### ISSUE THREAD

**Issue by rmuir** [elastic/curator#240]
Ideally we would optimize indexes with the "best_compression" codec. This uses less disk space (~53% of the space for apache log data, and should improve to ~43% in the future) but the tradeoff is that access to the _source and lucene stored fields are slower.

Maybe this can somehow be an optional part of the optimize process? Optimizing in this way should not be noticeably longer (my guestimate: ~ 5%-10% on average) as the cost of merging the stored fields from lz4 to deflate takes only 19% longer after https://issues.apache.org/jira/browse/LUCENE-6115 and https://issues.apache.org/jira/browse/LUCENE-6141.

See https://github.com/elasticsearch/elasticsearch/pull/8863 for more information. This only applies to elasticsearch 2.0 or higher.

**Comment by untergeek** [comment]
As this is dependent on Lucene 5.0, this will only be doable when I start testing with Elasticsearch 2.0 builds.

**Comment by untergeek** [comment]
It looks like this will be addressed by Curator, but not directly by enabling or disabling this feature.

From this [post](https://www.elastic.co/blog/elasticsearch-storage-the-true-story-2.0):

>Alternatively, we expect many users will want to utilize a “hot/warm” architecture using the shard allocation filtering feature. In this scenario, time-based indexes on hot nodes can be configured to be created with the default LZ4 compression; when they’re migrated to the warm nodes (configured with index.codec: best_compression in elasticsearch.yml), the indexes can be compressed by optimizing that index. It may be preferable to pay the CPU penalty of compression during this optimize process (which we often recommend executing when the cluster is known to be less utilized) than at the time of initial indexing.

With this being the case, it seems that Curator's existing shard allocation functionality will address this need.
