### ISSUE TITLE
no such option: --time-unit 

### ISSUE THREAD

**Issue by sephlietz** [elastic/curator#295]
The 3.0.0 release has broken --time-unit maybe?

    Downloading/unpacking elasticsearch-curator
      Downloading elasticsearch-curator-3.0.0.tar.gz
      Running setup.py (path:/tmp/pip_build_jlietz/elasticsearch-curator/setup.py) egg_info for package elasticsearch-curator
        
        warning: no previously-included files matching '__pycache__' found under directory '*'
        warning: no previously-included files matching '*.py[co]' found under directory '*'
    Downloading/unpacking elasticsearch>=1.0.0,<2.0.0 (from elasticsearch-curator)
      Downloading elasticsearch-1.4.0-py2.py3-none-any.whl (56kB): 56kB downloaded
    Downloading/unpacking click>=3.3 (from elasticsearch-curator)
      Downloading click-3.3-py2.py3-none-any.whl (58kB): 58kB downloaded
    Downloading/unpacking urllib3>=1.8,<2.0 (from elasticsearch>=1.0.0,<2.0.0->elasticsearch-curator)
      Downloading urllib3-1.10.2.tar.gz (132kB): 132kB downloaded
      Running setup.py (path:/tmp/pip_build_jlietz/urllib3/setup.py) egg_info for package urllib3
        
        warning: no previously-included files matching '*' found under directory 'docs/_build'
    Installing collected packages: elasticsearch-curator, elasticsearch, click, urllib3
      Running setup.py install for elasticsearch-curator
        
        warning: no previously-included files matching '__pycache__' found under directory '*'
        warning: no previously-included files matching '*.py[co]' found under directory '*'
        Installing es_repo_mgr script to /tmp/es.vql.cleanup.prVyaC/bin
        Installing curator script to /tmp/es.vql.cleanup.prVyaC/bin
      Running setup.py install for urllib3
        
        warning: no previously-included files matching '*' found under directory 'docs/_build'
    Successfully installed elasticsearch-curator elasticsearch click urllib3
    Cleaning up...
    Usage: curator delete [OPTIONS] COMMAND [ARGS]...
    
    Error: no such option: --time-unit

**Comment by untergeek** [comment]
The command structure is different in v3. Can you share the command-line you used? I don't see it in the output.

**Comment by untergeek** [comment]
`--time-unit` must come after `indices` or `snapshots`

**Comment by sephlietz** [comment]
The command used looks something like

    curator --host localhost delete --time-unit weeks --timestring %Y-%W- --prefix some-prefix- --suffix '*' --older-than 7

**Comment by untergeek** [comment]
You are missing the new sub-command `indices` after the `delete` command. This sub-command is what now drives index selection.

Try:

```
curator --help
```

Then:

```
curator delete --help
```

And finally:

```
curator delete indices --help
```

Hopefully this shows the change I'm trying to explain.

**Comment by sephlietz** [comment]
Got it, thanks.

**Comment by untergeek** [comment]
You won't need suffix '*' any more. 

Please read up on the command changes in the wiki here on github.
