### ISSUE TITLE
Delete indexes by date

### ISSUE THREAD

**Issue by OuesFa** [elastic/curator#305]
Hi,

I want to use Curator to delete indexes older than 7 days. I'm using Logstash to ship documents, so my index format is logstash-YYY.MM.DD.

I don't find equivalent command to :
 curator delete –older-than 7

Thanks for your help !

**Comment by untergeek** [comment]
Please refer to the [documentation wiki](https://github.com/elastic/curator/wiki):

[Delete examples](https://github.com/elastic/curator/wiki/Examples#delete-indices)
[Delete command](https://github.com/elastic/curator/wiki/Delete)
[Index selection](https://github.com/elastic/curator/wiki/index-selection)

There is a new command structure, which is discoverable at each subcommand via the `--help` flag:

```
curator --help
...
curator delete --help
...
curator delete indices --help
...
```

In  your case, what you would use is likely something like:

```
curator delete indices --older-than 7 --timestring %Y.%m.%d --time-unit days --prefix logstash
```

This will delete indices beginning with "logstash", which have a date pattern of _YEAR_._MONTH_._DAY_, and are older than 7 days.

**Comment by OuesFa** [comment]
Ok thank you :)

For now it says No indices matched provided args. it's weird cause it's the correct pattern i think to match this indice "logstash-2015.03.16"
But i will refer to the documentation.

**Comment by untergeek** [comment]
Try using 
```
curator show indices --all-indices
```
You'll see all indices.

**Comment by untergeek** [comment]
Any updates?

**Comment by OuesFa** [comment]
Thank you for quick reply and sorry i have been on holidays.

When i use show indices :
.kibana
logstash-2015.03.18
logstash-2015.03.19
logstash-2015.03.20
logstash-2015.03.21
logstash-2015.03.22
logstash-2015.03.23
logstash-2015.03.24
logstash-2015.03.25
logstash-soap2015.03.18
logstash-soap2015.03.19
logstash-soap2015.03.20
logstash-soap2015.03.21
logstash-soap2015.03.22
logstash-soap2015.03.23
logstash-soap2015.03.24
logstash-soap2015.03.25

For now, I'm trying to delete the "simple" indices logstash-YYYY.MM.DD

**Comment by untergeek** [comment]
Now that you have all indices showing, try adding the filtering:

```
curator show indices --older-than 7 --timestring %Y.%m.%d --time-unit days --prefix logstash
```

**Comment by OuesFa** [comment]
Same message when using show indices :/

2015-03-25 16:22:53,377 INFO      Job starting...
2015-03-25 16:22:53,396 WARNING   No indices matched provided args.
No indices matched provided args.

**Comment by OuesFa** [comment]
My bad sorry.
It works fine,  forgot that i deleted manually old indices ..

Thank you so much for your time.
