### ISSUE TITLE
Curator project needs a mascot

### ISSUE THREAD

**Issue by peterskim12** [elastic/curator#326]
I'm preparing a slide about Curator for a presentation and I have no cute mascot's image to put on there.

**Comment by untergeek** [comment]
Hey, @peterskim12, how is this for a draft?

![curator_logo_draft_cropped](https://cloud.githubusercontent.com/assets/1020383/7028955/c43d5f56-dd16-11e4-9e57-07a08793a654.png)

**Comment by untergeek** [comment]
Or this one:
![curator_logo_draft_2](https://cloud.githubusercontent.com/assets/1020383/7031364/341b8fc6-dd28-11e4-8ca4-ba4897656432.png)

**Comment by untergeek** [comment]
I'm working on the hand + feather duster, since they converted so poorly.  The final version will look better.

**Comment by peterskim12** [comment]
I like the concept. But I'm thinking that a simpler logo would be better? Just trying to think what would look good in a smaller (e.g. 200px square) form also...

**Comment by untergeek** [comment]
I could shrink it:

![curator_logo_draft_2_small](https://cloud.githubusercontent.com/assets/1020383/7047131/d3c6ca14-ddc7-11e4-9ef3-40d2f9a20fd1.png)

And make it easier to see by reducing it to 2 shelves, with 2 Logstash logos each

**Comment by untergeek** [comment]
That's 200x200, btw.

**Comment by untergeek** [comment]
Here's another 200x200:

![curator_draft_3](https://cloud.githubusercontent.com/assets/1020383/7054517/4d53d610-ddfa-11e4-9563-a5c34eb9960c.png)

**Comment by untergeek** [comment]
I cleaned up everything but the feathers, which are ridiculously hard to create for a novice like me.

**Comment by untergeek** [comment]
And a 400px version:

![curator_draft_3_400](https://cloud.githubusercontent.com/assets/1020383/7054569/9cf2156a-ddfa-11e4-82cf-46f3e2199b55.png)

**Comment by untergeek** [comment]
@peterskim12 I've been told the internal logo team will eventually handle this.  I'm closing the issue for now.

**Comment by peterskim12** [comment]
Thanks for trying. :) Yeah better to leave this to the pros. Hopefully we'll have Curator stickers at some point!
