### ISSUE TITLE
Snapshot verification times out

### ISSUE THREAD

**Issue by bobrik** [elastic/curator#339]
I'm using curator 3.0.2.

```
2015-04-08 01:07:33,910 INFO      Job starting...
2015-04-08 01:08:04,953 ERROR     Failed to verify all nodes have repository access.
```

```
# time curl -X POST http://web605:9200/_snapshot/ceph_s3/_verify?pretty
{
  "nodes" : {
    "pBdPew0bS4-tXTFq7ILaIA" : {
      "name" : "statistics06"
    },
    "4Fi21kZ5S_OxThErbSb83A" : {
      "name" : "statistics07"
    },
    "kLmTTs3kQUi8MGebMjO5DA" : {
      "name" : "statistics08"
    }
  }
}

real	0m35.171s
user	0m0.000s
sys	0m0.000s
```

Repository verification triggers a lot of requests for repository backend, it takes more time than curator can tolerate. cc @imotov, since I'm using s3-like repository.

**Comment by untergeek** [comment]
Hi @bobrik. v3.0.3 should correct the timeout. #323 restores the `--timeout` override, rather than trust in the unfortunately ineffective `--request-timeout` flag.

Even so, v3.0.2 should still work if you use the `--timeout` flag with a suitably large number.

**Comment by bobrik** [comment]
Got it, thanks!
