### ISSUE TITLE
curator 3.0.3 index filter selects all indexes with incomplete argument list

### ISSUE THREAD

**Issue by whyscream** [elastic/curator#348]
When using index selection criteria `curator show indices --timestring %Y.%m.%d --time-unit days`, I'd expect curator to give an error about a missing `--newer-than / --older-than` option. In stead it selects all indexes without any error. It looks as if `0` is used as silent default for the missing options, but i'd rather see no default at all than a rather nasty one.
BTW, I managed to *delete* all my logstash indexes (5 months worth of data) by accident this way.

**Comment by untergeek** [comment]
I'm sorry for the inconvenience you experienced.  This does seem like it should be the case.  You _can_ do selection with just the `--timestring` flag, but apparently adding `--time-unit` makes it think you're doing a delete by time.

I will add a check to ensure that `--time-unit` without `--newer-than`/`--older-than` does not result in this scenario.

**Comment by untergeek** [comment]
What's really going on is that it didn't care about `--time-unit` at all.  It simply matched all indices with a timestring pattern.  I can add a confirmation dialog to prevent accidentally using a `--timestring` without `--[older|newer]-than`.  Would that suffice?

This behavior is documented: http://www.elastic.co/guide/en/elasticsearch/client/curator/current/examples.html#_show_only_indices_with_a_timestring

**Comment by whyscream** [comment]
Thanks for the quick response. Backups are already back in place, so inconvenience was not that big :)

I indeed found out too that leaving out the `--time-unit` didn't matter, but as I had only one index not matching the `--timesting` format (the `kibana-int` index), it never occurred to me that it was actually applying a filter. Maybe a confirmation dialog is the best solution for this kind of problem.

**Comment by untergeek** [comment]
Will do!  Confirmation dialog coming up!

**Comment by untergeek** [comment]
Please see the code changes in #349 

The command-line output will look like this:
![screenshot 2015-04-17 16 00 44](https://cloud.githubusercontent.com/assets/1020383/7211843/94b2df0a-e51c-11e4-8e11-0442e57acad7.png)

**Comment by untergeek** [comment]
The warning will only display if it is **not** doing the `show` command or a `--dry-run`, by the way.

**Comment by untergeek** [comment]
Considering this fixed by #349
