### ISSUE TITLE
Question - Support local config files?

### ISSUE THREAD

**Issue by spuder** [elastic/curator#370]
I notice on the documentation page, that a lot of the commands omit the `--host` flag. That flag should be required. 

Will curator read in environment variables, or load stored data from a config file like `~/.curator.rc` ?

**Comment by untergeek** [comment]
`--host` isn't required because it has a default value of `localhost`.  It's only required if you are using something other than that.

The idea of using a `.curator.rc` file is an interesting one, but it kind of falls into duplicate territory with #343

**Comment by spuder** [comment]
Ah, forgot about localhost. I'll close in favor of 343

**Comment by untergeek** [comment]
Closing in favor of #343
