### ISSUE TITLE
Exit status of 99 for "No indices to act on" is inconvenient, make optional

### ISSUE THREAD

**Issue by timbunce** [elastic/curator#371]
As a rule we run all production shell scripts with exit-on-error enabled (we use [stringent](https://github.com/pottmi/stringent.sh/blob/master/stringent.sh). This has saved us from significant problems on many occasions.

I've recently updated our curator script to use curator v3 and discovered that the script, which contains several curator commands, will sometimes abort part way though due to a curator command reporting "No indices matched provided args." and returning a non-zero status.

The natural quick-fix would be to add `|| true` to commands that might fail. But this isn't a _failure_ and that 'fix' would mask real failures that we would want to know about.

A more complete fix requires extra shell coding to check the exit status and ignore the specific value of 99. That seems like a lot of effort to workaround this problem.

Please add an option to return a 0 exit status in the "No indices to act on" case.

**Comment by untergeek** [comment]
I appreciate that you're in a tough spot.  I was asked to include exit codes in #180.  Now my non-failure-but-still-a-failure exit code 99, which is ONLY for when there are no matching indices, is in the cross-hairs.

I think that I will lump this in to the work on #343.  If I can make that work, then exit code 99 will be moot for your use case.  You'll have a single config file which will run everything.

**Comment by petterl** [comment]
Please make new version without this available for pip.

**Comment by untergeek** [comment]
I will be releasing soon.  Please stay tuned.
