### ISSUE TITLE
[feature request]Unable to filter on indices containing the day of the year

### ISSUE THREAD

**Issue by petitout** [elastic/curator#392]
Hi,
I have indices with the following format :

```
indiceName-YYYY-DDD
```
with YYY the year and DDD the day of the year.
For example, today I store in : 

```
indiceName-2015-159
```

The problem is that the following commands return no indices :

```
curator --host myMachine show indices --newer-than 6 --time-unit days --timestring %Y-%j  --prefix indiceName-

curator --host myMachine show indices --older-than 6 --time-unit days --timestring %Y-%j  --prefix indiceName-
```

Thanks a lot

**Comment by petitout** [comment]
I have executed the command with the --debug option and it seems the "%j" is not well handled :
```
...
2015-06-08 12:14:06,973 DEBUG         curator.api.filter         get_date_regex:157  regex = \d{4}\-\j
2015-06-08 12:14:06,973 DEBUG          curator.cli.utils        filter_callback:170  REGEX = (?P<date>\d{4}\-\j)
...
```

**Comment by untergeek** [comment]
Hi, @petitout 

The reason day of year isn't recognized is that it is not (yet) included as a viable choice.

See https://github.com/elastic/curator/blob/master/curator/api/filter.py#L16-L26

>```
DATE_REGEX = {
    'Y' : '4',
    'y' : '2',
    'm' : '2',
    'W' : '2',
    'U' : '2',
    'd' : '2',
    'H' : '2',
    'M' : '2',
    'S' : '2',
}
```

Day of year is a curious choice for index naming.  If you want to add it, you'll have to find a way to add it.  Does `%j` always send a 3-digit number _when used in python?_  If so, you could add a pull request to both add it to the `DATE_REGEX` constant, and write a test or two.

If you don't want to create a pull request, we can treat this issue as a feature request.  Just edit the title and add the label "enhancement."

**Comment by petitout** [comment]
Hi,
Alright.
yes it is always returning 3 digits.
Thanks

**Comment by petitout** [comment]
Alright it seems we can close it as it has been implemented. 
Thanks
