### ISSUE TITLE
Add Synced Flush Support

### ISSUE THREAD

**Issue by pickypg** [elastic/curator#394]
With Elasticsearch 1.6, a new API and recovery tool called "[Synced Flush](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-synced-flush.html)" will appear. This will work similar to an optimized index so that indices can be recovered almost instantly, without having to compare segment files. However, the added benefit is that the older indices do _not_ need to be optimized at all; they just need to stop writing.

**Note**: For anyone that happens across this feature request. Optimizing an index is superior to synced flush in that the optimized version will get [sometimes significantly] better search performance, as well as reduced memory.

It would be great if sync flush could be triggered by Curator by having it as an option identical to `optimize`, minus optimize-specific flags (like the number of segments).

```
curator sync-flush indices <<index selection parameters>>
```

It may even be very useful to trigger this before (and perhaps after?) an optimize is run. Optimize is different in that it is just a forced merge that doesn't necessarily imply read-only indices (certainly that's the intent with merging to 1 segment), but synced flushing is meant for read-only (even if just temporary) indices for speedy recoveries. As a result, synced flushes will fail if the shard is being actively written, but the cost is very low.

**Comment by untergeek** [comment]
This is absolutely on my radar and will be added quickly.

**Comment by untergeek** [comment]
I will begin work on this as soon as @HonzaKral adds sync-flush to the elasticsearch-py module.  He tells me he's just coded it and will be releasing a version today.

**Comment by HonzaKral** [comment]
Pushed as https://github.com/elastic/elasticsearch-py/commit/aed7ec0d030b14eaadaaceb0ce6279e7cfd3a961 release comming later today, need to make sure all is in place.

**Comment by untergeek** [comment]
Super excited for this, @HonzaKral.  This will be one of the best new features for time-series users of Elasticsearch.  Ever.

**Comment by pickypg** [comment]
@untergeek Before I trick everyone into using my terminology, this is really being called "synced flush" and not "sync flush". But huge +1 to get this in. Big win.
