### ISSUE TITLE
Delete marvel indices automatically

### ISSUE THREAD

**Issue by marcotoma** [elastic/curator#398]
Hi, i installed curator to periodically delete the marvel indices. I've scheduled a windows task that runs every day, which executes a .bat file with the curator code. 
My code for Curator v.2 was this:  
curator delete --older-than 7 --prefix .marvel
Some days ago I upgraded curator to v.3, and i replaced my code with the following: 
curator delete indices --older-than 7 --prefix .marvel --time-unit days --timestring '%Y.%m.%d'

But it doesn't work. I read the documentation and seems that curator auto-prune the marvel indices to prevent accidental deletion.  
This was the reason why i installed curator: to be able to perform the delete-close-bloom-optimize  operations every day automatically, because the marvel data grows every day.

Is there a way to periodically delete the marvel data with curator?

**Comment by untergeek** [comment]
I'm not sure why that's failing for you.  My own daily script contains these lines:

```
/usr/local/bin/curator --logfile /var/log/curator/curator.log delete indices   --time-unit days --timestring %Y.%m.%d --prefix .marvel --older-than 15
/usr/local/bin/curator --logfile /var/log/curator/curator.log close  indices   --time-unit days --timestring %Y.%m.%d --prefix .marvel --older-than 14
/usr/local/bin/curator --logfile /var/log/curator/curator.log delete snapshots --time-unit days --older-than 30 --repository Untergeek --prefix marvel-
/usr/local/bin/curator --logfile /var/log/curator/curator.log optimize --max_num_segments 1 --delay 5 indices --time-unit days --timestring %Y.%m.%d --older-than 1 --prefix .marvel-
/usr/local/bin/curator --logfile /var/log/curator/curator.log snapshot --repository Untergeek --prefix marvel- indices --time-unit days --timestring %Y.%m.%d --older-than 2 --prefix .marvel-
```

That first line doesn't look substantially different from yours.  Could you enable the `--debug` flag and see what is in the output?  Hopefully it will reveal more about why it's not working.

**Comment by marcotoma** [comment]
Hi untergeek,
many thanks for your quick reply. 
When i execute the command the following message is provided: 
2015-06-12 17:14:22,844 INFO      Job starting: show indices
2015-06-12 17:14:22,844 WARNING   No indices matched provided args: {'regex': No
ne, 'newer_than': None, 'suffix': None, 'index': (), 'time_unit': 'days', 'older
_than': 7, 'all_indices': False, 'timestring': 'm.d', 'exclude': (), 'prefix': '
.marvel'}
No indices matched provided args.

**Here the output with --debug parameter:**

C:\Python34\Scripts>curator --debug show indices   --time-unit days --timestring
 m.d --prefix .marvel --older-than 7
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
170  REGEX = ^.marvel.*$
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
173  Added filter: {'pattern': '^.marvel.*$'}
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
174  New list of filters: [{'pattern': '^.marvel.*$'}]
2015-06-12 17:16:28,692 DEBUG         curator.api.filter         get_date_regex:
157  regex = \m\.\d
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
170  REGEX = (?P<date>\m\.\d)
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
173  Added filter: {'method': 'older_than', 'time_unit': 'days', 'value': 7, 'gr
oupname': 'date', 'pattern': '(?P<date>\\m\\.\\d)', 'timestring': 'm.d'}
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils        filter_callback:
174  New list of filters: [{'pattern': '^.marvel.*$'}, {'method': 'older_than',
'time_unit': 'days', 'value': 7, 'groupname': 'date', 'pattern': '(?P<date>\\m\\
.\\d)', 'timestring': 'm.d'}]
2015-06-12 17:16:28,692 INFO      curator.cli.index_selection                ind
ices:53   Job starting: show indices
2015-06-12 17:16:28,692 DEBUG     curator.cli.index_selection                ind
ices:54   Params: {'timeout': 30, 'debug': True, 'use_ssl': False, 'loglevel': '
INFO', 'host': 'localhost', 'logfile': None, 'http_auth': None, 'dry_run': False
, 'port': 9200, 'logformat': 'default', 'url_prefix': '', 'master_only': False}
2015-06-12 17:16:28,692 DEBUG          curator.cli.utils             get_client:
109  kwargs = {'timeout': 30, 'debug': True, 'use_ssl': False, 'port': 9200, 'lo
glevel': 'INFO', 'logfile': None, 'http_auth': None, 'dry_run': False, 'master_o
nly': False, 'url_prefix': '', 'logformat': 'default', 'host': 'localhost'}
2015-06-12 17:16:28,692 DEBUG         urllib3.util.retry               from_int:
155  Converted retries value: False -> Retry(total=False, connect=None, read=Non
e, redirect=0)
2015-06-12 17:16:28,692 INFO      urllib3.connectionpool              _new_conn:
203  Starting new HTTP connection (1): localhost
2015-06-12 17:16:28,692 DEBUG     urllib3.connectionpool          _make_request:
383  "GET / HTTP/1.1" 200 308
2015-06-12 17:16:28,692 INFO               elasticsearch    log_request_success:
63   GET http://localhost:9200/ [status:200 request:0.000s]
2015-06-12 17:16:28,692 DEBUG              elasticsearch    log_request_success:
65   > None
2015-06-12 17:16:28,692 DEBUG              elasticsearch    log_request_success:
66   < {
  "status" : 200,
  "name" : "R3_Alpha",
  "version" : {
    "number" : "1.3.4",
    "build_hash" : "a70f3ccb52200f8f2c87e9c370c6597448eb3e45",
    "build_timestamp" : "2014-09-30T09:07:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.9"
  },
  "tagline" : "You Know, for Search"
}

2015-06-12 17:16:28,708 DEBUG          curator.cli.utils          check_version:
90   Detected Elasticsearch version 1.3.4
2015-06-12 17:16:28,708 DEBUG         urllib3.util.retry               from_int:
155  Converted retries value: False -> Retry(total=False, connect=None, read=Non
e, redirect=0)
2015-06-12 17:16:28,708 DEBUG     urllib3.connectionpool          _make_request:
383  "GET /*/_settings?expand_wildcards=open%2Cclosed HTTP/1.1" 200 10527
2015-06-12 17:16:28,708 INFO               elasticsearch    log_request_success:
63   GET http://localhost:9200/*/_settings?expand_wildcards=open%2Cclosed [statu
s:200 request:0.000s]
2015-06-12 17:16:28,708 DEBUG              elasticsearch    log_request_success:
65   > None
2015-06-12 17:16:28,708 DEBUG              elasticsearch    log_request_success:
66   < {".marvel-2015.05.14":{"settings":{"index":{"mapper":{"dynamic":"true"},"
uuid":"vCMhfgutQrOADeA6LOttew","marvel":{"index_format":"5"},"analysis":{"analyz
er":{"default":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"
1","number_of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.05.27
":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"sE_49w6lRO-NHHGk1a7P
VQ","marvel":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"sta
ndard","stopwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","
version":{"created":"1030499"}}}},"es_search_purchasing":{"settings":{"index":{"
number_of_replicas":"1","number_of_shards":"5","uuid":"6gZbcPgSTqikulj7cxFIJw","
version":{"created":"1030499"}}}},"es_search_administration":{"settings":{"index
":{"uuid":"AcLyQOOMS3CXLxrnl_PKXA","number_of_replicas":"1","number_of_shards":"
5","version":{"created":"1030499"}}}},".marvel-2015.06.05":{"settings":{"index":
{"mapper":{"dynamic":"true"},"uuid":"F1L-1u_KQrWIJHyiKrCJaQ","analysis":{"analyz
er":{"default":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"
1","marvel":{"index_format":"5"},"number_of_shards":"1","version":{"created":"10
30499"}}}},".marvel-2015.06.09":{"settings":{"index":{"mapper":{"dynamic":"true"
},"uuid":"QxzG3mnDRWehkcbui7eV9g","analysis":{"analyzer":{"default":{"type":"sta
ndard","stopwords":"_none_"}}},"number_of_replicas":"1","marvel":{"index_format"
:"5"},"number_of_shards":"1","version":{"created":"1030499"}}}},"es_search_order
":{"settings":{"index":{"number_of_replicas":"1","number_of_shards":"5","uuid":"
YHJ9ak33SSukHu1KjHw39A","version":{"created":"1030499"}}}},".marvel-2015.05.26":
{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"30azx1MmTEqTojOk1kXPfA
","marvel":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"stand
ard","stopwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","ve
rsion":{"created":"1030499"}}}},"es_search_customer":{"settings":{"index":{"uuid
":"nE3h-KLGSIuFsbOu6mKZQw","number_of_replicas":"1","number_of_shards":"5","vers
ion":{"created":"1030499"}}}},".marvel-2015.06.03":{"settings":{"index":{"mapper
":{"dynamic":"true"},"uuid":"vWg3k91rQ6uT4b-hdbO4sw","marvel":{"index_format":"5
"},"analysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},
"number_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}
}},".marvel-2015.05.20":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid"
:"m_ANvmZpQ3uAIUlHJzrQXA","marvel":{"index_format":"5"},"analysis":{"analyzer":{
"default":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","n
umber_of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.05.21":{"s
ettings":{"index":{"mapper":{"dynamic":"true"},"uuid":"XhBfKdisTFOv4SoWHR7Ulw","
marvel":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"standard
","stopwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","versi
on":{"created":"1030499"}}}},"es_search_campagne":{"settings":{"index":{"number_
of_replicas":"1","number_of_shards":"5","uuid":"vOd_voTBTpWcPpLwNFE5GQ","version
":{"created":"1030499"}}}},".marvel-2015.06.01":{"settings":{"index":{"mapper":{
"dynamic":"true"},"uuid":"YG5_VBANTcCLJXyM4OraYg","marvel":{"index_format":"5"},
"analysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"nu
mber_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}},
"es_search_returnrefund":{"settings":{"index":{"number_of_replicas":"1","number_
of_shards":"5","uuid":"go6xr41FTFOGq86ST2PQkA","version":{"created":"1030499"}}}
},".marvel-2015.05.25":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":
"D9sCtA8xRqGtSCwZmzTLOw","marvel":{"index_format":"5"},"analysis":{"analyzer":{"
default":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","nu
mber_of_shards":"1","version":{"created":"1030499"}}}},"es_search_article":{"set
tings":{"index":{"number_of_replicas":"1","number_of_shards":"5","uuid":"pYnaSbH
nQvqaqMCwS05i6g","version":{"created":"1030499"}}}},".marvel-2015.06.07":{"setti
ngs":{"index":{"mapper":{"dynamic":"true"},"uuid":"ufcJU3e_Qf6BlKjDPoYT5A","anal
ysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"number_
of_replicas":"1","marvel":{"index_format":"5"},"number_of_shards":"1","version":
{"created":"1030499"}}}},".marvel-2015.06.10":{"settings":{"index":{"mapper":{"d
ynamic":"true"},"uuid":"SfcbAn-rR1C7WMVPeuGcfQ","analysis":{"analyzer":{"default
":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","marvel":{
"index_format":"5"},"number_of_shards":"1","version":{"created":"1030499"}}}},".
marvel-2015.05.18":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"wh9
xnK-IR9WfnN03hn9KCw","marvel":{"index_format":"5"},"analysis":{"analyzer":{"defa
ult":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","number
_of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.06.11":{"settin
gs":{"index":{"mapper":{"dynamic":"true"},"uuid":"59Hf-HZ_RWOTBFvZA4twJA","analy
sis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"number_o
f_replicas":"1","marvel":{"index_format":"5"},"number_of_shards":"1","version":{
"created":"1030499"}}}},".marvel-2015.05.16":{"settings":{"index":{"mapper":{"dy
namic":"true"},"uuid":"skpG_ppNRwSs1hNC7f0dRA","marvel":{"index_format":"5"},"an
alysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"numbe
r_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}},".m
arvel-2015.05.17":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"BnqX
Hr5ERUCB_Q0Cm8wN8A","marvel":{"index_format":"5"},"analysis":{"analyzer":{"defau
lt":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","number_
of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.05.30":{"setting
s":{"index":{"mapper":{"dynamic":"true"},"uuid":"n-2MxqK1Thi_751d0tFgIA","marvel
":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"standard","sto
pwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","version":{"
created":"1030499"}}}},".marvel-2015.05.29":{"settings":{"index":{"mapper":{"dyn
amic":"true"},"uuid":"9GY4tlJlTh6SZ54IZP5daQ","marvel":{"index_format":"5"},"ana
lysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"number
_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}},"es_
search_campagne_costs":{"settings":{"index":{"number_of_replicas":"1","number_of
_shards":"5","uuid":"_iG3lo7RSiK8p_P3IyNfcA","version":{"created":"1030499"}}}},
".marvel-2015.06.02":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"6
X2RsKhXQVC0jYNu3wEr_A","marvel":{"index_format":"5"},"analysis":{"analyzer":{"de
fault":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","numb
er_of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.05.31":{"sett
ings":{"index":{"mapper":{"dynamic":"true"},"uuid":"UMCovfxfQpWpOieoDvSSRg","mar
vel":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"standard","
stopwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","version"
:{"created":"1030499"}}}},".marvel-2015.05.28":{"settings":{"index":{"mapper":{"
dynamic":"true"},"uuid":"9pBfaYnaQpudZGVoxUv3mA","marvel":{"index_format":"5"},"
analysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"num
ber_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}},"
.marvel-2015.05.24":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"_Z
Ar0kBPQguqQyj2u5SfOA","marvel":{"index_format":"5"},"analysis":{"analyzer":{"def
ault":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","numbe
r_of_shards":"1","version":{"created":"1030499"}}}},".marvel-kibana":{"settings"
:{"index":{"mapper":{"dynamic":"true"},"uuid":"HEK6bNVcQRe4LWC-FopYIw","marvel":
{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"standard","stopw
ords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","version":{"cr
eated":"1030499"}}}},".marvel-2015.06.04":{"settings":{"index":{"mapper":{"dynam
ic":"true"},"uuid":"gpNWagzlR-icXj7jDAwSHg","marvel":{"index_format":"5"},"analy
sis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"number_o
f_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}},".marv
el-2015.06.08":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"gV4nRtz
eRhGXOFuXgvJcxg","analysis":{"analyzer":{"default":{"type":"standard","stopwords
":"_none_"}}},"number_of_replicas":"1","marvel":{"index_format":"5"},"number_of_
shards":"1","version":{"created":"1030499"}}}},"es_search_warehouse_movements":{
"settings":{"index":{"number_of_replicas":"1","number_of_shards":"5","uuid":"TGM
xOr3pRcul84Z26ZAMdg","version":{"created":"1030499"}}}},".marvel-2015.06.06":{"s
ettings":{"index":{"mapper":{"dynamic":"true"},"uuid":"qJJ9fknhTuGbwhYYhCnQYA","
analysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"num
ber_of_replicas":"1","marvel":{"index_format":"5"},"number_of_shards":"1","versi
on":{"created":"1030499"}}}},".marvel-2015.06.12":{"settings":{"index":{"mapper"
:{"dynamic":"true"},"uuid":"C85BhYEdQTCXT7OQlN1vMA","analysis":{"analyzer":{"def
ault":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","marve
l":{"index_format":"5"},"number_of_shards":"1","version":{"created":"1030499"}}}
},".marvel-2015.05.19":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":
"uGUJvEkbTvWmuDj6e3C3pg","marvel":{"index_format":"5"},"analysis":{"analyzer":{"
default":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","nu
mber_of_shards":"1","version":{"created":"1030499"}}}},".marvel-2015.05.15":{"se
ttings":{"index":{"mapper":{"dynamic":"true"},"uuid":"Ucvu0uYGQW6Hqy3OAsMQOA","m
arvel":{"index_format":"5"},"analysis":{"analyzer":{"default":{"type":"standard"
,"stopwords":"_none_"}}},"number_of_replicas":"1","number_of_shards":"1","versio
n":{"created":"1030499"}}}},".marvel-2015.05.22":{"settings":{"index":{"mapper":
{"dynamic":"true"},"uuid":"TDHb989PSCGiE2MlAEf-gw","marvel":{"index_format":"5"}
,"analysis":{"analyzer":{"default":{"type":"standard","stopwords":"_none_"}}},"n
umber_of_replicas":"1","number_of_shards":"1","version":{"created":"1030499"}}}}
,".marvel-2015.05.23":{"settings":{"index":{"mapper":{"dynamic":"true"},"uuid":"
Tv-MdOMpSGqm7X0oaUc-UQ","marvel":{"index_format":"5"},"analysis":{"analyzer":{"d
efault":{"type":"standard","stopwords":"_none_"}}},"number_of_replicas":"1","num
ber_of_shards":"1","version":{"created":"1030499"}}}}}
2015-06-12 17:16:28,724 DEBUG          curator.api.utils            get_indices:
27   All indices: ['.marvel-2015.06.09', '.marvel-2015.05.21', '.marvel-2015.06.
07', '.marvel-2015.05.28', 'es_search_article', '.marvel-2015.06.05', '.marvel-2
015.06.10', '.marvel-2015.06.02', '.marvel-2015.05.18', '.marvel-2015.06.04', '.
marvel-2015.05.16', '.marvel-2015.06.01', '.marvel-2015.06.08', '.marvel-kibana'
, '.marvel-2015.05.19', '.marvel-2015.05.14', '.marvel-2015.05.22', '.marvel-201
5.05.15', 'es_search_campagne_costs', 'es_search_campagne', '.marvel-2015.05.31'
, 'es_search_customer', 'es_search_warehouse_movements', '.marvel-2015.05.30', '
.marvel-2015.06.06', '.marvel-2015.05.25', 'es_search_purchasing', '.marvel-2015
.05.17', '.marvel-2015.05.24', '.marvel-2015.05.26', 'es_search_order', '.marvel
-2015.06.03', '.marvel-2015.06.12', '.marvel-2015.05.23', '.marvel-2015.06.11',
'.marvel-2015.05.27', '.marvel-2015.05.20', 'es_search_returnrefund', 'es_search
_administration', '.marvel-2015.05.29']
2015-06-12 17:16:28,724 DEBUG     curator.cli.index_selection                ind
ices:60   Full list of indices: ['.marvel-2015.06.09', '.marvel-2015.05.21', '.m
arvel-2015.06.07', '.marvel-2015.05.28', 'es_search_article', '.marvel-2015.06.0
5', '.marvel-2015.06.10', '.marvel-2015.06.02', '.marvel-2015.05.18', '.marvel-2
015.06.04', '.marvel-2015.05.16', '.marvel-2015.06.01', '.marvel-2015.06.08', '.
marvel-kibana', '.marvel-2015.05.19', '.marvel-2015.05.14', '.marvel-2015.05.22'
, '.marvel-2015.05.15', 'es_search_campagne_costs', 'es_search_campagne', '.marv
el-2015.05.31', 'es_search_customer', 'es_search_warehouse_movements', '.marvel-
2015.05.30', '.marvel-2015.06.06', '.marvel-2015.05.25', 'es_search_purchasing',
 '.marvel-2015.05.17', '.marvel-2015.05.24', '.marvel-2015.05.26', 'es_search_or
der', '.marvel-2015.06.03', '.marvel-2015.06.12', '.marvel-2015.05.23', '.marvel
-2015.06.11', '.marvel-2015.05.27', '.marvel-2015.05.20', 'es_search_returnrefun
d', 'es_search_administration', '.marvel-2015.05.29']
2015-06-12 17:16:28,724 DEBUG     curator.cli.index_selection                ind
ices:74   All filters: [{'pattern': '^.marvel.*$'}, {'method': 'older_than', 'ti
me_unit': 'days', 'value': 7, 'groupname': 'date', 'pattern': '(?P<date>\\m\\.\\
d)', 'timestring': 'm.d'}]
2015-06-12 17:16:28,724 DEBUG     curator.cli.index_selection                ind
ices:79   Filter: {'pattern': '^.marvel.*$'}
2015-06-12 17:16:28,724 DEBUG     curator.cli.index_selection                ind
ices:79   Filter: {'method': 'older_than', 'time_unit': 'days', 'value': 7, 'gro
upname': 'date', 'pattern': '(?P<date>\\m\\.\\d)', 'timestring': 'm.d'}
2015-06-12 17:16:28,724 WARNING   curator.cli.index_selection                ind
ices:136  No indices matched provided args: {'older_than': 7, 'time_unit': 'days
', 'exclude': (), 'index': (), 'prefix': '.marvel', 'suffix': None, 'all_indices
': False, 'regex': None, 'timestring': 'm.d', 'newer_than': None}
No indices matched provided args.

C:\Python34\Scripts>pause
Press any key to continue . . .

**Comment by untergeek** [comment]
Hmmm.  It appears that there's something wrong with the regular expressions:

```
170 REGEX = ^.marvel.$
```

That regular expression should be:

```
170 REGEX = ^.marvel.*$
```

The regex is also completely wrong with the time string: `170 REGEX = (?P\m.\d)`.  Those should have been interpolated to numerics!

Is this just a case of special characters failing to be read properly? I have no explanation as to why it is failing for you.  When I run this test on my windows machine with Python 3.4, it works just fine.  I run Curator in a plain CMD window, no batch files or power shell. 

To rule out your python install, you may want to try using [this pre-built package](https://dl.dropboxusercontent.com/u/1085030/curator-3.1.0-win-py27-amd64.zip) for 64-bit Windows (do NOT install it in your python directory or it may not work--this has been repeatedly observed).

**Comment by untergeek** [comment]
The more I think about it, the more certain I am that executing curator from the batch file has something to do with it.  Try running manually from the CMD window and see if that works.

**Comment by marcotoma** [comment]
Ok, i tried to run it from the cmd and it works!! That's great..but... how can i schedule it now?
seems that if i launch it from a bat file, the timestring characters are not read correctly

**Comment by marcotoma** [comment]
OK finally i figured it out!! 
Escape needed.  In the .bat file this line of code works like a charm:
curator show indices  --time-unit days --timestring "%%Y.%%m.%%d" --prefix .marvel --older-than 15
