### ISSUE TITLE
Curator installation issue with RHEL 6.5

### ISSUE THREAD

**Issue by chris-david-taylor** [elastic/curator#408]
Hi,

I have a full ELK stack running on a RHEL 6.5 x-64 Virtual Machine (VMware).  I have elasticsearch-1.6.0 and python-2.6.6 installed.  There are no other caveats - the VM is a base template that we've used hundreds of times over, so there aren't any fundamental issues that we are aware off.  So, installation via pip fails:

pip install elasticsearch-curator
  Could not find a version that satisfies the requirement elasticsearch>=1.0.0,<2.0.0 (from elasticsearch-curator) (from versions: curator-3.0.2, curator-3.0.1, curator-0.6.0, curator-1.2.1, curator-0.6.2, curator-2.1.1, curator-1.2.2, curator-1.1.2, curator-2.0.0, curator-1.2.0, curator-2.0.1, curator-1.0.0, curator-0.6.1, curator-2.1.0, curator-3.1.0, curator-1.1.0, curator-2.0.2, curator-2.1.2, curator-1.1.3, curator-3.0.0, curator-3.0.3)
No distributions matching the version for elasticsearch>=1.0.0,<2.0.0 (from elasticsearch-curator)

I tried to install elasticsearch via pip on top of the RPM (just as experiment), and the following occured:

[root@logger elasticsearch]# curator --host 127.0.0.1 delete –older-than 90
Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch>=1.0.0,<2.0.0

Anyone have any suggestions or seen this before?

Cheers,
Chris.

**Comment by untergeek** [comment]
Yep!  See [this FAQ](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html) in the [official documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html).

Bottom line: RHEL ships with an _ancient_ (in computer terms) version of Python, and the setuptools package needs to be upgraded for the installation to work.  The [FAQ doc for this issue](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html) has all the details.

**Comment by chris-david-taylor** [comment]
Hi Untergeek,
Thanks for getting back to me so soon!  I'll spin up a free VM and post back how I get on.

Chris,

**Comment by chris-david-taylor** [comment]
Apologies for the delay getting back to you. Okay, indeed that was the solution to the problem.

Cheers,
Chris.
