### ISSUE TITLE
combining --older-than with --all-indices does not work as intended

### ISSUE THREAD

**Issue by TinLe** [elastic/curator#409]
This was an accident, but I stumbled onto the bug late last night.  Luckily it was a test server, so deleting all my indices doesn't bother me :-)

I found that using curator to delete indices, if I combined --older-than with -all-indices, there is no timer.  E.g. it starts deleting right away.   This may be working as intended, but I did not know this and have not seen it in the docs.   Also, the --older-than does not work correctly, since I wanted to delete everything older than 30 days.  In this case, the '--all-indices' override and just delete everything.

$ curator --version
curator, version 3.2.0.dev0

# no timer, it just starts deleting immediately
$ curator delete indices --older-than 30 --time-unit days --all-indices --timestring '%Y.%m.%d'
2015-06-19 08:14:06,737 INFO      Job starting: delete indices
2015-06-19 08:14:06,750 INFO      Matching all indices. Ignoring flags other than --exclude.
2015-06-19 08:14:06,750 INFO      Pruning Kibana-related indices to prevent accidental deletion.
2015-06-19 08:14:06,750 INFO      Deleting indices as a batch operation:
2015-06-19 08:14:06,750 INFO      ---deleting index logstash-2015.06.14
2015-06-19 08:14:06,750 INFO      ---deleting index logstash-2015.06.15
2015-06-19 08:14:06,751 INFO      ---deleting index logstash-2015.06.16
2015-06-19 08:14:06,751 INFO      ---deleting index logstash-2015.06.17
2015-06-19 08:14:06,751 INFO      ---deleting index logstash-2015.06.18
2015-06-19 08:14:06,751 INFO      ---deleting index logstash-2015.06.19
2015-06-19 08:14:06,751 INFO      ---deleting index maillog-2015.06.19
2015-06-19 08:14:06,751 INFO      ---deleting index nginx-2015.06.19
2015-06-19 08:14:07,051 INFO      Job completed successfully.

# not using --older-than will trigger timer, but I wanted to delete everything older than 30 days
$ curator delete indices --all-indices --timestring '%Y.%m.%d'
2015-06-19 08:14:00,559 INFO      Job starting: delete indices
2015-06-19 08:14:00,618 INFO      Matching all indices. Ignoring flags other than --exclude.
2015-06-19 08:14:00,618 INFO      Pruning Kibana-related indices to prevent accidental deletion.
You are using --timestring without --older-than or --newer-than.
This could result in actions being performed on all indices matching %Y.%m.%d
Press CTRL-C to exit Curator before the timer expires:
10 9 8 ^C

**Comment by untergeek** [comment]
This is the expected behavior.  The countdown only happens if you specify `--timestring` _without_ other time-identifying flags.  See #348 and #349 for more information.  This edge case is documented [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/timestring.html):

> Starting in v3.1.0, if you specify `--timestring` without `--older-than` or `--newer-than`, the process will continue, but with a message warning you that the operation will delete all indices with a time string, followed by a 10 second countdown timer, which provides the opportunity to cancel the operation.

**Comment by TinLe** [comment]
Sure.  But notice that that older-than is not working.   I wanted to delete all indices older than 30 days.   It deletes everything.

So my question is:  Is this expected?   Eg "--older-than" does not work with "--all-indices" and I'd have to use regex to delete all indices older than 30 days for example.

**Comment by untergeek** [comment]
I didn't realize you were addressing another issue.  The `--all-indices` flag supersedes all other flags.  It will _always_ return all indices.  You can only use the `--exclude` flag to remove things from an `--all-indices` list.  See [the `--all-indices` documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/all-indices.html)

**Comment by TinLe** [comment]
OK.  That answers my question then.  Thank you.

I'll have to play with the flags.  I wanted to delete all indices older than certain number of dates, but there maybe other conditions.   I guess I can use regex in combination with other flags.

**Comment by untergeek** [comment]
To address this question:

> So my question is: Is this expected? Eg "--older-than" does not work with "--all-indices" and I'd have to use regex to delete all indices older than 30 days for example.

The answer is still with [the `--timestring` flag documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/timestring.html#_flags_19):

```
curator delete indices --timestring '%Y.%m.%d'
2015-06-19 09:54:53,728 INFO      Job starting: delete indices
2015-06-19 09:54:53,740 INFO      Pruning Kibana-related indices to prevent accidental deletion.
You are using --timestring without --older-than or --newer-than.
This could result in actions being performed on all indices matching %Y.%m.%d
Press CTRL-C to exit Curator before the timer expires:
10 ^C
Aborted!
```

In your above example, using the `--timestring` flag triggered the countdown, even if it erroneously was going to select all indices.  Regexes are implied.  Using `--timestring %Y.%m.%d` will match _all_ indices that match that time pattern, which in my case would be all `logstash-YYYY.MM.dd` and `.marvel-YYYY.MM.dd` indices.

**Comment by untergeek** [comment]
Delete indices older than 30 days that have a `%Y.%m.%d` pattern:

```
curator delete indices --timestring %Y.%m.%d --older-than 30 --time-unit days
```

**Comment by untergeek** [comment]
Omitting `--prefix`, `--suffix`, or `--regex` will simply match on the pattern provided, which in this case would be (not a real regex): `^.*[date pattern].*$`

**Comment by TinLe** [comment]
Ooooh.... d'oh! :-)

It's a... little bit confusing.   Thank you for the explanation.   To be honest, I was surprised when it started deleting all my indices late last night.   Just glad I was on my test server.

**Comment by untergeek** [comment]
It is a bit confusing.  The filters are just regexes. They're built in this method: https://github.com/elastic/curator/blob/master/curator/api/filter.py#L29-L89

The `--all-indices` behavior is here: https://github.com/elastic/curator/blob/master/curator/api/filter.py#L29-L89

As mentioned, it simply ignores all other flags.  You can see that the `--exclude` option is applied later.

**Comment by untergeek** [comment]
Each filter you use, `--prefix`, `--suffix`, etc. is applied iteratively to the list of indices, the results being used for the next filter iteration.

For example, if I have a `--prefix`, one of the filters (which is a list of regexes) will be `^prefix.*`
If I have a `--suffix`, one of the filters will be `^.*suffix$`
