### ISSUE TITLE
More utility support for aliases

### ISSUE THREAD

**Issue by t-pascal** [elastic/curator#415]
I several use cases that seem easy but aren't available yet. I have considered writing the code but don't have it formalised yet. These are just rough ideas that I'm sketching out. My use case is to curate an index based on age, how many are present, *and if it is part of an alias or not*.

(see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#alias-retrieving)

1. What aliases are currently applied to this index?

get_aliases_by_index(index or filter)

2. Which aliases currently exist? 

get_aliases(some_filter)

3. Which indices are in this alias?

get_indices_by_alias(alias or alias filter)

3. Does this index have this alias?

index_has_alias(index,alias)

**Comment by untergeek** [comment]
Thanks for being willing to contribute to Curator! I'd be more than happy to merge any additional utility methods you add to the API.

My expectations are:
* The methods are well annotated/documented following the existing pattern.
* Lots of unit tests (they'll need to pass both python2 and python3).  If you need help writing tests, please ask.
* Add the methods to the API documentation (again, if you annotate/document the methods well, this is as simple as following the pattern in the docs, they'll self-build).
* Add yourself to the CONTRIBUTORS file.
* Sign the [contributor agreement](http://www.elasticsearch.org/contributor-agreement/) — No merging will happen without this step.

**Comment by t-pascal** [comment]
My use case for this has gone away, so I won't be actively developing it. :)
