### ISSUE TITLE
Curator should have a silent mode

### ISSUE THREAD

**Issue by mjs510** [elastic/curator#428]
When running curator as a cron job, it should be possible to have it produce nothing to stdout in normal operation. However, a command such as the following will cause the following output:

`root@server:~# curator --logfile /tmp/curator.log --loglevel ERROR delete indices --prefix logstash- --older-than 30 --time-unit days --timestring %Y.%m.%d`
**No indices matched provided args.**

There should be a --quiet option or similar.

**Comment by untergeek** [comment]
That's not a bad idea.  I will not likely implement it before 4.0, however.  In the meantime, it's super-trivial to add `&> /dev/null` to the end of a cron job.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
