### ISSUE TITLE
When using logstash log format, all output should respect that

### ISSUE THREAD

**Issue by delfuego** [elastic/curator#438]
Currently, there appears to be output that doesn't respect `--logformat logstash` — for example, if I run:

`curator --logformat logstash delete indices --older-than 10 --time-unit days --timestring %Y.%m.%d`

and there aren't any indices older than 10 days, I get the "Job starting" and then the "No indices matched provided args" lines output in properly-formatted logstash JSON, but then I get the "No indices matched provided args" output AGAIN as plain text.

This means that if I pipe the curator output to logstash, the JSON-formatted lines get consumed properly, but the plain-text one causes logstash to hiccup and report a JSON parse failure.

**Comment by untergeek** [comment]
I will chalk this up to another vote for #428 

I will silence non-log output if `--quiet` is provided.

**Comment by untergeek** [comment]
And/or force `--quiet` mode if `--logformat` is set to logstash.

**Comment by delfuego** [comment]
That sounds great... but just to make sure I understand, the logstash-JSON-formatted output will still occur, yes? (I'm not logging to a file, I'm logging to stdout, and piping it to an `nc` connection to logstash's TCP input... so I still need stdout output, just not non-logstash-formatted output.)

**Comment by untergeek** [comment]
Yes.  It will only silence places in the code where the Click API is used to output directly to the console (so you'd see those messages even if you were logging to a file).
