### ISSUE TITLE
Allocation enable/disable

### ISSUE THREAD

**Issue by gquintana** [elastic/curator#446]
Using Cluster Settings cluster.routing.allocation.enable to enable/disable shard allocation.
This is needed to automate node/cluster/rolling restarts

This could handle shard allocation filtering as well cluster.routing.allocation.include.xxx cluster.routing.allocation.exclude.xxx to automate node removal

**Comment by untergeek** [comment]
I suppose I could add this.  It's a lot of work for a binary feature, though, because it will result in some API changes (which means it will not make it in until Curator 4.0 at the earliest).

In the meantime, I simply have 2 shell scripts for this:

## Disable allocation
```bash
#!/bin/bash

curl -XPUT localhost:9200/_cluster/settings -d '{
  "transient" : {
    "cluster.routing.allocation.enable" : "none"
  }
}'
echo
/usr/local/bin/curator --loglevel ERROR seal indices --all-indices
```

## Enable allocation (after restart)
```bash
#!/bin/bash

curl -XPUT localhost:9200/_cluster/settings -d '{
  "transient" : {
    "cluster.routing.allocation.enable" : "all"
  }
}'
```

**Comment by untergeek** [comment]
This will require a different approach now with 4.0, but it may be of some benefit between some actions.  I'll see if I can add this as an action to 4.0 now that an alpha is out.

**Comment by untergeek** [comment]
This feature makes no sense in the current incarnation of Curator.  It may be resurrected when I re-add the command-line tools (as separate scripts) in the future.  Re-flagging as on_hold.

**Comment by untergeek** [comment]
This actually does make sense to me now.  As a simple, filterless action, this works to disable allocation before something happens, and then re-enable after another action is completed.
