### ISSUE TITLE
[Feature] Allow filtering by index creation date

### ISSUE THREAD

**Issue by untergeek** [elastic/curator#451]
This may work in a large number of cases.  

In some use cases people will be ingesting older data, hence the need for index names based on content data.  But for many (perhaps most) users, indices are created within moments after the UTC rollover.  This provides an opportunity to avoid parsing index names for dates altogether.  Calculating cutoffs could be much easier, and even allow the dreaded `--disk-space` flag to sort exclusively by index creation date, which would fix some aspects of that use case when there are multiple index name patterns.

**Comment by imreFitos** [comment]
I have an alternate solution for this: specify sorting on character position of index name: https://github.com/elastic/curator/pull/517

**Comment by untergeek** [comment]
@imreFitos please see my comment on #517.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
