### ISSUE TITLE
show snapshots exit code

### ISSUE THREAD

**Issue by nik-petrov** [elastic/curator#452]
```
$ curator show snapshots --repository XXXXX --newer-than 4 --time-unit hours
2015-08-13 10:14:49,159 INFO      Job starting: show snapshots
2015-08-13 10:15:19,201 WARNING   No snapshots matched provided args.
ERROR. No snapshots matched provided args.
$ echo $?
0
```

It's ether and error or not an error and the exit code should reflect it.
Being a command line tool, it will be useful if no matched snapshot results in non-zero exit code.

**Comment by untergeek** [comment]
Thanks for the report.  This is indeed an oversight.

**Comment by nik-petrov** [comment]
I think "no match" is kind of a soft error. For instances in case of `curator delete` it's usually fine to ignore it. Probably use specific exit code for "no match" errors.

**Comment by untergeek** [comment]
I tried that.  I got well-reasoned pushback in #371 so I am only using 0 and 1 for the most part.
