### ISSUE TITLE
Missing dependencies for python-elasticsearch-curator-3.2.3-1

### ISSUE THREAD

**Issue by alexanderilyin** [elastic/curator#454]
After installing python-elasticsearch-curator via `yum`

```
python-elasticsearch-curator-3.2.3-1.noarch : Have indices in Elasticsearch? This is the tool for you!
Repo        : installed
Matched from:
Other       : Provides-match: /usr/bin/curator
```

I've found that it doesn't work.

```
$ sudo -u elasticsearch curator --host A.B.C.D delete indices --prefix logstash --older-than 3 --time-unit days --timestring '%Y.%m.%d'
Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Was fixed after this

```
sudo yum install python-pip
```

So it looks like python-setuptools was not installed with python-elasticsearch-curator.

```
$ cat /etc/redhat-release 
CentOS release 6.6 (Final)

$ uname -a
Linux kibana2 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/yum.repos.d/elasticsearch.repo 
[elasticsearch]
name=Elasticsearch repository for 1.4.x packages
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/GPG-KEY-elasticsearch
enabled=1
baseurl=http://packages.elasticsearch.org/elasticsearch/1.4/centos
humanname=Elasticsearch repository for 1.4.x packages

```

**Comment by untergeek** [comment]
Thanks for reporting your experience.  [The error and workaround are documented in the install documents](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html#_troubleshooting):

> There are some pitfalls you may encounter:
>
> * ImportError: No module named pkg_resources
>
> If you see this error:
>
>```
Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
>Then you will need to install python-setuptools (provided in the Curator repository):
>
>`yum install python-setuptools`
>
>The repository provides `python-setuptools-18.0.1-1.noarch.rpm`

**Comment by untergeek** [comment]
If there are no other comments, I will be closing this.

**Comment by sandwormusmc** [comment]
Why not add the dependency instead of rely on a workaround as a solution?

**Comment by untergeek** [comment]
Mostly because the workaround is for ancient versions of Python on CentOS/RedHat boxes.  Every other native distribution tends to have it.  I don't want to stomp on the shipped versions, so I do nothing here.

**Comment by sandwormusmc** [comment]
That makes sense.  I ran into this on a few CentOS 6.7 systems, so not terribly ancient in my case.

**Comment by untergeek** [comment]
Well, CentOS 6.7 isn't ancient, but the python version shipped with CentOS 5 and 6 is.  I believe it's because of a dependency issue related to how their package management works.  Upgrading python on those boxes is a no-no, though you may be able to run your own python3.

**Comment by sandwormusmc** [comment]
I see.  Good stuff, thanks for being so responsive.
