### ISSUE TITLE
Why curator delete index by --disk-space option which only take primary index repository size in account?

### ISSUE THREAD

**Issue by shanling2004** [elastic/curator#455]
During our production practice and source code confirm, we notice when curator delete index size-based, It only check primary_size for each index repository. However, the total disk cosumption per index should be primary_size * (replica_ratio +1) + <some_buffer_disk_comsuption>.

Shall we take replica ratio in account?

https://github.com/elastic/curator/blob/master/curator/api/filter.py#300

```   
def get_stat_list(stats):
       retval = list(
           (index_name, index_stats['index']['primary_size_in_bytes'])
            for (index_name, index_stats) in stats['indices'].items()
        )
        return retval
```

**Comment by untergeek** [comment]
Good observation!  I didn't write this code, but didn't think about it at the time I merged it.

By all means, submit a pull request and replace `primary_size_in_bytes` with `size_in_bytes`:

```
{u'size_in_bytes': 5722926301, u'primary_size_in_bytes': 2861508827}
```

It will give the total consumed by primary + all replicas.

**Comment by untergeek** [comment]
Had to put in a conditional.  `size_in_bytes` only appears if there are replicas.
