### ISSUE TITLE
Explanation of --newer-than

### ISSUE THREAD

**Issue by felipegs** [elastic/curator#461]
Hi,

The documentation of --newer-than flag is not clear to me.
I don't understand the meaning of it.
For example today is August 18.

I run the command:

```
curator show indices --timestring %Y%m%d --time-unit days --newer-than 0
events-20150821
events-20150822
events-20150823
events-20150824
```

```
curator show indices --timestring %Y%m%d --time-unit days --newer-than 1
events-20150820
events-20150821
events-20150822
events-20150823
events-20150824
```

```
curator show indices --timestring %Y%m%d --time-unit days --newer-than 2
events-20150819
events-20150820
events-20150821
events-20150822
events-20150823
events-20150824
```

**Comment by untergeek** [comment]
Perhaps adding the word, _ago,_ would help: `--newer-than` _n_ `--time-unit`'s _ago._  

It filters indices newer than _n_ days ago, and it uses UTC, so remember that date math in your calculations.  Also, it only does _full_ days, so that's probably partly why you are seeing some oddities.
