### ISSUE TITLE
Wrong type of parameter in apply_filter leads to an excpetion which is not well explained

### ISSUE THREAD

**Issue by o-r-r** [elastic/curator#465]
Using the python API, if I were to use the days ago parameter as my script parameter it can be passed as a string by mistake:   
 ```_filter = curator.build_filter(kindOf='newer_than', '3', time_unit='days',
                                   timestring='%Y%m%d')
curator.apply_filter(snapshots_list, **_filter)```

that would throw this excetion:
No handlers could be found for logger "curator.api.filter"
Traceback (most recent call last):
  File "/home/name/Programs/pycharm-community-4.5.3/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/name/Programs/pycharm-community-4.5.3/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/elasticsearch-delete-snapshot.py", line 63, in <module>
    main(sys.argv[1:])
  File "/elasticsearch-delete-snapshot.py", line 48, in main
    snapshots_to_delete_list = curator.apply_filter(snapshots_list, **_filter)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/filter.py", line 131, in apply_filter
    value=value, utc_now=utc_now,
  File "/usr/local/lib/python2.7/dist-packages/curator/api/filter.py", line 290, in timestamp_check
    if object_time < cutoff:

The issue is this call in filer.py line 281 that returns a boolean that can't be compared to the timestamp of an object:
```cutoff = get_cutoff(unit_count=value, time_unit=time_unit, utc_now=utc_now)```
TypeError: can't compare datetime.datetime to bool

I think there should be a more clear exception thrown in this case

**Comment by untergeek** [comment]
Rather than throw a more readable exception, perhaps we should just fix the casting of the variable?

**Comment by o-r-r** [comment]
I think trying to cast is very welcome, but then we will need to throw the readable exception when we weren't able to do the casting right?

**Comment by untergeek** [comment]
If we expect the variable to be sent as int, it will raise a different exception and not proceed with the method.

**Comment by untergeek** [comment]
We can try to cast if it fails the int type check, and hard-fail the method if it fails at that point.

**Comment by o-r-r** [comment]
Yes - that sounds good :)

**Comment by untergeek** [comment]
Actually, we only need to fix the casting.  You'll get a very different exception if the variable passed is not able to be cast.

**Comment by untergeek** [comment]
And it can only be cast in the `timestamp_check` method, as `value` can be non-integer in other places.

I'm fixing the casting of `disk_space` as well.

**Comment by untergeek** [comment]
*Sigh*

While all tests were passing on my machine, for some reason they stopped passing on our Jenkins setup.  Refactoring this change to hopefully patch Jenkins.
