### ISSUE TITLE
Improvements to log levels

### ISSUE THREAD

**Issue by seang-es** [elastic/curator#475]
We've gotten some customer reports on the latest Curator.  They were running an operation to close some indices and were a bit confused by the logs:

```
It's odd that it chooses to show indices that it is skipping, but not actually closing. 
Then there was the 'no indices to seal' warning message that doesn't seem to correlate to anything.

2015-09-01 06:07:09,305 INFO Job starting: close indices 
2015-09-01 06:07:09,459 WARNING Very large list of indices. Breaking it up into smaller chunks. 
2015-09-01 06:07:09,500 INFO Skipping index logstash-2014.08.21: Closed. 
2015-09-01 06:07:09,514 INFO Skipping index logstash-2014.08.22: Closed. 
2015-09-01 06:07:11,046 WARNING No indices to seal. 
...
2015-09-01 06:07:13,655 INFO Provided indices successfully sealed. (Shown with --debug flag enabled.) 
2015-09-01 06:07:16,079 INFO Job completed successfully.
```

The 'No indices to seal' error seems fine, though it might not be worth a WARNING level.  It is definitely odd that Curator is logging all the indices that are being skipped but not the ones that it seems to be closing.

**Comment by untergeek** [comment]
I put them in debug logging because the volume was quite long.  To turn on "debug" for Curator only (but not include all of the debug content of the `--debug` flag), you can set `--loglevel DEBUG`.

Again, I'm not opposed to bringing this back into INFO, but it can be a lot of spam to go through to find the ham.

**Comment by seang-es** [comment]
It just seems odd that the ones being skipped are INFO but the ones being acted on are DEBUG.  You would think action would lead to a log event, even a single line saying 'Closing index X', where a skip may not.  Does it make sense for the skips to be DEBUG as well?

**Comment by untergeek** [comment]
Probably.  I am disappointed that there's not anything between INFO and WARN.  I either have to throw everything in DEBUG, and little or nothing in INFO, or make more things WARN, which as you've noted, is not a great idea either.

**Comment by untergeek** [comment]
I think making the skips DEBUG makes sense.  I will definitely pursue that.

I will also re-introduce an INFO log line that shows every index that will be acted on.  Then any failures can be logged as WARN or ERROR.
