### ISSUE TITLE
[Feature] Filtering by "closed"

### ISSUE THREAD

**Issue by s12v** [elastic/curator#476]
I'd like to delete old closed indices. I can filter by time, by not by "closed" state. Couldn't find, how to do so. Is it possible? Would it make sense to have such a filter?

**Comment by untergeek** [comment]
It's an interesting idea.  But wouldn't other age-based criteria fit the requirement just as well, seeing as how "closed" are also likely older by the same, measurable index naming criteria?

I won't add the feature myself any time soon, as I have bigger fish to fry.  However, if you, or someone in the community were to add it, I would happily merge the feature.
