### ISSUE TITLE
Improvement: Curator should remind user to provide --timestring with --[older/newer]-than

### ISSUE THREAD

**Issue by rodriguezsergio** [elastic/curator#477]
So I was getting no results when running 
```
$ curator show snapshots --older-than 14 --time-unit days --repository  $s3-bucket
2015-09-10 12:28:05,539 INFO      Job starting: show snapshots
2015-09-10 12:28:06,869 WARNING   No snapshots matched provided args.
No snapshots matched provided args.
```
but then I came across this 
```The indices must also have a [timestring].```
https://github.com/elastic/curator/blob/887ef54f3c735c99793ec19a1cd6f20596dcb16a/docs/asciidoc/flags/older-than.asciidoc

In the case where a user does something as I did, or when they run `curator show snapshots --help` (or similar), there should be some helper text that using  `older/newer-than` requires a `timestring`.

**Comment by untergeek** [comment]
This may be the case if you created the snapshots with something other than Curator, and they have a timestamp in the name that differs from what Curator assigns by default.

You'll note that the `--timestring` definition for snapshots differs from the one for indices:

### Snapshots
The code which yields this is here: https://github.com/elastic/curator/blob/master/curator/cli/snapshot_selection.py#L24-L25
```
--timestring TEXT               Python strftime string to match your
                                  snapshot's definition, e.g. 20140715020304
                                  would be %Y%m%d%H%M%S
```


### Indices
The code which yields this is here: https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py#L23-L24
```
--timestring TEXT               Python strftime string to match your index
                                  definition, e.g. 2014.07.15 would be
                                  %Y.%m.%d
```

Note that there is a default value for snapshots, but no default for indices.  This is likely why you had no matches.  I don't think an update to the code is necessary here.  I _could_ add `show_default=True` to that line, to indicate that there is a default timestring, but that would make long output even longer.  Education and documentation are perhaps better solutions.

**Comment by rodriguezsergio** [comment]
Oh yeah... I should have mentioned that I created these snapshots just using the good ol' command line.

Feel free to close this.
