### ISSUE TITLE
ES2.0 support

### ISSUE THREAD

**Issue by imreACTmd** [elastic/curator#479]
Since ES2.0 beta is out, will you folks support it any time soon? check_version is hardcoded to stop at versions above 2.0.0

**Comment by untergeek** [comment]
There's a dependency on the elasticsearch-py module supporting 2.0.  As soon as that's available, I will start work on Curator 4.0-alpha.

**Comment by imreACTmd** [comment]
FYI: elasticsearch-py==1.7 is now out and Honza Kral says it's 2.0 compatible: https://github.com/elastic/elasticsearch-py/issues/271

**Comment by untergeek** [comment]
Tests are not yet passing.  It will be some time as I have more pressing matters to attend.

**Comment by untergeek** [comment]
Fixed in #488.  That was a lot of API crawling.
