### ISSUE TITLE
Add ssl support for es_repo_mgr 

### ISSUE THREAD

**Issue by ESamir** [elastic/curator#480]
When using SSL with es_repo_mgr we get the following error 

es_repo_mgr --host x.x.x.x --port 9200 --use_ssl --http_auth ***:*** create s3 --repository my_repo --bucket prod --region eu-west-1 --access_key *** --secret_key ***
2015-09-23 13:58:08,651 INFO Attempting to verify SSL certificate.
2015-09-23 13:58:08,652 WARNING Unable to verify SSL certificate.
/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:54: UserWarning: Connecting to x.x.x.x using SSL with verify_certs=False is insecure.
'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
ERROR: Connection failure.

Regards

**Comment by untergeek** [comment]
Add these options from Curator: https://github.com/elastic/curator/blob/master/curator/cli/cli.py#L37-L38

**Comment by markwalkom** [comment]
Also ran into this with a customer when trying to clean up some Marvel indices in a found cluster, replicated from my laptop on `3.0.3`;
```
$ curator --host CLUSTERID.found.io --port 9243 --use_ssl show indices --older-than 5 --time-unit days --timestring test-%Y.%m.%d
2015-10-07 18:20:27,387 INFO      Job starting: show indices
/Library/Python/2.7/site-packages/elasticsearch/connection/http_urllib3.py:50: UserWarning: Connecting to CLUSTERID.found.io using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
/Library/Python/2.7/site-packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-10-07 18:20:28,196 WARNING   No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'prefix': None, 'time_unit': 'days', 'timestring': u'test-%Y.%m.%d', 'exclude': (), 'older_than': 5, 'all_indices': False}
No indices matched provided args.
```

However if I check the HTTPS URL via browser or with openssl then it's fine.

**Comment by xh3b4sd** [comment]
I had the same issue and fixed it with the following.

```
pip install urllib3[secure]
```
