### ISSUE TITLE
Curator failing to remove an index from an alias 

### ISSUE THREAD

**Issue by ESamir** [elastic/curator#485]
Steps to reproduce 

You need install CURATOR 3.30 

Create an index
```
PUT /test_batch/test/1
{"name":"samir"}
```
add the index to the alias 

```
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : "test_batch", "alias" : "test_alias" } }
    ]
}
```
and use curator to remove the index from the alias 
```
sudo curator --debug --host 127.0.0.1 alias --name 'test_alias' --remove indices --prefix 'test_batch'
```
it will fail with the follwing error 

```
2015-10-06 18:32:03,830 DEBUG     urllib3.connectionpool          _make_request:387  "HEAD /test_alias/_alias HTTP/1.1" 404 0
```
https://guides.github.com/features/mastering-markdown/

When discussing with @untergeek , we found that the issue only happened when using urllib3 version 1.12 . If we use the version 1.11 it work fine.

**Comment by untergeek** [comment]
The urllib3 errors are a red herring.  The problem actually appears to be the fault of version 1.7.0 of the elasticsearch-py module.  1.7.0 is forward-looking to Elasticsearch 2.0, and it may be an incompatibility between versions.  I will, at some point, have to do some dependency refactoring.

You can verify you have version 1.7.0 by running:

```
$ pip list | grep elasticsearch
elasticsearch (1.7.0)
```

or you can test at the command-line:

```
$ python
>>> import elasticsearch
>>> elasticsearch.__version__
(1, 7, 0)
```

This can be addressed by running:

```
pip install -U elasticsearch==1.6.0
```

This command will uninstall version 1.7.0 of the elasticsearch-py module and replace it with version 1.6.0.
