### ISSUE TITLE
filter_by_space in filter.py should exclude .kibana index by default

### ISSUE THREAD

**Issue by mizeng** [elastic/curator#496]
Recently our curator delete .kibana (which is Kibana Dashboard configuration index) during size-based-rotation, and all the configuration data lost. 

I think "filter_by_space" should naturally exclude system index like .kibana by default to avoid this tragedy happen again.

**Comment by untergeek** [comment]
@mizeng if you are using Curator as it ships, it already does [automatically exclude all standard Kibana index types](https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py#L106-L120):

```python
    if ctx.parent.info_name == "delete": # Protect against accidental delete
        logger.info("Pruning Kibana-related indices to prevent accidental deletion.")
        working_list = prune_kibana(working_list)

    # If there are manually added indices, we will add them here
    working_list.extend(in_list(index, indices))

    if working_list and ctx.parent.info_name == 'delete':
        # If filter by disk space, filter the working_list by space:
        if ctx.parent.params['disk_space']:
            logger.info("Filtering to keep disk usage below {0} gigabytes".format(ctx.parent.params['disk_space']))
            working_list = filter_by_space(
                                client, working_list,
                                disk_space=ctx.parent.params['disk_space'],
                                reverse=ctx.parent.params['reverse']
                           )
```

The [`prune_kibana` method](https://github.com/elastic/curator/blob/master/curator/api/utils.py#L273-L286) is used to remove these indices from the working list before any action is taken.

If you are using the Curator API, you'd be correct.  `filter_by_space` does not, by itself, automatically prune Kibana indices.  It should be simple to add the `prune_kibana` method before or after running the `filter_by_space` method.

**NOTE:** If you are using an older version of Curator, the `filter_by_space` method was called differently and did not act as a special filter, but was called `delete_by_space`.  With one of these older versions, it may have been possible for Curator to have deleted a Kibana index in a delete-by-space operation.  You will automatically have this protection if you upgrade to the most recent version of Curator.

**Comment by mizeng** [comment]
@untergeek Thanks a lot for so detailed explanation.

I just checked, we're using "elasticsearch-curator==2.0.2" in "elasticsearch-1.5.2.deb". Seems need to upgrade elasticsearch-curator version.
