### ISSUE TITLE
Timezone support?

### ISSUE THREAD

**Issue by aochsner** [elastic/curator#505]
I searched the docs, github issues, and Google, and I couldn't find anything definitive.  Does curator assume indexes roll over at midnight UTC?  If so, is there a way to modify that?  I have indexes that rotate at midnight Mountain time (with all of the lovely DST issues so a simple offset isn't ideal).  It's not a tremendously huge deal because most of my curator usage occur when Mountain and UTC are on the same "date," but just want to understand my options here.

Thanks

**Comment by untergeek** [comment]
Yes, Curator assumes UTC.  There is not presently a setting which allows this to be tuned.  I'd be happy to merge a PR that adds this functionality, but it's not on my to-do list.

**Comment by untergeek** [comment]
Without changing anything, your best bet right now is to simply keep 1 more `--time-unit` of indices to prevent acting before the desired time frame.

**Comment by aochsner** [comment]
Thanks for the followup!  I'll likely just add a timeunit for the short term, but will try to dust off my Python skills and shoot you a PR.

**Comment by Geek2France** [comment]
I live in France (timezone GMT+1).
I want use curator to create weekly index mondays at midnight (when the week begins).

Curator fails because it considers the week is not yet finished and tells the index already exists.
Curator is used with crontab that use local time. So, why do you use UTC time ?

I would like understand. May be i misunderstood something.

**Comment by untergeek** [comment]
Everything Elasticsearch does with time is in UTC. Recalculation is done for display only, as in Kibana. 

I made Curator use UTC as well. The `creation_date` is in UTC, so for the sake of consistency, time strings are also treated the same.
