### ISSUE TITLE
Proxy support for Curator

### ISSUE THREAD

**Issue by imphasing** [elastic/curator#510]
It would be nice to be able to pass a proxy option to curator. This way I can have things network isolated like I want, and run Curator behind something I have to proxy into.

**Comment by untergeek** [comment]
I won't be adding this feature myself, but would be happy to merge it if someone else were to add it, with tests.

**Comment by untergeek** [comment]
@imphasing I've done a bit of digging.  It does not appear simple to add this, at first glance.

1. elasticsearch-py (the parent module Curator uses) does not have an out-of-the-box way to enable this.
2. There is [this](https://github.com/elastic/elasticsearch-py/issues/275), which gives a possible way to do proxying, but with the caveat that the proposed solution will not proxy HTTPS requests, which is explained in detail [here](https://lukasa.co.uk/2013/07/Python_Requests_And_Proxies/).

As a result, Curator will not likely be adding proxy support any time soon, as the burden of having to write tedious work-arounds that will not work with HTTPS is not something I want to tackle.  I'm going to close this for now, and reference it if the request comes up again.
