### ISSUE TITLE
Integrate Curator tests with our CI infra

### ISSUE THREAD

**Issue by joshuar** [elastic/curator#512]
Can we integrate Curator with the Elastic Jenkins instance so we are testing on all configurations we support?

**Comment by untergeek** [comment]
http://build-eu-00.elastic.co/job/es-curator_core/

It was in the past, but something broke.  They haven't fixed it since ES 2.0 was released.

**Comment by untergeek** [comment]
Raise an issue with @electrical and/or the infra team

**Comment by joshuar** [comment]
Done.
