### ISSUE TITLE
Curator with shield-enabled cluster - Password in clear text

### ISSUE THREAD

**Issue by ManjuNirmal** [elastic/curator#516]
The curator script for shield-enabled cluster exposes the admin password in clear text.

**Comment by untergeek** [comment]
This issue has been worked around in 3.5.x with the ability to use certificates for authentication, removing the need for passwords.  Please give that a try and let me know what you think.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
