### ISSUE TITLE
Error generating snapshot for one index

### ISSUE THREAD

**Issue by KunX** [elastic/curator#518]
I'm trying to generate an snapshot for one of my indexes for S3 archiving, but every single try resulted in an error:

```
# curator snapshot --repository anima-es-logarchive --name fortigate-2015.12.01 indices logstash-fortigate-2015.12.01
```

This command results on the error:

Error: Got unexpected extra argument (logstash-fortigate-2015.12.01)

I already tryed almost all options like and the only one that works is --all-indices

**Comment by corey-hammerton** [comment]
You need the ``--index`` argument BEFORE ``logstash-fortigate-2015.12.01``

**Comment by untergeek** [comment]
Thanks, @corey-hammerton.  @KunX, he is correct.  You do need to use the [`--index`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index_flag.html) flag to select individual indices.

**Comment by KunX** [comment]
Thank you guys for your help.
I guess I had some problem interpreting the documentation.
