### ISSUE TITLE
Curator is very slow on cluster with many indices

### ISSUE THREAD

**Issue by jnjackins** [elastic/curator#519]
We have a cluster with about 7000 indices, with new indices being created every day. We would like to run curator daily to assign indices to different nodes (SSD vs spinning disk), and adjust their replica settings, depending on the age of the index. However, when operating on a large number of indices (e.g. --older-than 90 days yields thousands of indices on our cluster), we find that curator spends a long time querying each individual index, checking it's status. Using --debug, I noticed that curator queries e.g. /_cat/indices/my-index-20151202?h=status&format=json for each index, which can 5 or even 10 seconds on our cluster. This means that a single execution can take 10 or more hours to complete, and we would like to run it more often than that.

Digging into the code, I've found this:

 ```python
    # This workaround using the _cat API is for AWS Elasticsearch, since it does
    # not allow users to poll the cluster state.  It may also be faster than
    # using the cluster state.
    if get_version(client) >= (1, 5, 0):
        indices = client.cat.indices(index=index_name, format='json', h='status')
        # This workaround is also for AWS, as the _cat API still returns text/plain
        # even with ``format='json'``.
        if not isinstance(indices, list):  # content-type: text/plain
            indices = json.loads(indices)
        (index_info,) = indices
        return index_info['status'] == 'close'
    else:
        index_metadata = client.cluster.state(
            index=index_name,
            metric='metadata',
        )
        return index_metadata['metadata']['indices'][index_name]['state'] == 'close'
```

I suppose this decision to query each index rather than using the cluster state is causing this slowness for us.

Is there a compromise that can be made, such as adding a --use-cluster-state (I'm sure a better name can be imagined) option?

Thanks.

**Comment by jnjackins** [comment]
Sorry, the above code snippet is from the index_closed function in api/utils.py.

**Comment by untergeek** [comment]
Sorry to keep you waiting for so long.
