### ISSUE TITLE
does curator support _ip=XXX for allocatin?

### ISSUE THREAD

**Issue by makeyang** [elastic/curator#526]
curator allocation --rule _ip=192.168.200.197 --type exclude  indices --all-indices

my comand dosen't work. so I wonder if curator  support _ip

**Comment by untergeek** [comment]
It does not.  The allocation rules, as presently coded, are based on tags only.  `_ip` is not recognized as a valid tag.  If you wanted to add this in, I'd merge it.  This is the first time this has been requested, so there doesn't appear to have been a high demand for it.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
