### ISSUE TITLE
curator complains about "Missing required parameter --repository" when "--repository" argument is specified

### ISSUE THREAD

**Issue by foresightyj** [elastic/curator#529]
I am using curator version:
    
    curator, version 3.4.0

This works:

    # curator --host localhost show snapshots --all-snapshots --repository fht360_backup
    2015-12-24 09:35:32,068 INFO      Job starting: show snapshots
    2015-12-24 09:35:32,087 ERROR     No snapshots found in Elasticsearch.
    No snapshots found in Elasticsearch.

But taking a snapshot shows me an error:

    # curator --host localhost snapshot indices --repository fht360_backup
    Usage: curator snapshot [OPTIONS] COMMAND [ARGS]...

      Take snapshots of indices (Backup)

    Options:
      --repository TEXT               Repository name.
      --name TEXT                     Override default name.
      --prefix TEXT                   Override default prefix.
      --wait_for_completion BOOLEAN   Wait for snapshot to complete before
                                      returning.  [default: True]
      --ignore_unavailable            Ignore unavailable shards/indices.
      --include_global_state BOOLEAN  Store cluster global state with snapshot.
                                      [default: True]
      --partial                       Do not fail if primary shard is unavailable.
      --request_timeout INTEGER       Allow this many seconds before the
                                      transaction times out.  [default: 21600]
      --skip-repo-validation          Skip repository access validation.
      --help                          Show this message and exit.

    Commands:
      indices  Index selection.
    2015-12-24 09:36:09,188 ERROR     Missing required parameter --repository
    Missing required parameter --repository

I cannot figure out where the mistake is in the command. Thanks for any hint!

**Comment by corey-hammerton** [comment]
The ``--repository`` flag must come BEFORE the ``indices`` keyword.

**Comment by foresightyj** [comment]
Indeed it works.
I patiently read the documentations and realized that the positions do matter. 
Thanks!
