### ISSUE TITLE
'allocation' returns failure when already optimized

### ISSUE THREAD

**Issue by maxvu** [elastic/curator#531]
I have a cron job that runs {delete, allocation, optimize} nightly and house it with a script that intercepts STDOUT and curator's return code in order to determine success of the run. I have some expectation of idempotence in these operations and so I use the same selection parameters each time.

In the case where an operation would be applied twice to the same criteria (e.g. right after), I notice that 'delete' will WARN (+msgout?) and return zero ("No indices matched provided args"), where 'allocation' will WARN and return one:

```
Running command: "/usr/local/mycorp/prod/local/python_2.6/bin/curator --host 'elasticsearch' --loglevel 'WARNING' --port '9200' --timeout '21600' allocation --rule 'tier=warm' indices --newer-than '30' --older-than '1' --time-unit 'days' --timestring '%Y.%m.%d'"
WARNING   Very large list of indices.  Breaking it up into smaller chunks.
WARNING   No indices to act on.
WARNING   No indices to act on.
WARNING   No indices to act on.
WARNING   Job did not complete successfully.
```

I understand that I should be using the API for my case and ought not to expect the CLI verbs to map to API functions directly, but should these be unified somehow? Is there a decision on what constitutes success?

**Comment by untergeek** [comment]
Yeah, I can fix that.  Sorry for the inconvenience.
