### ISSUE TITLE
--timestring flag supports only zero-padded decimal numbers

### ISSUE THREAD

**Issue by radap** [elastic/curator#532]
Hello,

In the documentation of --timestring there's a link to python strftime formatting (https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior), but it supports only zero-padded decimal numbers, so if I have index named with string like "listener-3-8-2015" the curator command:

curator --dry-run delete indices --timestring '%d-%m-%Y' --prefix 'listener-' --older-than 60 --time-unit 'days'

wont catch it...
It seems like it wont support the command:

 --timestring '%-d-%-m-%Y' 

as described in http://strftime.org/

**Comment by untergeek** [comment]
That is correct. Python strftime is not the same as strftime.org and requires zero padded days and months.   The linked documentation indicates that:

> '%d Day of the month as a zero-padded decimal number'

**Comment by radap** [comment]
Got it.

It is too bad that there is no support for this option.

**Comment by gfrankliu** [comment]
Can curator add support of non zero padded number? A new formatting function can be added in curator: http://stackoverflow.com/questions/9525944/python-datetime-formatting-without-zero-padding

**Comment by untergeek** [comment]
@gfrankliu This is not an easy task here, as it would involve a great deal of tokenizing and testing.  Instead, in Curator 4.0 (still not pushed to master) you can filter by age in 3 different ways:

1. By index name (which is the only way the current version of Curator works)
2. By index `creation_date`.  This is the timestamp of when the index was created.
3. By use of the `field_stats` API.  You use a timestamp field, and it can tell when the oldest and newest entries are in an index.

These are likely more desirable than hacking a way in to allow non-zero-padded strftime dates.

**Comment by gfrankliu** [comment]
@untergeek 4.0 filters look definitely better. Look forward to it.

**Comment by untergeek** [comment]
@gfrankliu https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/index.html

You can give the alpha release a try.  I'll be pushing out a8 in a little while (there's a forcemerge/optimize bug in a7 for ES versions < 5.0 that a8 fixes).
