### ISSUE TITLE
Index name issue with Curator 3.2.3

### ISSUE THREAD

**Issue by djnelson9715** [elastic/curator#533]
We have indices with this pattern of name  gbs.evenlogger.logstash-2016.01.04

When trying to run the following curator command
curator show indices --prefix gbs
returns no indices matched the provided args
curator show indices --all-indices
does not return any of the indices that have '.' in the index name.

It looks like curator is having an issue with indices that have a period in the index name.

**Comment by untergeek** [comment]
What happens if you run:

```
curator show indices --prefix 'gbs\.'
```

I'll add a test to the suite to see what happens with the long index name.

**Comment by djnelson9715** [comment]
It is returning No indices matched the provided args.

Same as before.

On Tue, Jan 5, 2016 at 11:02 AM, Aaron Mildenstein <notifications@github.com
> wrote:

> What happens if you run:
>
> curator show indices --prefix 'gbs\.'
>
> I'll add a test to the suite to see what happens with the long index name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/curator/issues/533#issuecomment-169062033>.
>



-- 
Doug Nelson

**Comment by untergeek** [comment]
Hmm.  I put the index with:

```
curl -XPUT localhost:9200/gbs.evenlogger.logstash-2016.01.04
```

And then when I ran curator (3.4.0) I saw this:

```
curator show indices --all-indices
2016-01-05 11:53:40,041 INFO      Job starting: show indices
2016-01-05 11:53:40,054 INFO      Matching all indices. Ignoring flags other than --exclude.
2016-01-05 11:53:40,054 INFO      Action show will be performed on the following indices: [u'.kibana', u'.marvel-es-2015.12.22', u'.marvel-es-2015.12.29', u'.marvel-es-2015.12.30', u'.marvel-es-2015.12.31', u'.marvel-es-2016.01.01', u'.marvel-es-2016.01.02', u'.marvel-es-2016.01.03', u'.marvel-es-2016.01.04', u'.marvel-es-2016.01.05', u'.marvel-es-data', u'.marvel-kibana', u'gbs.evenlogger.logstash-2016.01.04', u'logstash-2015.12.22', u'logstash-2015.12.29', u'logstash-2015.12.30', u'logstash-2015.12.31', u'logstash-2016.01.01', u'logstash-2016.01.02', u'logstash-2016.01.03', u'logstash-2016.01.04', u'logstash-2016.01.05', u'test_batch']
2016-01-05 11:53:40,054 INFO      Matching indices:
.kibana
.marvel-es-2015.12.22 (CLOSED)
.marvel-es-2015.12.29
.marvel-es-2015.12.30
.marvel-es-2015.12.31
.marvel-es-2016.01.01
.marvel-es-2016.01.02
.marvel-es-2016.01.03
.marvel-es-2016.01.04
.marvel-es-2016.01.05
.marvel-es-data
.marvel-kibana
gbs.evenlogger.logstash-2016.01.04
logstash-2015.12.22 (CLOSED)
logstash-2015.12.29
logstash-2015.12.30
logstash-2015.12.31
logstash-2016.01.01
logstash-2016.01.02
logstash-2016.01.03
logstash-2016.01.04
logstash-2016.01.05
test_batch
```

And when I run with `--prefix gbs` I see this:

```
curator show indices --prefix gbs
2016-01-05 11:55:45,999 INFO      Job starting: show indices
2016-01-05 11:55:46,013 INFO      Action show will be performed on the following indices: [u'gbs.evenlogger.logstash-2016.01.04']
2016-01-05 11:55:46,013 INFO      Matching indices:
gbs.evenlogger.logstash-2016.01.04
```

I'm not sure what the problem is for you.

**Comment by djnelson9715** [comment]
I noticed you are doing this in 3.4 curator and I am running 3.2.3 I wonder
if that could be the issue.  Looks like it is time to upgrade

On Tue, Jan 5, 2016 at 12:57 PM, Aaron Mildenstein <notifications@github.com
> wrote:

> Hmm. I put the index with:
>
> curl -XPUT localhost:9200/gbs.evenlogger.logstash-2016.01.04
>
> And then when I ran curator (3.4.0) I saw this:
>
> curator show indices --all-indices
> 2016-01-05 11:53:40,041 INFO      Job starting: show indices
> 2016-01-05 11:53:40,054 INFO      Matching all indices. Ignoring flags other than --exclude.
> 2016-01-05 11:53:40,054 INFO      Action show will be performed on the following indices: [u'.kibana', u'.marvel-es-2015.12.22', u'.marvel-es-2015.12.29', u'.marvel-es-2015.12.30', u'.marvel-es-2015.12.31', u'.marvel-es-2016.01.01', u'.marvel-es-2016.01.02', u'.marvel-es-2016.01.03', u'.marvel-es-2016.01.04', u'.marvel-es-2016.01.05', u'.marvel-es-data', u'.marvel-kibana', u'gbs.evenlogger.logstash-2016.01.04', u'logstash-2015.12.22', u'logstash-2015.12.29', u'logstash-2015.12.30', u'logstash-2015.12.31', u'logstash-2016.01.01', u'logstash-2016.01.02', u'logstash-2016.01.03', u'logstash-2016.01.04', u'logstash-2016.01.05', u'test_batch']
> 2016-01-05 11:53:40,054 INFO      Matching indices:
> .kibana
> .marvel-es-2015.12.22 (CLOSED)
> .marvel-es-2015.12.29
> .marvel-es-2015.12.30
> .marvel-es-2015.12.31
> .marvel-es-2016.01.01
> .marvel-es-2016.01.02
> .marvel-es-2016.01.03
> .marvel-es-2016.01.04
> .marvel-es-2016.01.05
> .marvel-es-data
> .marvel-kibana
> gbs.evenlogger.logstash-2016.01.04
> logstash-2015.12.22 (CLOSED)
> logstash-2015.12.29
> logstash-2015.12.30
> logstash-2015.12.31
> logstash-2016.01.01
> logstash-2016.01.02
> logstash-2016.01.03
> logstash-2016.01.04
> logstash-2016.01.05
> test_batch
>
> And when I run with --prefix gbs I see this:
>
> curator show indices --prefix gbs
> 2016-01-05 11:55:45,999 INFO      Job starting: show indices
> 2016-01-05 11:55:46,013 INFO      Action show will be performed on the following indices: [u'gbs.evenlogger.logstash-2016.01.04']
> 2016-01-05 11:55:46,013 INFO      Matching indices:
> gbs.evenlogger.logstash-2016.01.04
>
> I'm not sure what the problem is for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/curator/issues/533#issuecomment-169097116>.
>



-- 
Doug Nelson

**Comment by untergeek** [comment]
To test with 3.2.3, I had to install an older Elasticsearch instance:

```
» curator --version
curator, version 3.2.3
```
```
» curator show indices --all-indices
2016-01-05 12:10:12,583 INFO      Job starting: show indices
2016-01-05 12:10:12,592 INFO      Matching all indices. Ignoring flags other than --exclude.
2016-01-05 12:10:12,592 INFO      Matching indices:
gbs.evenlogger.logstash-2016.01.04
```
```
» curator show indices --prefix gbs
2016-01-05 12:10:18,670 INFO      Job starting: show indices
2016-01-05 12:10:18,681 INFO      Matching indices:
gbs.evenlogger.logstash-2016.01.04
```

It seems to be working with 3.2.3 and Elasticsearch 1.7 also.

What does your environment look like?  OS and version? Python version? Elasticsearch version?

**Comment by djnelson9715** [comment]
Figured it out.  We have shield installed and I was not using the correct
account which has access to these indices.

Thanks for all the help.  Should have thought to check that first.

On Tue, Jan 5, 2016 at 1:12 PM, Aaron Mildenstein <notifications@github.com>
wrote:

> To test with 3.2.3, I had to install an older Elasticsearch instance:
>
> » curator --version
> curator, version 3.2.3
>
> » curator show indices --all-indices
> 2016-01-05 12:10:12,583 INFO      Job starting: show indices
> 2016-01-05 12:10:12,592 INFO      Matching all indices. Ignoring flags other than --exclude.
> 2016-01-05 12:10:12,592 INFO      Matching indices:
> gbs.evenlogger.logstash-2016.01.04
>
> » curator show indices --prefix gbs
> 2016-01-05 12:10:18,670 INFO      Job starting: show indices
> 2016-01-05 12:10:18,681 INFO      Matching indices:
> gbs.evenlogger.logstash-2016.01.04
>
> It seems to be working with 3.2.3 and Elasticsearch 1.7 also.
>
> What does your environment look like? OS and version? Python version?
> Elasticsearch version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/curator/issues/533#issuecomment-169100888>.
>



-- 
Doug Nelson

**Comment by untergeek** [comment]
Glad it was a simple fix!

**Comment by bhellsun** [comment]
hello @djnelson9715 
Can you tell me how you solved the problem. Even I have shield installed.
And when I give a command like
"curator show indices --all-indices"
it throws an error
"""
2016-02-27 10:58:10,645 INFO      Job starting: show indices
2016-02-27 10:58:10,654 ERROR     Connection failure.
"""

**Comment by untergeek** [comment]
I would start by upgrading to 3.4.1

**Comment by bhellsun** [comment]
@untergeek 
I am already using curator 3.4.1 version

- Should I give any OPTION when giving the command "curator show indices --all-indices"
- because when giving curl command you have to give the option "curl -XPOST -u <username>" if you have shield installed. similarly do we have to give any option when using curator.
