### ISSUE TITLE
Run curator where the http enabled param is false

### ISSUE THREAD

**Issue by panda87** [elastic/curator#542]
Hi

I have a situation that I built new cluster with 3 data (master) nodes + 2 client nodes.
On the data nodes I set http.enabled to be false, so only the client nodes will receive external traffic.
Before I set the http.enabled to be false in the data nodes I used the --master only param and installed curator in all the data instances.

Now when I can't run the curator local on the data nodes since port 9200 is closed, where can I run the curator commands to avoid duplicates in the commands?

Thanks.
D.

**Comment by untergeek** [comment]
Hmmm.  That kind of paints you into a corner.

Curator requires http access as it is API-driven.  It does not need to be run only on the masters, or anything like that.  It only needs to run against a single client, which can be any node at all, provided you haven't disabled http access.

I would simply run it against one of the clients (removing the `--master-only` option) and monitor the exit code so you can tell it ran successfully each day.

**Comment by panda87** [comment]
I wanted to achieve sort of HA in the curator commands, so if one instance will be down the second will run the commands.
But, I understand I will have to change my design to not loose the curator automation commands.

Thanks @untergeek

**Comment by untergeek** [comment]
@panda87 Understood.  Rather than set http.enabled to false, perhaps you could set it to only listen on 127.0.0.1.  In that way, nothing external could query the masters, but a localhost API call, like Curator, would work.

**Comment by panda87** [comment]
@untergeek this is exactly the idea I thought about :)
