### ISSUE TITLE
Support for deleting old snapshots

### ISSUE THREAD

**Issue by rhoml** [elastic/curator#543]
At the moment I have two cronjobs to manage ES snapshots, one for creating the snapshot, and the second one for deleting snapshots older than X days. 

It would be nice if curator allowed us to keep the most recent X snapshots

**Comment by untergeek** [comment]
That's one thing snapshots actually make easier: sorting by date. They have an epoch timestamp that curator uses for this. While not impossible, it's more work to add this, and more flags to manage. I'll add the adopt me tag for now.

**Comment by rhoml** [comment]
Sweet! thanks :D

**Comment by untergeek** [comment]
Closing in favor of #649, which will add filter by count.
