### ISSUE TITLE
AWS ES indices removal via CLI

### ISSUE THREAD

**Issue by HenryCook** [elastic/curator#546]
I'm looking to utilise curator via the CLI to remove old indices from our new AWS ES cluster however I'm struggling to get it to work together.

We currently are utilising curator for our production Elasticsearch cluster which is working fine. I can see that work has been done to make [curator compatible](https://github.com/elastic/curator/issues/491) with the new AWS ES service.

Sorry if this is common knowledge or already been asked, as I'm struggling to see if this has already been done using the CLI. Failing that, would using the API be favourable?

**Comment by untergeek** [comment]
The CLI works with AWS ES.  Just be sure to use v3.4.0

**Comment by HenryCook** [comment]
Thanks for the quick response! 

I've now got it working after realising I hadn't specified the port or for it to use https.

For anyone else who's experiencing the same issue, make sure to specify the options `--use_ssl` to use https and `--port 443` to use port 443 instead of the default 9200.
