### ISSUE TITLE
Create snapshot repository from curator

### ISSUE THREAD

**Issue by fiunchinho** [elastic/curator#550]
Curator API allows us to take and restore snapshots, but before we do it, we have to create an snapshot repository.

I just saw that you can use the es_repo_mgr script to create it, but this method is not available in the api, only for the cli version.

Is there any plans to add this feature to the API? Or is this not here by design?

Thank you!

**Comment by untergeek** [comment]
To the API?  The `es_repo_mgr` endpoint that comes with Curator does this, and there are a few modules in its code you'd be able to use, if you follow the code and use them.  Otherwise, it's not something I originally planned on adding.

**Comment by fiunchinho** [comment]
Sorry, I didn't make myself clear. I meant that I can't instantiate the curator object to create a snapshot repository. [The API has these methods available](https://curator.readthedocs.org/en/latest/#contents), but I miss that one in particular, since it's needed to create the repository to start creating snapshots.
I was using the curator object inside an Ansible module, that's why I need this method available. What would be the best option?

Thank you

**Comment by untergeek** [comment]
> I was using the curator object inside an Ansible module

I'm not trying to be dismissive, but I'm kind of surprised by this.  You are automating/scripting the creation of _repositories?_  This is something that happens regularly enough that you need to automate it?

I might be able to migrate that method into the API, but I'm not sure when I'll get to it.

**Comment by fiunchinho** [comment]
You make a total valid point. But we have several teams that want to create their own ELK infrastructure, and I wrote a small ansible module to do it. I did it without the curator API, but I was just wondering if there were any plans to add the method.
Thank you! :)

**Comment by untergeek** [comment]
Methods moved and documented :smile:

**Comment by untergeek** [comment]
@fiunchinho See the [updated docs](http://curator.readthedocs.org/en/v3.4.1/utilities.html#create-repo-body).

**Comment by fiunchinho** [comment]
Oh my! You are awesome, man. Thank you very much
