### ISSUE TITLE
Log exceptions

### ISSUE THREAD

**Issue by erik-stephens** [elastic/curator#551]
Took me a while to figure out why snapshotting stopped working.  I patched [these lines](https://github.com/elastic/curator/blob/976be3a8230eab595654f1c5017e4cca2c1f30d3/curator/api/snapshot.py#L63) to:

    except Exception as exc:
        logger.error('Failed to verify all nodes have repository access: %s', str(exc))

Not sure if prefer another way to log exceptions (eg logger.exception to show full traceback).  It should help us better understand the underlying cause:

    2016-01-28 18:16:54,863 ERROR     Failed to verify all nodes have repository access: TransportError(404, 'repository_missing_exception')

The above is not a curator problem - just wanted to show example.  Now to figure out how my repository definition was deleted...

**Comment by untergeek** [comment]
@erik-stephens I've had the same problem with my repository disappearing.  Thanks for the report. I'll add in some improved logging to cover this.
