### ISSUE TITLE
Add support for quarterly indicies in timestring date format

### ISSUE THREAD

**Issue by eladtamary** [elastic/curator#590]
Hi, 
Since python strftime formatting doesn't support quarter as part of the date format, it's currently not possible to delete indexes that are created quarterly (prefix_2015_4, prefix_2016_1, prefix_2016_2, ...).  
How can I use Curator to delete such indexes? 
Can you add support for mathematical calculations on the date format?

See:
https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

Thanks,
Elad

**Comment by untergeek** [comment]
I'm pretty bound by the strictures of Python's datetime and strftime implementations, so this isn't likely to happen.  However...

Curator 4.0 should address this concern by allowing you to identify index age by `field_stats` API and `creation_date`, and not just trying to extract a timestamp from the index name.

**Comment by untergeek** [comment]
Presuming this is closed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
