### ISSUE TITLE
Support multiple hosts

### ISSUE THREAD

**Issue by pricecarl** [elastic/curator#591]
Feature request 

Hey,

At the moment the flag --host only supports a single host meaning you have point curator at a single node in the cluster. However if that host goes down for whatever reason then you cant manage your indices.

I think it would be better to allow multiple hosts separated by a delimited so then the process can check each host until it finds one that works.

**Comment by untergeek** [comment]
This is unfortunately unsupportable in the 3.x branch of Curator.  I will see if I can get it to work in the 4.x dev branch I'm working on right now.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
