### ISSUE TITLE
Weekly Index based on ISOWeek

### ISSUE THREAD

**Issue by sundarv85** [elastic/curator#592]
Hello,

I’m having a weekly index xyz_2016_15 (15 is the ISO week 15). The below command does not set up this index into the alias correctly

`curator alias --name last_month indices --newer-than 1 --timestring '%Y_%W' --time-unit weeks --prefix xyz_`

When I change the option to `--newer-than 2`, then it works.

What is the defined behaviour for curator, when I use the command to setup alias based on ISOWeeks

We are using Golang's time package, in which the [ISOWeek](https://golang.org/pkg/time/#Time.ISOWeek) based on ISO8601 returns week ranges from `1 to 53`.

Python's [datetime](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior) describes `%W` to be from `00, 01, ..., 53`

**Comment by untergeek** [comment]
I'm pretty bound by the strictures of Python's datetime and strftime implementations. 

Curator 4.0 should address these by allowing you to identify index age by `field_stats` API and `creation_date`, and not just trying to extract a timestamp from the index name.

**Comment by untergeek** [comment]
Presuming this is closed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
