### ISSUE TITLE
Allocation/Replicas - Wait For Completion

### ISSUE THREAD

**Issue by corey-hammerton** [elastic/curator#600]
This question is more focused on the Allocation and Replicas actions, but is it possible to add an option to allow curator to wait for those actions to complete before proceeding to other actions?

For instance, in Allocation add a "wait_for_completion" flag that will run `self.client.cluster.health(level='indices', wait_for_relocating_shards=0)`. The same for Replicas to run `self.client.cluster.health(level='indices', wait_for_status='green')`

**Comment by untergeek** [comment]
Sounds reasonable.

**Comment by corey-hammerton** [comment]
The next question that would probably come up is when to call `self.client.cluster.health()` when configured?

Should it be after each allocation or replica change or after the entire loop is finished?

**Comment by untergeek** [comment]
The current behavior would automatically chunk lists into acceptable URL lengths:

```python
        self.loggit.info('Updating index setting {0}'.format(self.body))
        try:
            index_lists = chunk_index_list(self.index_list.indices)
            for l in index_lists:
                self.client.indices.put_settings(
                    index=to_csv(l), body=self.body
                )
```

As you can see, the current action is to act on a list of chunked lists.  I guess the question is whether it would be desirable to loop through the entire list one index at a time and pausing after each one, or in batches, and pause after each batch.  

Thoughts? @corey-hammerton what would you like to see here?

**Comment by corey-hammerton** [comment]
Now I understand it, I misinterpreted the code in `chunk_index_list`.

For simplicity's sake let's keep the batch changes and pause after each batch. The code for that could be as follows:

`
        self.loggit.info('Updating index setting {0}'.format(self.body))
        try:
            index_lists = chunk_index_list(self.index_list.indices)
            for l in index_lists:
                self.client.indices.put_settings(
                    index=to_csv(l), body=self.body
                )
                if self.wait_for_completion:
                    self.client.cluster.health(
                        index=to_csv(l),
                        wait_for_relocation_shards=0
                    )
`

**Comment by untergeek** [comment]
Yeah, the code wasn't a problem, but timeout becomes one, if you had a low default timeout value.

I've already updated the default options for each action to allow for "timeout_override", so actions like this will not timeout after 30 seconds.  My local test revealed that is a likely outcome, and not all actions should have high timeouts, so this was a stepping stone to being able to allow for this to "complete" before continuing.
