### ISSUE TITLE
YUM Repo -> Missing python-pyyaml Dependency

### ISSUE THREAD

**Issue by corey-hammerton** [elastic/curator#613]
I understand that curator 4.0.0 has not been fully released, but trying to install this using YUM resulted in a missing dependency for package python-pyyaml on a CentOS 6 node.

**Comment by untergeek** [comment]
Of course it did.  RHEL/Centos _never_ provide comprehensive python packages.

I'll make sure it gets added.  Thanks.

**Comment by untergeek** [comment]
I've updated the repositories with this.  4.0.0a9 is up now, too, though the docs won't catch up with it for another 20 minutes.
