### ISSUE TITLE
Encrypting Data as it's Backed Up to S3?

### ISSUE THREAD

**Issue by ninjada** [elastic/curator#617]
Hello,

Have had curator backing things up to s3 for almost 2 years but now going through some compliance revisions atm and investigating options for encrypting data.

Just doing some tests & not fully across S3 encryption atm, but wondering if anyones come across such a predicament and if it's possible for Curator to backup using the S3 Server Side Encryption options?

Cheers

**Comment by untergeek** [comment]
What do you mean?  Encryption of the data on the disk?  Encryption of the data as it's streaming to S3?

Curator talks to Elasticsearch via the https://github.com/elastic/elasticsearch-cloud-aws plugin.  If encryption is disk side, and Elasticsearch and the plugin both support it, then Curator will just make it work.  

Curator v4 experimentally allows request signing with AWS IAM credentials, if that's more of what you were asking.  See more here: https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/configfile.html

**Comment by ninjada** [comment]
I guess just making sure the connection for backing up to s3 is encrypted and also if there are any possibilities to use S3's server side encryption.

Again, I'm only beginning to explore options but with S3 you can encrypt the data server side using the --sse flag and specific encryption keys with the aws cli.

Just wondering if there's an equivalent option possible via Curator, specifying an encryption key for the data to be encrypted server side on S3?

**Comment by untergeek** [comment]
Thanks for the clarification.

It's important to note that Curator doesn't have any control over the S3 repository.  Curator sends API requests to Elasticsearch, and Elasticsearch does the snapshotting.  The AWS plugin documentation shows that an S3 repository _can_ support server side encryption: https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws-repository.html

You have to configure this on the Elasticsearch side of things, however.  Also, Curator cannot create an S3 repository with this option at present, but once the repository is created, it will snapshot to it through Elasticsearch's API as mentioned.  If I ever repackage the es_repo_mgr tool for use with Curator v4, I'll be sure to add support for this, but that tool is not being included at present.

**Comment by untergeek** [comment]
Closing since it can be completely handled on the Elasticsearch side with the linked settings.
