### ISSUE TITLE
Exclude alias

### ISSUE THREAD

**Issue by sebesvn** [elastic/curator#634]
Hi,
Is that in any way possible to perform a delete indices while excluding index that has a given alias name?
I couldn't find how to achieve that.
The `--exclude` do not recognize alias name.
Thanks

**Comment by untergeek** [comment]
Not presently, but that can be a feature request for the newer 4.x branch.

**Comment by sebesvn** [comment]
> Not presently, but that can be a feature request for the newer 4.x branch.

That would be very nice.
