### ISSUE TITLE
Timestring %Y.%m.%d does not contain time unit weeks

### ISSUE THREAD

**Issue by wkruse** [elastic/curator#636]
In `elasticsearch-curator:3.4.0` following was working:

```
curator --master-only delete indices --prefix logstash --time-unit weeks --older-than 4 --timestring '%%Y.%%m.%%d'
```

In `elasticsearch-curator:3.5.1` I am getting:

```
ERROR. Timestring %Y.%m.%d does not contain time unit weeks`
```
Both versions running Python 3.5.1.

Probably related to https://github.com/elastic/curator/issues/181

**Comment by untergeek** [comment]
Curator at one point did timestring/time-unit vetting, e.g. "If you say `--time-unit` is `weeks`, ensure that  timestring contains `%W`".  I think that got lost during the 3.x upgrade.  It was re-added after 3.4.0.

This is moot in Curator 4, because all timestamps are converted to epoch time.

**Comment by wkruse** [comment]
Ok, thanks for the info.
