### ISSUE TITLE
curator allocation indices stopped working properly

### ISSUE THREAD

**Issue by reqless** [elastic/curator#637]
I have a cronjob that runs daily that is supposed to move indices to 'warm' nodes. Here is the command ::

sudo curator --master-only --logfile /var/log/curator-hot-warm-migration.log allocation --rule box_type=warm indices --time-unit days --older-than 5 --timestring '\%Y.\%m.\%d'

If I run that manually, it says ::

No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': u'\\%Y.\\%m.\\%d', 'exclude': (), 'older_than': 5, 'all_indices': False}

I can remove the backslashes and apostrophes from the timestring part of the command, check the log file and it says ::

I check the log file and it says the following ::

2016-05-25 17:32:34,507 WARNING   Very large list of indices.  Breaking it up into smaller chunks.
2016-05-25 17:32:34,617 WARNING   No indices to act on.
2016-05-25 17:32:36,731 WARNING   No indices to act on.
2016-05-25 17:32:38,857 WARNING   No indices to act on.
2016-05-25 17:32:40,900 WARNING   No indices to act on.
2016-05-25 17:32:42,903 INFO      Job completed successfully.

However, the indices that should have been moved, were not.

**Comment by corey-hammerton** [comment]
The crontab treats '%' as a line terminator so they need to be escaped for the cronjob to work.

Can you also provide a sample list of the index names you are trying to move?

**Comment by reqless** [comment]
Hi Corey, it doesn't move the indices no matter if being ran from cronjobs or if I run it manually.

Samples of index names that aren't being moved ::

ad-app-integration-2016.05.10
ad-app-integration-2016.05.11
ad-app-pbm-2016.05.04
ad-app-pbm-2016.05.05
ad-app-services-2016.05.04
ad-app-services-2016.05.05

**Comment by corey-hammerton** [comment]
Can you run `curator show indices --time-unit days --older-than 5 --timestring '\%Y.\%m.\%d'`?
Could also try putting double-quotes around the timestring value.

**Comment by reqless** [comment]
I executed that and it did not find anything. However, when I executed and removed the apostrophes and backslashes, ie --timestring %Y.%m.%d , it did list a bunch of indices older than 5 days.

**Comment by corey-hammerton** [comment]
Try removing the quotes/apostrophes from your crontab.

**Comment by reqless** [comment]
Corey, as I stated in the original post, I have manually executed the command to move the indices older than 5 days (without the apostrophes, slashes, quotes, etc), yet it still does not move the indices.

**Comment by untergeek** [comment]
@reqless, the title suggest that it worked at one point, then stopped working.  Is this the case?

Also, which version of Curator are you running?  I don't see that information in any of the comments.

For troubleshooting, using the `--debug` flag will be useful, as will looking in the Elasticsearch logs to see if there are any errors or extra information stored there.

**Comment by untergeek** [comment]
@reqless I'd also be grateful if you'd dry this with Curator v4, to see if it still has the same problem.

**Comment by untergeek** [comment]
Closing for lack of follow-up.  If you feel this is in error, please feel free to re-open, or open another issue.
