### ISSUE TITLE
Please add language classifiers to indicate what version of Python this is compatible with

### ISSUE THREAD

**Issue by fgimian** [elastic/curator#640]
Hey there, hope you're doing well :smile: 

Can you please add language classifiers to `setup.py` to indicate what versions of Python curator is compatible with?

e.g.

```python
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Topic :: System :: Networking',
        'Topic :: System :: Networking :: Monitoring'
    ]
```

Cheers
Fotis

**Comment by untergeek** [comment]
It's not a bad idea.  Have you hit an error with a version it's not working with?  I mean, it should work with 2.6+, generally speaking.

**Comment by fgimian** [comment]
Hey @untergeek, we are about to deploy this tomorrow but it was hard to know what versions of Python are supported.

However, we have decided to use the YUM repos anyway and it is clear that our OS is supported which is great 😄 

Thanks
Fotis

**Comment by fgimian** [comment]
Thanks :smile:
