### ISSUE TITLE
RPM dependencies

### ISSUE THREAD

**Issue by benohara** [elastic/curator#641]
The python-setuptools in the repo looks like been changed to use python2.7 so no longer works on EL6 (which is what it was for according to the docs)

We'd previosuly installed all this fine, but it now wont install on EL6 as the dependancies cant be met

**Comment by untergeek** [comment]
Is this for the 3.x tree or the 4.x tree?

**Comment by benohara** [comment]
Thats was on the 3 tree, on the 4

pkg_resources.DistributionNotFound: The 'click>=3.3' distribution was not found and is required by elasticsearch-curator

looks like a package of the same release, version was made a couple of days apart, on depend on python <= 2.7, the other = 2.7 (on the 3 tree)

**Comment by benohara** [comment]
yum install python-click

and

pkg_resources.DistributionNotFound: The 'elasticsearch<5.1.0,>=2.3.0' distribution was not found and is required by elasticsearch-curator

but

yum info python-elasticsearch
Loaded plugins: rhnplugin
This system is receiving updates from RHN Classic or RHN Satellite.
Installed Packages
Name        : python-elasticsearch
Arch        : noarch
Version     : 2.3.0
Release     : 1
Size        : 441 k
Repo        : installed
From repo   : elasticsearch-curator-el6
Summary     : Official low-level client for Elasticsearch. Its goal is to provide
URL         : https://github.com/elastic/elasticsearch-py
License     : Apache-2.0
Description : Official low-level client for Elasticsearch. Its goal is to provide
            : common ground for all Elasticsearch-related code in Python; because of this it
            : tries to be opinion-free and very extendable.

this is el6.7

**Comment by untergeek** [comment]
This has been fixed on my test system, which is Centos 6.8:

```
CentOS release 6.8 (Final)
```

Python has done some odd things, so if you still have issues with setuptools being weird, you can also try 

```
sudo yum install python-distribute
```

which should install setuptools in a suitable version (I've included it in the repo).

The version of setuptools in the repository seems to work:

```
[vagrant@localhost ~]$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'20.3'
```

but I upgraded it anyway and put a 20.10 version in as well:

```
[vagrant@localhost ~]$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'20.10.1'
```

It appears to work with both Curator 3.5.1 and my patched version of Curator 4.0.0a9 (because the released version had a python6 incompatibility, which will be fixed in the a10 release).

**Comment by untergeek** [comment]
Would love to hear if the fixes I've put in work for you.  I fixed the 3.x and 4.x trees, and they seem to install properly on my clean vagrant instances.

**Comment by untergeek** [comment]
In the absence of further response, I'm going to close this.  If you believe it is closed in error, feel free to re-open, or open a new ticket.
