### ISSUE TITLE
Delete indices based on size and date. 

### ISSUE THREAD

**Issue by pavanraotk** [elastic/curator#645]
Hi guys,

I would like to know if it's possible to build a feature like this, slice indices/snapshots based on the size and date. 

For example, if size > 100GB and older than 30 days, delete indices.

Reason I ask, we plan to keep the size low and number of days reasonable, but if the logs do fill within a single day because of special reasons, we don't want to delete the content of the newly created indices as well, just because size is more.

Is this reasonable? Is this already implemented? If yes, can you please share since I did not find any  command that does this already.

Thanks,

**Comment by untergeek** [comment]
Currently, Curator 4 allows for this feature.  It is in alpha release right now.  I am working to get the first beta out this week, if all goes well.

Curator 4 documentation is at https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/index.html

Essentially, you'd add extra filters.  Filter stacking is not possible in Curator 3.x, but it is in 4.

Snapshots are not monitored by size in Curator, by the way.  Only indices.

**Comment by untergeek** [comment]
I should have said that Elasticsearch doesn't show how much space is consumed by snapshots.

See:

```
    {
      "snapshot": "marvel-20160513083214",
      "version_id": 2020199,
      "version": "2.2.1",
      "indices": [
        ".marvel-es-2016.05.08",
        ".marvel-es-2016.05.07",
        ".marvel-es-2016.05.09",
        ".marvel-es-2016.05.04",
        ".marvel-es-2016.05.03",
        ".marvel-es-2016.05.06",
        ".marvel-es-2016.05.05",
        ".marvel-es-2016.05.11",
        ".marvel-es-2016.05.10",
        ".marvel-es-2016.05.02",
        ".marvel-es-2016.05.01",
        ".marvel-es-2016.04.30"
      ],
      "state": "SUCCESS",
      "start_time": "2016-05-13T08:32:14.271Z",
      "start_time_in_millis": 1463128334271,
      "end_time": "2016-05-13T08:32:26.934Z",
      "end_time_in_millis": 1463128346934,
      "duration_in_millis": 12663,
      "failures": [],
      "shards": {
        "total": 12,
        "failed": 0,
        "successful": 12
      }
    },
```

**Comment by pavanraotk** [comment]
Thanks :). Would the elastic-search 2.2.0 still work with version 4 of curator, or would there be any version change in elastic search necessary

**Comment by untergeek** [comment]
Curator 4 will work with ES 2.x - 5.0

**Comment by pavanraotk** [comment]
Last query, you mean to say the extra filters would look something like this:
curator delete indices --older-than {{ delete_indices_after_in_days }} <AND --disk-space {disk_value}>  --time-unit days --timestring %Y.%m.%d --regex '^{{ elasticsearch_index_name }}'

< ---- > would be the content of the added new filter or we create an action file(even if it's a single action) https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/actionfile.html as mentioned here.

If it's the action file, say action.yaml, how do I run this action.yaml, curator action.yaml would work?

**Comment by untergeek** [comment]
See the sample action file configuration for a similar (if not identical) request in #611 

The 4.0 documentation explains [how to use the command-line](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/command-line.html).  You need to have a [configuration file](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/configfile.html) and an [action file](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/actionfile.html), as you pointed out.

**Comment by untergeek** [comment]
Since this functionality has already been added to 4.x, I'm closing this issue.
