### ISSUE TITLE
Curator and crontab not working

### ISSUE THREAD

**Issue by pierro42100** [elastic/curator#655]
Hi everyone ! 

I would like to delete all indices older than 14 days. The following curator command line works correctly.
`/usr/local/bin/curator --host localhost delete indices --older-than 14 --time-unit days --timestring '\%Y.\%m.\%d'`

Now I would like to do it every day, so I think crontab seems a good solution.
But unfortunatly it doesn't work...

Here is the line in the crontab file :
`# Curator Elasticsearch every day at 8 am.`

`00 8  * * * root /usr/local/bin/curator --logfile /tmp/curator.log --host localhost delete indices --older-than 14 --time-unit days --timestring '\%Y.\%m.\%d'`

As you can see, I use \% instead of %. 
I saw the following cron log : 
`(root) CMD (root /usr/local/bin/curator --logfile /tmp/curator.log --host localhost delete indices --older-than 14 --time-unit days --timestring '%Y.%m.%d')`

But the indices aren't deleted... Moreover the log file /tmp/curator.log isn't created.

Do you have any suggestion ?

Thx !

**Comment by untergeek** [comment]
What system are you running this on?  If your system is running systemd, try [this FAQ](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/escape-percent.html) answer about systemd.

Most of the time, I don't use Curator directly in cron.  I use a wrapper script, and call the script via cron.

**Comment by untergeek** [comment]
I should also mention that Curator v4 solves this by using configuration files instead of using lots of complicated, nested flags.  See https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/index.html

**Comment by pierro42100** [comment]
> I use a wrapper script, and call the script via cron.

Ok, I try to do something like that, but it's not working.
Can you give me an example ?

Thank you

**Comment by untergeek** [comment]
Sure:

In crontab: 

```
30 2 * * * /home/username/bin/curator.sh &> /dev/null
```

And `/home/username/bin/curator.sh` would be:

```
#!/bin/bash

/usr/local/bin/curator --logfile /tmp/curator.log --host localhost delete indices --older-than 14 --time-unit days --timestring %Y.%m.%d
```

Note that there is no need for the single quotes or escaping of percents in the shell script.

**Comment by untergeek** [comment]
I'm closing this since 4.0 resolves most—if not all—of the crontab issues by removing flags.  If you feel that more discussion is necessary, feel free to reopen the issue.
