### ISSUE TITLE
Curator should give you the option to change index settings (static and dynamic)

### ISSUE THREAD

**Issue by evanv** [elastic/curator#656]
Several months ago, Elastic introduced the ability to change the compression codex of an index (eg https://www.elastic.co/blog/store-compression-in-lucene-and-elasticsearch). Although the default compression settings can be specified on a per node level with `elasticsearch.yml`, it would be nice if Curator could also modify index settings like replica counts and compression codecs.

**Comment by untergeek** [comment]
Replica counts are already supported in the 3.x and 4.0 branches.  I will look into the others.

**Comment by evanv** [comment]
I'll clone and see what I can do as well. The compression settings would be a nice add imo. But then again maybe just moving the indices to "cold" nodes would work... might be overkill. Not sure.

**Comment by untergeek** [comment]
I think that changing compression settings for sure should be added.  It may require a forceMerge immediately after changing (if it isn't auto-triggered).

**Comment by evanv** [comment]
That's a good question. I know changing the allocation type doesn't trigger a force merge. I'll check compression settings in a moment. I should also have time to work on this later this week, if you need a hand with it.

**Comment by evanv** [comment]
Ah, bummer.  Gotta close the index first. 

```
curl -XPUT 'https://localhost:9200/prediction_index/_settings' -d '{"settings": {"index.codec": "best_compression" } }'

{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[localhost][localhost:9300][indices:admin/settings/update]"}],"type":"illegal_argument_exception","reason":"Can't update non dynamic settings[[index.codec]] for open indices [[prediction_index]]"},"status":400}%
```

**Comment by untergeek** [comment]
But with command chaining in Curator 4, you could close the indices, change compression, and then reopen by using the same filters. It can be done!

**Comment by evanv** [comment]
I was thinking the exact same thing (nice call on YAML/filter chaining by the way). Tomorrow's pretty busy. I should be able to work on this Thursday/Friday unless you beat me to it.

**Comment by untergeek** [comment]
I can guarantee you I won't likely be able to get to it before you, so I'll be happy to merge this in after you add it.

**Comment by mayoung8** [comment]
Is this still a targeted feature? I force merge my indices after one day as they are time based and would love to also compress them via curator if possible. I'd prefer not to have to compress the current days indices as they are very hot.

**Comment by untergeek** [comment]
It won't make it into 4, but probably will in a later 5.x release.
