### ISSUE TITLE
Logging to JSON the field @timestamp overwrites the indexed time when using the logstash json filter

### ISSUE THREAD

**Issue by ryancurrah** [elastic/curator#661]
Logging to JSON the field @timestamp overwrites the indexed time when using the logstash json filter. 

```
{"@timestamp": "2016-06-25T14:03:58.179Z", "function": "__not_actionable", "linenum": 39, "loglevel": "INFO", "message": "Index .marvel-es-1-2016.06.22 is not actionable, removing from list.", "name": "curator.indexlist"}
```

I've tried to use remove_field to prevent it from happening but all i get in logstash is...

```
LogStash::Error: Unable to format in string "YYYY.MM.dd", @timestamp field not found
```

This is my filter...

```
filter {
    if [type] == "elasticsearch-curator" {
        json {
            source => "message"
            remove_field => [ "@timestamp" ]
        }
        mutate {
            rename => { "loglevel" => "level" }
        }
    }
}
```

Would it be possible to not use use the special @timestamp as a field name for your logs? 

I beleive the line of code that would need to be changed is [here](https://github.com/elastic/curator/blob/161aa69323213f77bdf008518773dc6d7c81d1a1/curator/logtools.py#L21)

**Comment by untergeek** [comment]
The JSON output was designed to go straight into Logstash using the json_lines codec. It is supposed to provide the `@timestamp` field with the time the Curator event occurred. Why are you trying to remove/replace the event time?

**Comment by ryancurrah** [comment]
The timestamp's timezone produced by Curator (Great job on 4.0 btw) is in the CET timezone (Same as the server). When collecting logs using Filebeat (Which I assumed most users do) it expects the timestamp to be in UTC. So in Eleasticsearch the events are showing up 6 hours behind when they acutally happened. See Filebeat docs about @timestamp field [here](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-env.html#_timestamp). 

Thanks for the quick response!

**Comment by untergeek** [comment]
Ah. You should let Logstash overwrite the timestamp. If Curator isn't sending the correct ISO8601, then either the server isn't UTC with an offset, or I need to coerce the time properly.

**Comment by untergeek** [comment]
The Beats timestamp is _not_ the event timestamp.

**Comment by ryancurrah** [comment]
The servers timezone is set for CET. As for the beats timestamp i agree but filebeats input on logstash expects the @timstamp field to be in UTC. Curators @timestamp field needs to be UTC to or not use that field name. So when the json filter in logstash overwrites the filebeat field with curator field @timestamp there will be no issue.

**Comment by untergeek** [comment]
@ryancurrah Please see if you can patch/modify your existing Curator install with the changes in #662 

I'd be interested to know if that addresses your concerns.

**Comment by ryancurrah** [comment]
@untergeek wow that was fast. I'm AFK today I will give it a try first thing tomorrow, or tonight if I get a chance.

**Comment by ryancurrah** [comment]
@untergeek FYI i made some comments on your PR, thanks again!
