### ISSUE TITLE
Running snapshot action fails when using the snapshot.yml action example.

### ISSUE THREAD

**Issue by leonhoffman** [elastic/curator#663]
Run - 
curator --config /etc/curator/config/es-host.yml /etc/curator/actions/logstash_snapshot.yml

2016-06-28 11:42:55,842 INFO      Action #1: snapshot
2016-06-28 11:42:55,843 INFO      Starting new HTTP connection (1): es-host.body.stage
2016-06-28 11:42:55,851 INFO      GET http://es-host.body.stage:9200/ [status:200 request:0.008s]
2016-06-28 11:42:55,873 INFO      GET http://es-host.body.stage:9200/_all/_settings?expand_wildcards=open%2Cclosed [status:200 request:0.021s]
2016-06-28 11:42:55,960 INFO      GET http://es-host.body.stage:9200/_cluster/state/metadata

<REMOVED FOR BREVITY>

2016-06-28 11:42:55,985 ERROR     Failed to complete action: snapshot.  <type 'exceptions.KeyError'>: 'creation_date'

[logstash_snapshot.txt](https://github.com/elastic/curator/files/337662/logstash_snapshot.txt)
[es-host.txt](https://github.com/elastic/curator/files/337663/es-host.txt)

**Comment by corey-hammerton** [comment]
You need to fill out the `repository` option in your `logstash_snapshot.yml` file

**Comment by leonhoffman** [comment]
You are correct and that is a requirement, however that does not make any difference.  I removed the repo name from the file before I uploaded it.  I should have stated that.

**Comment by untergeek** [comment]
Can you paste the debug output instead, please?

**Comment by leonhoffman** [comment]
I am attaching it (output with the Debug flag on) since it is a bit of info to paste.
[output-with-debug.txt](https://github.com/elastic/curator/files/337692/output-with-debug.txt)

**Comment by untergeek** [comment]
Thanks.  I'm looking it over right now.

As an aside, I took your config files, exactly as they were and replaced only the host and repository name, and it worked flawlessly for me.  I'm still extracting the cluster state from the log file, but I'm guessing that the 'key error "creation_date"' bit is indicating something unusual in your index metadata.

**Comment by untergeek** [comment]
Yep:

```
>>> for idx in testinge.indices.keys():
...     try:
...         foo = testinge.indices[idx]['settings']['index']['creation_date']
...     except:
...         print('Index: {0} does not have a creation_date!'.format(idx))
...
Index: kibana-int-demo1 does not have a creation_date!
Index: .marvel-kibana does not have a creation_date!
Index: kibana-int does not have a creation_date!
```

This seems to indicate that these are _old_ indices and do not have a creation_date.  If you're not still using them, you can quickly get around this issue by deleting them.  `kibana-int` and `.marvel-kibana` are for pre-2.x versions of ES.  Since I can see in your log output, `Detected Elasticsearch version 2.3.2`, these can probably be safely deleted, unless you're still trying to make Kibana 3 work with this version of ES.

I will have to code a way to catch this, log it to death to ensure that the end user knows this is going on, and remove these indices from the actionable list (if creation_date is selected).

**Comment by leonhoffman** [comment]
Ok @untergeek  Thanks for digging into this: I thought for some reason that when you use the "pattern" filtertype that it would first just look at the value that I had listed then look at the creation_date in the age filter.  I wasn't aware that it would first retrieve all creation_data meta data, so I was just looking for the creation_date meta data for the index I had listed, and that threw me.

That makes sense though, Thank you!

**Comment by untergeek** [comment]
It pre-populates all of the values, yes.  I have a workaround that will skip these old messages with a warning. I will push a PR soon.

**Comment by untergeek** [comment]
By the way, `creation_date` was added in Elasticsearch v1.4, so those are pretty old indices.

**Comment by leonhoffman** [comment]
Yeah - those are - I deleted them
2016-06-28 13:02:11,137 INFO      Snapshot curator-20160628190210 successfully completed.

**Comment by untergeek** [comment]
Glad to hear it, @leonhoffman 

Thanks for the report!

**Comment by leonhoffman** [comment]
Thanks for your help.

**Comment by untergeek** [comment]
#664 should address this for future users.
