### ISSUE TITLE
Running restore action fails when using state filtertype in action yml file.

### ISSUE THREAD

**Issue by leonhoffman** [elastic/curator#665]
Running:
curator --config /etc/curator/config/rubber-licorice.yml /etc/curator/actions/restore_kibana_snapshot.yml

When using the 'state' filtertype the restore fails.  If I leave it out it is successful.  I'm attaching the yml and debug files.

Excluding this works:
- filtertype: state
      state: SUCCESS
      exclude:

2016-06-28 15:40:32,552 ERROR                curator.cli                    cli:242  Failed to complete action: restore.  <class 'curator.exceptions.ConfigurationError'>: Unrecognized filtertype: state

[restore_snapshot.txt](https://github.com/elastic/curator/files/338127/restore_snapshot.txt)
[rubber-licorice-yml.txt](https://github.com/elastic/curator/files/338126/rubber-licorice-yml.txt)
[restore_kibana_snapshot-yml.txt](https://github.com/elastic/curator/files/338125/restore_kibana_snapshot-yml.txt)

**Comment by untergeek** [comment]
Oooh.  That's an unfortunate one.  I'll have a fix for you in a second.

**Comment by untergeek** [comment]
Please see if you can add the line patched in #666 ( 😆 ) to your existing install and see if that covers the problem.

**Comment by leonhoffman** [comment]
Cool that's fixed.  Thanks
