### ISSUE TITLE
es_repo_mgr / curator cli?

### ISSUE THREAD

**Issue by morero** [elastic/curator#668]
Hi,

I'm upgrading a previous elasticsearch installation, that uses the es_repo_mgr to create repositories for backups.

It seems this tool is no longer available? I noticed the methods in the curator api, but not in the curator cli ool. 

What is the recommended replacement? Scripting against the api?

//Robin

**Comment by untergeek** [comment]
I am planning on re-bundling those separately in the future.  If scripting against the API is undesirable, I recommend installing the 3.x branch in a virtualenv if you still need it now:

```
(sudo) pip install virtualenv
```

Once this is installed:

1. `mkdir curator-3.5.1`
1. `cd curator-3.5.1`
1. `virtualenv venv`
1. `source venv/bin/activate`.  Your command-line prompt will be prepended with `(venv)` after this, to show you are in a virtual env.
1. `pip install elasticsearch-curator==3.5.1`
1. Test your work: `curator --version`
  
    ```
    curator, version 3.5.1
    ```

Any time you need this, you can `cd curator-3.5.1` and `source venv/bin/activate`, and curator 3.5.1 will be available in that directory.

You're really creating new repositories that frequently?

**Comment by morero** [comment]
Thanks! 

I'm not really creating them often. And it's not critical. Just wanted to automate the process (planned on a few test cases in a clean environment to verify my curator setup).
