### ISSUE TITLE
Snapshot action requires an IndexList

### ISSUE THREAD

**Issue by kylehendricks** [elastic/curator#672]
I am trying to do a nightly backup of daily log indices something like this:

```python
# Get a list of all indices except today's
indices_needing_snapshot = curator.IndexList(client)
indices_needing_snapshot.filter_by_age(timestring='%Y.%m.%d', direction='older', unit='days', unit_count=1)

# Get a list of all snapshots with this index prefix
snapshots = curator.SnapshotList(get_client(), repository=SNAPSHOT_REPOSITORY_NAME)
snapshots.empty_list_check()
snapshots.filter_by_regex(kind='prefix', value=index_prefix)
snapshots.filter_by_state(state="FAILED", exclude=True)

for index in indices_needing_snapshot.indices:
    if index not in snapshots.snapshots:
        snapshot_action = curator.actions.Snapshot(index,
                                                   repository=SNAPSHOT_REPOSITORY_NAME,
                                                   name=index,
                                                   include_global_state=False)
        snapshot_action.do_action()
```

Unfortunately the Snapshot constructor only takes an IndexList.  Am I missing something?  Is there a better way to do this?

**Comment by untergeek** [comment]
If I understand correctly, you're trying to remove indices from `indices_needing_snapshot` based on whether they are or are not in `snapshots.snapshots`?  And, based on your snapshot creation here, you're trying to create a snapshot _per_ index?

**Comment by untergeek** [comment]
I'm puzzled by the approach.  Why not snapshot all of the indices in one?  Retention?  Having multiple snapshots point to the same index does not duplicate data.  Snapshots work at the segment level, and any snapshot attempting to back up an already snapshotted segment will just point to it, so it's not duplicating data.  And when deleting snapshots, segments are only deleted when there are no more snapshots pointing to them.

**Comment by kylehendricks** [comment]
I just thought that the snapshot per index approach made more sense for my use case (logs).

2 reaons:
1.  Easier to move old snapshot data from AWS S3 storage to glacier storage.
2.  Easier to restore just a few days of logs from some point in the past.

I'm new to snapshotting with elasticsearch.  Is there a better way to do this?

**Comment by untergeek** [comment]
Please read [this comment from the past](https://github.com/elastic/curator/issues/174#issuecomment-57056621).  Curator used to do per-index snapshots, but it no longer does because it is inefficient to do so.  Please note, you can restore individual indices from any snapshot at any time.  It's super easy to do so.

**Comment by kylehendricks** [comment]
Thanks!  I didn't realize that.
