### ISSUE TITLE
Support for STS temporary credentials

### ISSUE THREAD

**Issue by joshuaspence** [elastic/curator#681]
Currently it is only possible to use hardcoded credentials for communicating with AWS Elasticsearch. It could be great if STS temporary credentials were supported as well. It seems that this functionality is only partially supported by `requests-aws4auth` (see sam-washington/requests-aws4auth#14).

**Comment by untergeek** [comment]
Unfortunately, I can't add a feature that I can't test myself.  This is further complicated by the words, "only partially supported."  That makes it difficult to schedule time to work out coding a way to make this work, only to find that it might not, or worse, doesn't work.

I've added the `adopt_me` label in case someone wants to take a stab at this.  Until it's officially supported by `requests-aws4auth`, I don't see myself adding it.

**Comment by joshuaspence** [comment]
Fair enough, thanks for the response.

**Comment by swladyka** [comment]
It is possible to use boto3 session for retrieving credentials (this is probably the most common way of injecting these), please see: https://github.com/sam-washington/requests-aws4auth/issues/14

That would enable option to use either STS temporary credentials or roles for signing. User credentials are obviously also possible with this approach.

The question is whether this could replace current config parameters, or these should remain?

**Comment by untergeek** [comment]
It would have to be in addition, otherwise it would break existing functionality. 

Also, someone else will have to add it, test it, and submit a PR. I haven't the means to test it myself.

**Comment by untergeek** [comment]
Moot as AWS Elasticsearch is no longer supported.
