### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/curator#686]
With Curator 4 out, and already 3 major versions of Elasticsearch in this world, i think that we need to add a compatibility matrix in the readme to make sure we state which product each version supports.

**Comment by gmoskovicz** [comment]
@untergeek What do you think?

**Comment by untergeek** [comment]
A pull request would be welcome, if you'd like to add it.

**Comment by untergeek** [comment]
It's pretty much:

Curator Version | ES 1.x | ES 2.x | ES 5.x
-------- | -------- | -------- | --------
**3** | yes | yes | no 
**4** | no | yes | yes
