### ISSUE TITLE
Broken import in 4.0.2?

### ISSUE THREAD

**Issue by mattdeboard** [elastic/curator#702]
In v4.0.2, [this line](https://github.com/elastic/curator/blob/master/curator/__init__.py#L2) throws an exception:

```pytb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4189b2456320> in <module>()
----> 1 import curator

/path/lib/python2.7/site-packages/curator/__init__.py in <module>()                                                                                   [1610/1957]      1 from .exceptions import *
----> 2 from .defaults import settings
      3 from .logtools import *
      4 from .utils import *
      5 from .indexlist import IndexList

ImportError: No module named defaults
```

I see that the `curator/defaults/` directory exists but for whatever reason the relative import isn't working.

For now we have reverted back to 4.0.1.

**Comment by untergeek** [comment]
Yeah, I caught this a few minutes before you reported it during release testing.  I've fixed it and 4.0.3 is already out on `pip`.

**Comment by untergeek** [comment]
It was a MANIFEST.in error.

**Comment by mattdeboard** [comment]
Alright. Well if nothing else it was a good punch in the mouth to remind us to pin our dependency versions. Hopefully future release testing will happen before the release goes out.

**Comment by mattdeboard** [comment]
And thanks for your work getting out a fix quickly.

**Comment by untergeek** [comment]
No problem.  Sorry for the trouble.  I caught it immediately when doing a `pip` sanity test after pushing the new version there.  That _was_ me doing a PyPI release test, as it passed all of the regular Travis CI testing already.  It was a packaging error that Travis did not catch.  I'll have to see if I can get that figured out for the future.

I'm actually surprised you caught it in the few minutes it was there after my test, but that's on me for not marking it unavailable on PyPI sooner.

**Comment by mattdeboard** [comment]
I would've reported it more quickly but our on-call guys are on airplanes, and it took awhile for me to get notified :)
