### ISSUE TITLE
Could not find the repository

### ISSUE THREAD

**Issue by Ruposh** [elastic/curator#718]
2016-08-02 19:26:45,593 INFO      Action #1: snapshot
2016-08-02 19:26:45,688 ERROR     Repository /home/curator/repository not found.
2016-08-02 19:26:45,688 ERROR     Failed to complete action: snapshot.  <type 'exceptions.TypeError'>: argument of type 'bool' is not iterable

ACTION FILES:
actions:
  1:
    action: snapshot
    description: >-
      Snapshot logstash- prefixed indices older than 1 day (based on index
      creation_date) with the default snapshot name pattern of
      'curator-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
      the repository filesystem access check.  Use the other options to create
      the snapshot.
    options:
      repository: '/home/curator/repository'
      name:
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 1
      exclude:

**Comment by untergeek** [comment]
I would first advise adding a `:` after `exclude` where they are missed.  The YAML configuration language requires keys to be followed by colons.

**Comment by untergeek** [comment]
Proper indentation is also necessary.

**Comment by Ruposh** [comment]
Thank you @untergeek . I corrected all syntax error. But later I found that problem is with "repository path". I have updated action scripts and I found "Repository /home/curator/repository not found" error. What is the actual pattern to write any directory path. There is another error also " Failed to complete action: snapshot. : argument of type 'bool' is not iterable". Please take a look at that.

**Comment by untergeek** [comment]
You have to create a repository first. It's not just a file system path. It must be a shared file system that _all_ data and master nodes have write access to. There's an Elasticsearch API for that, as well as the `es_repo_mgr` script that ships with Curator.

**Comment by Ruposh** [comment]
Thank you @untergeek . It helped me a lot.
I am working in CENTOS 6. I have created a repository at "/home/curator/repository" using Elasticsearch API :
curl -XPUT 'http://localhost:9200/_snapshot/es_backup' -d '{
    "type": "fs",
    "settings": {
        "location": "/home/curator/repository",
        "compress": true
    }
}'
After that I can take snapshot of my elasticsearch indices by ES API:
curl -XPUT "localhost:9200/_snapshot/my_backup/snapshot_1?wait_for_completion=true".
But If I use curator, same problem arises. Though I can take snapshot but I want to use curator for more flexibility.

**Comment by Ruposh** [comment]
Ok. I got it. 
WRONG:      repository:  '/home/curator/repository'
CORRECT:    repository:  es_backup
Thank you @untergeek for your help :)
