### ISSUE TITLE
[Docs] Document the date math method for each time unit

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/curator#732]
Because of the way curator 4.x calculates time in the various units, it would be good to document how each of these unites are derived, as not all calculations will necessarily align with calendar-based math.

As outlined here: https://github.com/elastic/curator/blob/master/curator/utils.py#L232-L265

For example, a month is assumed to be 30 days, rather than however many days are in a given calendar month. So documenting this would be great, for the sake of understanding and planning for this behavior.

**Comment by untergeek** [comment]
Fixed by #734.  See https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_unit.html
