### ISSUE TITLE
--master_only option has been removed

### ISSUE THREAD

**Issue by pshroads** [elastic/curator#735]
It appears that the --master_only option has been removed as of at least 4.0.3. Passing the --master_only parameter now returns

Error: no such option: --master-only

I don't see this listed as a breaking change in the documentation.

**Comment by untergeek** [comment]
The option is in the configuration file now, not the command line.  Almost _everything_ is a breaking change if you've upgraded to 4.0.

See: https://www.elastic.co/blog/curator_v4_release

and also https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/configfile.html#master_only

**Comment by pshroads** [comment]
Thanks! I *really* thought I looked carefully but not carefully enough :/
