### ISSUE TITLE
Curator snapshot action timeout override

### ISSUE THREAD

**Issue by KrzysztofSendor** [elastic/curator#737]
As discuses with @untergeek on [discuss.elastic.co](https://discuss.elastic.co/t/curator-snapshot-action-timeout-override/58362) automatic `timeout_override` for actions like **snapshot** and **forcemerge** is not working in latest version of curator. This should be mentioned somewhere ideally in documentation found [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#timeout).

This is quote of @untergeek reply to my question on discuss.elastic.co relevant to this issue:

> You need to manually change the `timeout_override` for these actions for now. I initially had the feature in place, but removed it when I added `timeout_override`.
>But don't despair, the automatic, longer `timeout_override` for these actions will be fixed in 4.1.0 as a part of the schema validation feature being worked on right now.

**Comment by untergeek** [comment]
This has been fixed by #742
