### ISSUE TITLE
Nice to have: action description in logfile

### ISSUE THREAD

**Issue by ynux** [elastic/curator#738]
We have several delete_indices actions every day, deleting different indices after different periods. They all use the same curator.yml, so it all goes to the same logfile. Going through this logfile, it's a bit unconvenient to find out which delete_indices action is which. Presently I use the scheduled time to identify them. If the action.yml's description was written to the logfile, this would be a great help.

**Comment by untergeek** [comment]
I'm adding a similar logging functionality to the schema validation requested in #674.  It shouldn't be hard to add to the main body.
