### ISSUE TITLE
create_index filters support

### ISSUE THREAD

**Issue by sundarv85** [elastic/curator#740]
Hello,

We have weekly indexes. For e.g. node_2016_31, node_2016_32 etc.

We use the curator `alias` action, with the correct filters in the add/remove sections to create an alias for last_3_months (comprising of last 12 weekly indexes) and this works.

We would like to also create the index for next week, this week itself so that the alias will work smoothly. The `create_index` action does not support `filters` and `filtertype` like [alias command](https://github.com/elastic/curator/blob/master/examples/actions/alias.yml).

Such a support would be very helpful. Or is there any other way to do this.

**Comment by untergeek** [comment]
This kind of falls under #511, and the extended support for this.  Please comment there, as that's where this belongs.
