### ISSUE TITLE
yml parsing error

### ISSUE THREAD

**Issue by nickydu** [elastic/curator#741]
I run curator in Centos 6.x with command **curator --config /etc/logstash/conf.d/curator.yml curator_action.yml** and get the yaml parser error. I copied the configs from the example here https://www.elastic.co/guide/en/elasticsearch/client/curator/current/examples.html and https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

config:
---
  hosts:
    - 127.0.0.1
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

action file:
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 45 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 4
      exclude:

Python version is 2.6 and I use the 4.0.6 curator. 
Is there anything I missed?

**Comment by untergeek** [comment]
It's hard for me to tell what's going on here. I can't tell if it's properly formatted (indentation matters, and it is in the examples).  

In order to read it properly, please encapsulate each block of text in triple back-tick characters on their own line, with nothing else on that line e.g.

\`\`\`
formatted text goes here
\`\`\`

**Comment by untergeek** [comment]
Also, I think it's not a good idea to put your curator client configuration in your logstash conf.d directory.  Logstash will likely try to read it and parse it as a configuration file, and that will definitely yield an error.

**Comment by nickydu** [comment]
Thanks for your quick response! 
This is the config file
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"client:
  hosts:
    - 127.0.0.1:
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
```
Here is the action file
```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices.  Find which to delete by first limiting the list to logstash-
      prefixed indices. Next filter by space, to those indices in excess of
      20g of usage.  Then further filter those to prevent deletion of anything
      less than 30 days old.
    options:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: space
      disk_space: 20
      reverse: True
      use_age: True
      source: creation_date
      timestring:
      field:
      stats_result:
    - filtertype: age
      source: creation_date
      direction: older
      timestring:
      unit: days
      unit_count: 30
```

I already moved the config file to the curator directory. 
The Exception is:
```
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.0.6', 'console_scripts', 'curator')()
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 5, in main
    cli()
  File "/usr/lib/python2.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/curator/cli.py", line 128, in cli
    yaml_config  = get_yaml(config)
  File "/usr/lib/python2.6/site-packages/curator/utils.py", line 38, in get_yaml
    cfg = yaml.load(raw)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "<string>", line 20, column 1:
    logging:
    ^
```

**Comment by untergeek** [comment]
I believe I've found your problem:

```
hosts:
    - 127.0.0.1:
```

Remove the colon at the end of `127.0.0.1:` and it will hopefully work.

**Comment by nickydu** [comment]
Thanks! I removed it, but still see the same error...

**Comment by untergeek** [comment]
you're also missing the keyword, `client:` at the beginning of the config.yml file:

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - 127.0.0.1
```

Somehow you put it on the line before:

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"client:
  hosts:
    - 127.0.0.1
```

**Comment by nickydu** [comment]
Thank you so much! It's working now!
