### ISSUE TITLE
Add reindex action

### ISSUE THREAD

**Issue by untergeek** [elastic/curator#751]
This will only support Elasticsearch versions of 2.3+, but since we're on 2.4 now, I will try to squeeze it in before releasing 5.0.0

**Comment by untergeek** [comment]
There is limited use for the index filtering nature of Curator with this API.  I'm sure there are those out there who will be reindexing stuff nightly, but how will they determine which indices?

I need some use case feedback before I start blindly coding this.

**Comment by untergeek** [comment]
I think combining #733 with this will actually be pretty cool.  It would allow users to reindex one or more hours|days|weeks|months down to a single index.

I think the use case has been found.

**Comment by evanv** [comment]
If you're still looking for use cases, there are three that come to mind immediately for me:

1.  Reindex daily data into weekly or monthly indices after then end of the week / month. There are two clusters I'm working on right now that would benefit from functionality like this. The pattern in both cases would be combining daily indices into either weekly or monthly, once the week/month is over. 
2. Reduce shard count after index becomes immutable. This use case would probably be replaced by https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-shrink-index.html. But then again the cases where I've done this have always had to do with starting with a higher shard count to parallelize writes and then shrinking the shard count back down once the index is immutable. Other words, the first use case is much more generic and powerful than this use case. 
3. Reindexing old data to account for schema incompatibilities introduced by dynamic mappings and/or schema evolution. It is not uncommon to see log data evolve as users gain more experience with Kibana / ES. A great example that came to mind recently was status code in Nginx logs. Initially IP addresses were indexed as strings, before the devs realized they could be indexed as IP. We changed this to an IPv4 mapping in the index template. But, in doing so, we also introduced a backwards incompatibility in the mappings for the alias. The conflict itself can be avoided by never changing field names -- but a lot of times it's important to be able to retroactively fix some mapping in log data, and that usually involves ad hoc scripts either scanning and scrolling or using the _reindex API.

**Comment by cinhtau** [comment]
:+1: currently we are doing it with Jenkins and the ES REST API, but Curator would be the desired way to go

**Comment by untergeek** [comment]
Just to give you a heads-up, I do not intend to add the reindex action to the 4.x branch, even though the API technically is supported for 2.4.

The reindex action will only be available for Curator 5, and therefore will be version locked to ES 5.

**Comment by ppf2** [comment]
@untergeek Are we also adding shrink api support as part of this work for Curator 5?

**Comment by untergeek** [comment]
Shrink will likely come in a later release of 5.x, but not in 5.0
