### ISSUE TITLE
Incorrect element identified in logs when source: name is missing from an age filter

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/curator#759]
With debug logging enabled, if you omit the `source: name` from an age filter on an alias action, the log points you to the timestring element:

```
Bad Value: "%Y.%m.%d", extra keys not allowed @ data['timestring']. Check configuration file.. Check configuration file.
```

Rather than pointing out the missing, required `source` setting for the age filter.

**Comment by untergeek** [comment]
Fixed in #760
