### ISSUE TITLE
Bug - get_repository returns boolean when repo not found

### ISSUE THREAD

**Issue by emanjogu** [elastic/curator#761]
I am writing code that is checking if a repository exists. I use curator.utils.repository_exists which calls get_repository and expects a dict in return. However, if the repository I am searching for does not exist, get_repository returns a bool (False) instead of a dict, so curator.utils.repository_exists fails with the following error: 

  File "/var/task/curator/utils.py", line 925, in repository_exists
    if repository in test_result:
TypeError: argument of type 'bool' is not iterable

curator version:
**version** = '4.1.0'

**Comment by untergeek** [comment]
Ah. That's a holdover from the 3.x code. Back then I expected you to test for a value or a `False` before proceeding. 

With v4 already released, I can't really change this part of the API without breaking "existing" functionality. I can change this to be a `raise` then. 

In the meantime, test for `False` before proceeding:

```
value = curator.get_repository(...)
if value:
    # do something 
```

Sorry for the inconvenience.

**Comment by emanjogu** [comment]
Okay, I will do that. Thanks for the quick reply!
