### ISSUE TITLE
Boolean environment variables are not coerced

### ISSUE THREAD

**Issue by elliott-davis** [elastic/curator#765]
For variables that are boolean as environment variables get rendered as strings in yaml which fails the schema validation. I think the right answer is to coerce those variables into booleans like we do with integers.

**Comment by untergeek** [comment]
@elliott-davis can you give an example?  This has been addressed in the master branch, I think.

**Comment by elliott-davis** [comment]
I thought so too - so I did a build of master and tested it out - the config file I used looks like:

`actions:
    action: delete_indices
    options:
      disable_action: ${DISABLE_DELETE:False}
    filters:
      - filtertype: age
        source: name
        timestring: 'foo-%Y.%m.%d'
        direction: older
        unit: days
        unit_count: ${DAYS_TO_KEEP:14}`

When I run: `DAYS_TO_KEEP=30 DISABLE_DELETE=True curator action_file_above.yml` 

I get: `curator.exceptions.ConfigurationError: Configuration: options: Location: Action ID "1", action "snapshot": Bad Value: "True", expected bool for dictionary value @ data['disable_action']. Check configuration file.`

**Comment by untergeek** [comment]
Hmmm.  This is an awkward edge case.  The Voluptuous schema validator cannot coerce a string value of "True" to being a boolean value of `True`.  This is because Voluptuous' coerce method doesn't care about string boolean values:

```
def coerce(type, msg=None):
"""Coerce a value to a type.
 
If the type constructor throws a ValueError, the value will be marked as
Invalid.
"""
    def f(v):
        try:
            return type(v)
        except ValueError:
            raise Invalid(msg or ('expected %s' % type.__name__))
    return f
```

You can see what happens at any python command line:

```
>>> l = ['True', 'true', True, 'False', 'false', False]
>>> print('{0}'.format(l))
['True', 'true', True, 'False', 'false', False]
>>> for v in l:
...     print('Value: {0} is of type: {1}'.format(v, type(v)))
...
Value: True is of type: <type 'str'>
Value: true is of type: <type 'str'>
Value: True is of type: <type 'bool'>
Value: False is of type: <type 'str'>
Value: false is of type: <type 'str'>
Value: False is of type: <type 'bool'>
```

So because environment variables are inherently strings, Voluptuous cannot coerce.  What this means is that in order for it to coerce a string value of `'true'|'True'` or `'false'|'False'` into a true bool, I need to do it myself.  I can do this, and I apologize for the inconvenience.

**Comment by elliott-davis** [comment]
No inconvenience at at @untergeek. I'm glad that I could find an edge case. Thank you for taking it on!

**Comment by JD557** [comment]
> What this means is that in order for it to coerce a string value of 'true'|'True' or 'false'|'False' into a true bool, I need to do it myself.

I'm sorry for bringing this up again (as I previously stated, I'm not really familiar with Voluptuous), but wouldn't this be fixed if the code called `Boolean()` instead of `All(Any(bool, int), Coerce(bool))`?

From the Boolean source code:
```python
def Boolean(v):
    """Convert human-readable boolean values to a bool.

    Accepted values are 1, true, yes, on, enable, and their negatives.
    Non-string values are cast to bool.

    >>> validate = Schema(Boolean())
    >>> validate(True)
    True
    >>> validate("1")
    True
    >>> validate("0")
    False
    >>> with raises(MultipleInvalid, "expected boolean"):
    ...   validate('moo')
    >>> try:
    ...  validate('moo')
    ... except MultipleInvalid as e:
    ...   assert isinstance(e.errors[0], BooleanInvalid)
    """
    if isinstance(v, basestring):
        v = v.lower()
        if v in ('1', 'true', 'yes', 'on', 'enable'):
            return True
        if v in ('0', 'false', 'no', 'off', 'disable'):
            return False
        raise ValueError
    return bool(v)
```

This seems to be exactly what you are looking for, isn't it?

**Comment by untergeek** [comment]
Indeed.  I should have to be angry with the developer for not listing this in any of the examples I found, but rather the ones I used.

I'll test this out and see what I get.  It may not work, still, for some of the cases, as `None` is still valid (then it takes the default), so I may yet have to use something similar, but with an added if statement for the `None` case.
