### ISSUE TITLE
No plugin-descriptor.properties file

### ISSUE THREAD

**Issue by mdconner** [elastic/curator#774]
When installing from ZIP (no internet connection) with Elasticsearch 2.3.5, the install fails with "ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip".  Shouldn't this file be in source control?  I'm using version 4.0

**Comment by untergeek** [comment]
Can you provide more context? I've never seen that error before.

**Comment by mdconner** [comment]
I’m using elasticsearch/bin/plugin install file:/<dir>/curator.zip.

Michael D. Conner
Valley Forge, PA
(610) 354 - 4916

**Comment by untergeek** [comment]
Ah. Curator is not an Elasticsearch plugin. It is a standalone script

**Comment by untergeek** [comment]
Since this is a non-issue, I am closing this.
