### ISSUE TITLE
Issue with long urls should be documented

### ISSUE THREAD

**Issue by gmarziou** [elastic/curator#775]
Hello,

Thanks for this very useful tool.

While configuring a "close indices" action, I found that due to a list of 120+ actionable indices, I got an exception from ElasticSearch about "TooLongFrameException: An HTTP line is larger than 4096 bytes".

I worked around it by adding line below to `/etc/elasticsearch/elasticsearch.yml`

~~~
http.max_initial_line_length: 64K
~~~

Maybe there is a better way but I think it should be documented.

**Comment by untergeek** [comment]
What version of the API are you using?  The current version (Curator 4) handles these cases for you already.

See https://github.com/elastic/curator/blob/master/curator/utils.py#L349-L370:
```
def chunk_index_list(indices):
    """
    This utility chunks very large index lists into 3KB chunks
    It measures the size as a csv string, then converts back into a list
    for the return value.
    :arg indices: A list of indices to act on.
    :rtype: list
    """
    chunks = []
    chunk = ""
    for index in indices:
        if len(chunk) < 3072:
            if not chunk:
                chunk = index
            else:
                chunk += "," + index
        else:
            chunks.append(chunk.split(','))
            chunk = index
    chunks.append(chunk.split(','))
    return chunks
```


Which is used in each action, like this example https://github.com/elastic/curator/blob/master/curator/actions.py#L489-L494:
```
        try:
            index_lists = chunk_index_list(self.index_list.indices)
            for l in index_lists:
                self.client.indices.open(index=to_csv(l))
        except Exception as e:
            report_failure(e)
```

Curator 4 does this for you, for all actions.  Curator 3 tries to do this for most of the actions at the command-line level, but you'd have to do it yourself if you were using the API.  The `chunk_index_list` method is in Curator 3 in some form.

**Comment by gmarziou** [comment]
I'm using Curator 4.1.1 on top of ES 2.3.0.

I installed curator using pip:
-   urllib3 version=1.12
- click version=6.3
- PyYAML version=3.11
- elasticsearch version=2.4.0
- elasticsearch-curator version=4.1.1

**Comment by untergeek** [comment]
So how are you calling close indices?  I'm not following how you could hit this if you're using the proper methods.  Here's a simplified example (no filter args are actually shown):

```
client = elasticsearch.Elasticsearch(host='127.0.0.1')
ilo = curator.IndexList(client)
ilo.filter_by_age(**kwargs)
# add any other filters as necessary here
# ...
close = curator.Close(ilo)
close.do_action()
```

The `do_action` method for class `Close` looks like this:
```
    def do_action(self):
        """
        Close open indices in `index_list.indices`
        """
        self.index_list.filter_closed()
        self.index_list.empty_list_check()
        self.loggit.info(
            'Closing selected indices: {0}'.format(self.index_list.indices))
        try:
            index_lists = chunk_index_list(self.index_list.indices)
            for l in index_lists:
                if self.delete_aliases:
                    self.loggit.info(
                        'Deleting aliases from indices before closing.')
                    self.loggit.debug('Deleting aliases from: {0}'.format(l))
                    try:
                        self.client.indices.delete_alias(
                            index=to_csv(l), name='_all')
                    except Exception as e:
                        self.loggit.warn(
                            'Some indices may not have had aliases.  Exception:'
                            ' {0}'.format(e)
                        )
                self.client.indices.flush(
                    index=to_csv(l), ignore_unavailable=True)
                self.client.indices.close(
                    index=to_csv(l), ignore_unavailable=True)
        except Exception as e:
            report_failure(e)
```
See: https://github.com/elastic/curator/blob/master/curator/actions.py#L232-L260

As you can see, it uses the `chunk_index_list` method to prevent what you are seeing.  How are you calling your `close`?

**Comment by gmarziou** [comment]
I'm calling it from a cron defined as below

~~~
/bin/curator --config=/home/example/curator/curator.yml /home/example/curator/close_indices.yml
~~~

<summary>
The config file: `/home/example/curator/curator.yml`
<details>
~~~
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts: "127.0.0.1"
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
~~~
</details>

<summary>
The action file for close: `/home/example/curator/close_indices.yml`
<details>
~~~
---
actions:
  1:
    action: close
    description: >-
      Close indices older than 30 days (based on index name), for logstash-
      prefixed indices.
    options:
      delete_aliases: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
      exclude:
~~~
</details>

I also have another cron with an action file to delete the older indices and I don't remember if I had to increase the url length for close or delete.

<summary>
The action file for close: `/home/example/curator/delete_indices.yml`
<details>
~~~
---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 180 days (based on index name), for logstash-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 180
      exclude:
~~~
</details>

**Comment by untergeek** [comment]
Can you please attach the log file?  Preferably a DEBUG level log file.  This should not be happening.  As mentioned in my first response, those URLs are truncated at the 3072 byte range.  An additional index name can only be added if the URL is less than 3072 bytes.  They should not be _much_ bigger than 3072 bytes, unless you have very long index names.  That would make yours an edge case.

**Comment by gmarziou** [comment]
My longest index name is something like `logstash-supervision-2016.09.01`.
I'll try to get the log file tomorrow though I may have only one system left in similar state but probably with less indices open than the original one.

**Comment by untergeek** [comment]
It may be a call somewhere else in the chain that is not chunking.  I know that chunking works, as it's been around since 3.x.  That debug log will be essential to finding where that happened.  At the very least, the original log that had the 4096 error in it will be helpful.

I am trying to replicate this on my end and cannot :(

Without your data I won't know where to look.

**Comment by gmarziou** [comment]
I should be able to work on this next week.

**Comment by gmarziou** [comment]
Hello, I failed to reproduce the long URL problem.
So, I'm closing this issue and I'm sorry for wasting your time, thanks.
