### ISSUE TITLE
Curator 3 not processing filters in predictable

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/curator#781]
Details:

```
➜  ~ curator --version
curator, version 3.5.0
```

I have the following indices in my local environment:

```
➜  ~ curl localhost:9200/_cat/indices
yellow open index-2016.09.10   5 1 0 0   575b   575b
yellow open index-2016.09.39   5 1 0 0   575b   575b
yellow open index2016.09.39    5 1 0 0   575b   575b
green  open .marvel-2016.10.10 1 0 0 0 16.1kb 16.1kb
```

When using a daily time units, the prefix is not being respected. It's still trying to extract the timestamp from indices that the prefix is not match:

```
➜  ~ curator show indices --older-than 2 --time-unit days --timestring '%Y.%m.%d' --prefix 'sdafksadlfsdf-'
2016-10-10 09:22:26,499 INFO      Job starting: show indices
2016-10-10 09:22:26,509 ERROR     Could not extract a timestamp matching 2016.09.39 from timestring %Y.%m.%d
2016-10-10 09:22:26,509 ERROR     Could not extract a timestamp matching 2016.09.39 from timestring %Y.%m.%d
2016-10-10 09:22:26,509 WARNING   No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': u'sdafksadlfsdf-', 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 2, 'all_indices': False}
No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': u'sdafksadlfsdf-', 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 2, 'all_indices': False}
```

Note that it's trying to extract the timestamp for *index-2016.09.39* and *index2016.09.39*. Given that we know the prefix at this point, i would expect curator to check the prefix before parsing the date. If the prefix is match, then i think that it's fine to raise the ERROR because the weekly indices cannot be extracted by a daily pattern.

@untergeek what do you think? Is this something that we can address?

Thanks!

**Comment by untergeek** [comment]
That's easily addressed by upgrading to Curator 4. Filters are processed in the order they appear in the configuration file.

**Comment by untergeek** [comment]
I'd change the title to, "Curator 3 doesn't process filters in a predictable order"

**Comment by gmoskovicz** [comment]
@untergeek thanks for confirming this. The `ERROR` messages are benign anyway, so not a huge issue, but do you think that this could be addressed in Curator 3?

**Comment by untergeek** [comment]
No, not without drastically changing the API.  Curator 3 is pretty dead at this point. I'd only update a security fix.

I am planning on adding some singleton CLI actions as add-ons to Curator 4, but these are not yet part of any release schedule.

Is there some reason a user is resistant to Curator 4?

**Comment by untergeek** [comment]
I'm changing the label because the issue is resolved in Curator 4.  Yes, it's a bug in 3, but it has been fixed in a subsequent version.

**Comment by gmoskovicz** [comment]
@untergeek 

> Is there some reason a user is resistant to Curator 4?

Not really. I was just curious. Thanks for confirming i think that we can close this issue 😺 

Thanks!

**Comment by untergeek** [comment]
@gmoskovicz You should also note that 2016.09.39

**Comment by gmoskovicz** [comment]
Oh yes @untergeek .. i was trying with `%Y.%m.%d` to show this issue. The real issue is shown when you have daily indices and monthly indices at the same time. One with an index pattern and another with another index pattern, and Curator tries to parse the timestamp from indices not matching the prefix which is odd.

**Comment by untergeek** [comment]
Actually, it doesn't care.  The pattern is just `^.*(timestamp pattern).*$`.  And because it's just matching digits: 4 numbers, a period, 2 numbers, a period, and 2 numbers; Then weeks match the pattern, but it can't be reverse translated to `%d` for days.  That's what the error is actually doing.   Yes, `prefix` is not being filtered first, but that's why it sees the pattern there.

So, to your point, if you were to have `monthly-%Y.%m` and `daily-%Y.%m.%d`, without applying prefix first, the above timestamp pattern would match because 4 digits followed by a period, followed by 2 digits still matches the `daily` index type too.  Curator 4 allows you to get around this by using an extra filter with exclude set to True, e.g.

```
- filtertype: pattern
  kind: timestring
  value: '%Y.%m'
  exclude: False
- filtertype: pattern
  kind: timestring
  value: '%Y.%m.%d'
  exclude: True
```
Without calculating any dates, this would filter to keep only 4 digit + `.` + 2 digit timestring patterns.

Of course, it could also be handled by prefix first, too, should the prefixes differ.

**Comment by gmoskovicz** [comment]
Thanks for the detailed explanation @untergeek . This makes sense. I was curious around why the pattern wasn't being calculated after matching the prefix, but given how this is done it makes sense.
