### ISSUE TITLE
readonly plugin blocking curtor (cant delete the indexes)

### ISSUE THREAD

**Issue by pramod08** [elastic/curator#791]
Hello 

Am using curator  for deleting indices in elasticseach ..
plugins installed 
1.readonlyrest-plugin
2.head
3.Installed curator using pipe 

elasticsearch version = 2.4

when i run manually the curator (3.5.1 )
curator delete indices --older-than 1 --time-unit days --timestring %Y.%m.%d

it will block by the readonly-plugin
The bellow Error as i run above command by manually 
curator delete indices  --time-unit days --timestring %Y.%m.%d
2016-10-24 17:51:44,977 INFO      Job starting: delete indices
2016-10-24 17:51:44,988 ERROR     Failed to get indices.
2016-10-24 17:51:44,988 ERROR     No indices found in Elasticsearch
ERROR. No indices found in Elasticsearch.

**Comment by untergeek** [comment]
The readonlyrest-plugin is not an officially supported/recognized plugin of the Elastic Stack.  As such, Curator is not designed to handle its altered behavior.  There's nothing I can do to help you here.

**Comment by pramod08** [comment]
Thank you for reply @untergeek
