### ISSUE TITLE
ElasticSearch Curator for ES/Kibana 5.0?? 

### ISSUE THREAD

**Issue by elJoeyJojo** [elastic/curator#799]
Hello,

I know it doesn't support ES 5.0 but my question is does ES/Kibana 5.0 remove logs automatically? What is the default set to? I basically want to know what I need to configure on my ES/Kibana Server to remove logs/indices after a period of time or does ES 5.0 do that automatically to the point where you don't need anything like Curator anymore?

Thanks and sorry for posting this in the Issues section. I just can't find a clear answer on this. 

Thank You

Joey

**Comment by untergeek** [comment]
huh?  Who told you that Curator doesn't work with ES 5.0?  Did you see the compatibility matrix on the home page here?  https://github.com/elastic/curator

**Comment by elJoeyJojo** [comment]
@untergeek hey Aaron, sorry I guess I saw the the chart and I assumed 'cause I read it quite quickly. I will try to setup Curator for ES 5.0. Thank You
