### ISSUE TITLE
Wondering how to express --timestring when month is variable length

### ISSUE THREAD

**Issue by fabiendelpierre** [elastic/curator#808]
Hi folks,
I have an ES cluster with monthly indices called "tracking_m_yyyy", which produces tracking_1_2016, tracking_2_2016 ... tracking_12_2016. When they're three months old, they need to get closed.
I'm struggling to get Curator to work with the way the date is expressed in the names of the indices.

If it matters, this is on a CentOS 7 box, Python is v2.7.12, Curator is v3.5.1, ES is v1.7.5.

This works, but only partially:
```
$ /usr/bin/curator --logfile /var/log/curator.log --loglevel INFO --logformat default  --host localhost --port 9200 close indices --prefix 'tracking_' --time-unit months --older-than 3 --timestring '%m_%Y'
```
The problem is the `%m` in Python's `strftime()` pads single-digit months with a zero, and my indices don't have that leading zero. So if I have an index called tracking_10_2015, it'll get closed fine, but tracking_9_2015 is ignored.

I tried expressing `--timestring` as `%-m_%Y` instead, which works in regular Python:
```
$ python
Python 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime(2015,3,5).strftime('%m_%Y')
'03_2015'
>>> datetime.datetime(2015,3,5).strftime('%-m_%Y')
'3_2015'
```

But apparently Curator doesn't like that:
```
$ /usr/bin/curator --logfile /var/log/curator.log --loglevel INFO --logformat default  --host localhost --port 9200 close indices --prefix 'tracking_' --time-unit months --older-than 3 --timestring '%-m_%Y'
ERROR. Timestring %-m_%Y does not contain time unit months
```

Before you ask: yes, I could have the indices for the months of Jan through Sep created with that leading zero to begin with, but that's controlled by an app I don't control, needs a release, QA, regression and all that jazz, and it would take a while to make it into prod, so that's a last resort.

Is there something I can do differently to get this working? Thanks!

**Comment by untergeek** [comment]
Curator doesn't support single-digit month notation, even though Python does, due to the regular expression hoops that would be required to verify and properly extract the dates and re-translate them back again.  You _might_ be able to just disable the safety checks that ensure `%m` is present for `--time-unit months`, but I would not test that theory without running a `--dry-run`

If you were using Elasticsearch 2.x or newer, I would suggest upgrading to the [current version of Curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html) (which just recently re-added [3.x style command-line actions](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/singleton-cli.html)) and using the [index `creation_date`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_creation_date) to [filter](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html).

Since you aren't using Elasticsearch 2.x or newer, then I'm afraid I can't do anything else to help you.

**Comment by fabiendelpierre** [comment]
Thanks for getting back to me.
You mentioned disabling a safety check -- is that a command-line flag or would that mean modifying the code? Just wanna know what I'm getting into. I'm not a Python dev (or any kind of dev), I can probably figure it out but any leads are appreciated :)
Is [this](https://github.com/elastic/curator/blob/3.5/curator/cli/utils.py#L284) the safety check you mentioned in the version I'm using?

**Comment by untergeek** [comment]
Yes, that line is the one. You have to comment that out to bypass the check.

**Comment by fabiendelpierre** [comment]
I'll give it a shot then, thanks!

**Comment by fabiendelpierre** [comment]
Following up: no luck.

```
$ tail utils.py
        if '%d' in timestring:
            retval = True
    elif time_unit == 'weeks':
        if '%W' in timestring:
            retval = True
    elif time_unit == 'months':
#        if '%m' in timestring:
        if '%m' in timestring or '%-m' in timestring:
            retval = True
    return retval
$ curl -XPUT localhost:9200/tracking_9_2015
{"acknowledged":true}$
$ curl -XPUT localhost:9200/tracking_10_2015
{"acknowledged":true}$
$ /usr/bin/curator --dry-run --loglevel INFO --logformat default  --host localhost --port 9200 close indices --prefix 'tracking_' --time-unit months --older-than 3 --timestring '%m_%Y'
2016-11-10 21:12:29,766 INFO      Job starting: close indices
2016-11-10 21:12:29,791 INFO      Action close will be performed on the following indices: [u'tracking_10_2015']
2016-11-10 21:12:29,791 INFO      DRY RUN MODE.  No changes will be made.
2016-11-10 21:12:29,792 INFO      DRY RUN: close: tracking_10_2015
$ /usr/bin/curator --dry-run --loglevel INFO --logformat default  --host localhost --port 9200 close indices --prefix 'tracking_' --time-unit months --older-than 3 --timestring '%-m_%Y'
2016-11-10 21:12:33,337 INFO      Job starting: close indices
2016-11-10 21:12:33,361 WARNING   No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': u'tracking_', 'time_unit': 'months', 'timestring': u'%-m_%Y', 'exclude': (), 'older_than': 3, 'all_indices': False}
No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': u'tracking_', 'time_unit': 'months', 'timestring': u'%-m_%Y', 'exclude': (), 'older_than': 3, 'all_indices': False}
```

Guess it's back to convincing the devs to do it differently 😄

**Comment by untergeek** [comment]
Yeah.  The parser is kind of limited in that way.  It was expected that the people naming things would remember to make them uniform, so they are parsable.
