### ISSUE TITLE
"ignore_empty_list" not exposed in "Singleton Command Line Interface" for "delete_indices"

### ISSUE THREAD

**Issue by jippi** [elastic/curator#812]
Hi,

Would it be possible to expose ignore_empty_list for the "new" CLI ?

On a new cluster, the delete_indices fail since there currently is no indices older than the $x of filter_list, and it's not possible to configure that as expected from the CLI tool.

**Comment by untergeek** [comment]
Maybe. I'll see what I can do

-- Aaron Mildenstein
