### ISSUE TITLE
Error: no such option: --host

### ISSUE THREAD

**Issue by FlorinAndrei** [elastic/curator#813]
Ubuntu 16.04

Installed curator from the APT package https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html

```
$ curator --version
curator, version 4.2.1
```

The ES cluster is in the Elastic Cloud.

```
$ curator --host XXXXXXXXXXXXX.aws.found.io --port 9200 --http_auth 'XXXXXXX:XXXXXXXX' show indices
Error: no such option: --host
$ curator --host XXXXXXXXXXXXXX.aws.found.io --port 9243 --use_ssl --certificate certifi-cacert.pem --http_auth 'XXXXXXX:XXXXXXXX' show indices
Error: no such option: --host
```

**Comment by FlorinAndrei** [comment]
Same error if I install from pip

**Comment by FlorinAndrei** [comment]
I must say, trying to use this tool is very frustrating. SSL doesn't work well due to a bug. What seems to be valid syntax with --host doesn't work either. The documentation is extremely poor quality - appears written to pass some documentation benchmarks and fill up a predetermined number of pages, but it does nothing for those who are just learning to use the software (but this is an issue with all ElasticSearch documentation). Where are the examples for show indices with the --host option?

**Comment by FlorinAndrei** [comment]
Downgrading to curator 3.5.1 removes the error.

**Comment by corey-hammerton** [comment]
Curator starting from 4.2.0 adds a `curator_cli` command-line utility with much of the previous syntax available. The `curator` command works by relying on a configuration file and an action file, both in YAML format. 

You should be able to run the `curator_cli` utility as follows:

`$ curator_cli --host XXXXXXXXXXXXX.aws.found.io --port 9200 --http_auth 'XXXXXXX:XXXXXXXX' show indices`

The configuration file options can be viewed [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html).
The action file options can be viewed [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/actionfile.html).

**Comment by FlorinAndrei** [comment]
3.5.1 works great and makes more sense. Thanks.

**Comment by benlavender** [comment]
Just adding some info for users on ES 5.x.x that elasticsearch-curator version 3.5.1 doesn’t support ES 5.x.x. I’ve on 5.1.1 and having to use the singleton command section as noted here:

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/singleton-cli.html
