### ISSUE TITLE
Remove old data in index

### ISSUE THREAD

**Issue by MartinPyka** [elastic/curator#825]
I couldn't find in the documentation a way to delete only data with a certain age within an index (for indices that don't have a date as suffix). Is this supported by curator? Otherwise I would propose it as a feature request.

Best,
Martin

**Comment by corey-hammerton** [comment]
Curator is only capable of index management, your request requires the Elasticsearch delete-by-query plugin or Bulk delete them.

**Comment by untergeek** [comment]
Indeed. Curator is for index-level management. A feature to delete data within an index is outside the scope of Curator's intended reach.
