### ISSUE TITLE
Cannot snapshot the .security index under Curator 4 / ES 2.x

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/curator#826]
Curator seems to use `GET /_all/_settings?expand_wildcards=open%2Cclosed` to build it's initial list of indices, but under Elasticsearch 2.4.1, the `.security` index doesn't appear in that query response.     

This seems to be resolved with ES 5.x, as it returns the `.security` index details.

**Comment by untergeek** [comment]
Is there an API call that does pull the `.security` index in 2.4.1?  Curator can only show what the Elasticsearch API reveals.

**Comment by PhaedrusTheGreek** [comment]
@clintongormley might know...

**Comment by clintongormley** [comment]
See https://www.elastic.co/guide/en/shield/current/limitations.html#_accessing_the_literal_security_literal_index

**Comment by untergeek** [comment]
@PhaedrusTheGreek I'm not sure this is an easy fix, though it should be doable.  It will require an ugly workaround that may not even be effective unless the provided credentials have all required permissions.  This will likely result in a lot of ugly extra error and/or warning messages suggesting that `.security` may or may not be there, and Curator can't tell exactly.  The steps 

1. Figure out which version of Elasticsearch (2.x or 5.x)
2. If 2.x, then test for the presence of `.security` manually.  _This can fail for so many reasons I'm not sure if my tests will be conclusive._ Log warnings/errors if not found or it cannot be accessed by the provided credentials.
3. Manually add the `.security` index to the IndexList object and its metadata.

Is this a customer request?

**Comment by PhaedrusTheGreek** [comment]
Thanks @untergeek .   there may not be a great deal of demand for this functionality in Elasticsearch 2.x, especially since  will soon be moving to 5.x anyhow, under which the issue is fixed in Elasticsearch.     

Currently 2 workarounds exist:
1.  use ES 5.x or 
2. use the Snapshot API directly

**Comment by untergeek** [comment]
The proper way to fix this is to upgrade to 2.4.2, which mimics the 5.x behavior of including `.security` in a wildcard search.  

There is no other workaround, as earlier 2.x versions disallow closing and deleting of the `.security` index, making it impossible to restore from a snapshot.

**Comment by PhaedrusTheGreek** [comment]
Upgrading to 2.4.2 does allow a workaround in that you can manually snapshot and restore the `.security` index,  But I just tested curator still doesn't see the `.security` index.

**Comment by untergeek** [comment]
My misunderstanding. I'll reopen this.
