### ISSUE TITLE
[Enhancement] Allow to set the name name of the snapshot created on S3 with singleton snapshot action

### ISSUE THREAD

**Issue by trompx** [elastic/curator#827]
Hello,

In curator 3.x, the snapshot backup on the s3 repository had the same name specified in command line with --prefix.

With curator 4.2.3.post1, I end up with names like meta-0UH9cMZsR1Df5v68IaDPEQ.dat.
Is it possible to still get the nice formatted name as specified in --name my-nice-name-hourly-%Y%m%d%H%M%S ?

Use case : I had bash scripts dynamically getting snapshot to restore according to parameters (specific date or "latest") and it picked the right backup according to its name.

**Comment by untergeek** [comment]
This has nothing to do with Curator and everything to do with the Elasticsearch 5 API. The name you assign is only visible via API call. The same thing applies to indices. You should not be looking at the file system for information about either, but only the API.

**Comment by untergeek** [comment]
See https://www.elastic.co/guide/en/elasticsearch/client/curator/current/restore.html

Note that leaving `name` blank for the restore action automatically selects the most recent snapshot.
