### ISSUE TITLE
show_snapshots lists only the last backup and lists it twice

### ISSUE THREAD

**Issue by trompx** [elastic/curator#828]
Hello,

Curator version: 4.2.3.post1

When I execute the first backup with "singleton snapshot":
`curator_cli $ES_OPTS snapshot --repository $S3_REPOSITORY --name my-nice-name-hourly-%Y%m%d%H%M%S --filter_list '{"filtertype":"pattern","kind":"prefix","value":"myindice"}'`
the `show_snapshots` returns:
```
my-nice-name-hourly-20161125002650
my-nice-name-hourly-20161125002650
```
I excpect it to return only 1 result.

If then I index some more data and make another snapshot, the `show_snapshots` returns:
```
my-nice-name-hourly-20161125010047
my-nice-name-hourly-20161125010047
```

While a new .dat file has been added to the s3 repository, the show_snapshots shows no trace of the previous backups.

Excpected results of the second run of `show_snapshots`:
```
my-nice-name-hourly-20161125002650
my-nice-name-hourly-20161125010047
```

**Comment by trompx** [comment]
It seems I had network issues and the snapshot did not complete. I tried it again today (after an elasticsearch cluster restart) and everything works fine. I am not sure but checking the snapshots status, one were either in IN_PROGRESS or ABORTED state.

So it makes sense that the output were always different as the snapshot never completed.

What is still weird is:
- why when the snapshot is still running, the show_snapshots showed the snapshot twice.

As for the new .dat file in the s3 repo, I guess it is created when the snapshot starts and not cleared if the snapshots fails.

**Comment by untergeek** [comment]
Thanks for reporting back that it worked after the cluster restart.

I'm not sure why it shows two running.  I'll take a look at adding the status in another column with `--verbose` output at some point.  It probably means one of them is flagged IN_PROGRESS and the other is something else.

**Comment by untergeek** [comment]
I'm not seeing this issue in the master branch anymore.  It's probably because I'm using `elasticsearch-py` version `5.1.0`, so it's a better API matchup.
