### ISSUE TITLE
Error: Elasticsearch version 5.1.0 incompatible with this version of Curator (5.1.0)

### ISSUE THREAD

**Issue by martbhell** [elastic/curator#832]
Hi!

If I change the version_max in settings.py to 
<pre>
def version_max():
    return (5, 1, 1)
</pre>

Then I do not get the below error and if I run it without --dry-run it closes the index so seems to work with 5.1.0 still.
<hr>

<pre>
# curator --version
curator, version 4.2.3.post1
</pre>

error:
<pre>
# /bin/curator --config /etc/curator/curator.yml /etc/curator/action.yml --dry-run
Traceback (most recent call last):
  File "/bin/curator", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.3.post1', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 585, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.1.0 incompatible with this version of Curator (5.1.0)
</pre>

This is with elasticsearch 5.1.0
<pre>
# curl http://localhost:9199/_nodes?pretty|grep version

      "version" : "5.1.0",
        "version" : "3.10.0-327.36.3.el7.x86_64",
        "version" : "1.8.0_111",
        "vm_version" : "25.111-b15",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
          "version" : "5.1.0",
</pre>

**Comment by untergeek** [comment]
Elasticsearch 5.1.0 is not yet officially released. It will be supported when it is released.

**Comment by martbhell** [comment]
Oops. I've been using "https://artifacts.elastic.co/packages/5.x/yum" to get the packages. Thought that was the latest stable :)

**Comment by untergeek** [comment]
Yes. It will work with 5.0.2.  I'll be updating Curator to support 5.2+ this week.
