### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by dotmilk** [elastic/curator#84]
```
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==1.0.0', 'console_scripts', 'curator')()
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 345, in main
    version_number = get_version(client)
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 163, in get_version
    version = client.info()['version']['number']
TypeError: string indices must be integers
```

elasticsearch 1.1.1

**Comment by amulyas** [comment]
@untergeek is there a way I can use both Curator and http-basic-server-plugin at the same time

**Comment by untergeek** [comment]
@amulyas Unfortunately no. Curator depends on some other health check metadata, and it seems that said plugin interferes with that.

**Comment by amulyas** [comment]
thanks @untergeek so the only way to secure elasticsearch is via nginx proxy or something .. I wish I can make this work but it seems ..it not trivial . is there a way I can pass version information to curator .. so it not depend on health check to get version

**Comment by untergeek** [comment]
@amulyas Well, that's why Elastic has the Shield security product.  Proxies are not very effective, though they are better than nothing.

There may be other ways to capture the version information, but this is the easiest.  If you can find another that doesn't break other functionality (or cause dramatic slowdowns), I could be persuaded to merge it.

**Comment by Ramlalit** [comment]
@untergeek  i am aslo getting the same problem:
  File "/home/ram/Asiaville/asiaville-project/lib/python3.5/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/ram/Asiaville/asiaville-project/lib/python3.5/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/ram/Asiaville/asiaville-project/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/home/ram/Asiaville/asiaville-project/lib/python3.5/site-packages/elasticsearch/exceptions.py", line 58, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers


but i have not added plugin can you help me or anyone

**Comment by Ramlalit** [comment]
output of curl -v localhost:9200/_clus

ter/stats?pretty
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET /_cluster/stats?pretty HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 2618
< 
{
  "timestamp" : 1551254433222,
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "indices" : {
    "count" : 0,
    "shards" : { },
    "docs" : {
      "count" : 0,
      "deleted" : 0
    },
    "store" : {
      "size_in_bytes" : 0,
      "throttle_time_in_millis" : 0
    },
    "fielddata" : {
      "memory_size_in_bytes" : 0,
      "evictions" : 0
    },
    "filter_cache" : {
      "memory_size_in_bytes" : 0,
      "evictions" : 0
    },
    "id_cache" : {
      "memory_size_in_bytes" : 0
    },
    "completion" : {
      "size_in_bytes" : 0
    },
    "segments" : {
      "count" : 0,
      "memory_in_bytes" : 0,
      "index_writer_memory_in_bytes" : 0,
      "index_writer_max_memory_in_bytes" : 0,
      "version_map_memory_in_bytes" : 0,
      "fixed_bit_set_memory_in_bytes" : 0
    },
    "percolate" : {
      "total" : 0,
      "time_in_millis" : 0,
      "current" : 0,
      "memory_size_in_bytes" : -1,
      "memory_size" : "-1b",
      "queries" : 0
    }
  },
  "nodes" : {
    "count" : {
      "total" : 1,
      "master_only" : 0,
      "data_only" : 0,
      "master_data" : 1,
      "client" : 0
    },
    "versions" : [ "1.7.2" ],
    "os" : {
      "available_processors" : 4,
      "mem" : {
        "total_in_bytes" : 16686645248
      },
      "cpu" : [ {
        "vendor" : "Intel",
        "model" : "Core(TM) i5-7200U CPU @ 2.50GHz",
        "mhz" : 3100,
        "total_cores" : 4,
        "total_sockets" : 4,
        "cores_per_socket" : 16,
        "cache_size_in_bytes" : 3072,
        "count" : 1
      } ]
    },
    "process" : {
      "cpu" : {
        "percent" : 0
      },
      "open_file_descriptors" : {
        "min" : 154,
        "max" : 154,
        "avg" : 154
      }
    },
    "jvm" : {
      "max_uptime_in_millis" : 6591021,
      "versions" : [ {
        "version" : "1.8.0_201",
        "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
        "vm_version" : "25.201-b09",
        "vm_vendor" : "Oracle Corporation",
        "count" : 1
       "count" : 1
      } ],
      "mem" : {
        "heap_used_in_bytes" : 50934312,
        "heap_max_in_bytes" : 1038876672
      },
      "threads" : 44
    },
    "fs" : {
      "total_in_bytes" : 970137522176,
      "free_in_bytes" : 914553806848,
      "available_in_bytes" : 865250025472,
      "disk_reads" : 128774,
      "disk_writes" : 319590,
      "disk_io_op" : 448364,
      "disk_read_size_in_bytes" : 2629964800,
      "disk_write_size_in_bytes" : 11662929920,
      "disk_io_size_in_bytes" : 14292894720,
      "disk_queue" : "0",
      "disk_service_time" : "5.5"
    },
    "plugins" : [ ]
  }
}
* Connection #0 to host localhost left intact

**Comment by untergeek** [comment]
@Ramlalit I'm not sure what the context is for what you're doing, even. A new issue is more appropriate.

I can tell you, however, that I am surprised and should probably not be seeing `django` in the output for a Curator run. I'm guessing you installed via `pip`, and if possible, should instead be trying one of the independent packages.

**Comment by Ramlalit** [comment]
@untergeek thanks for the reply, ok I will try
