### ISSUE TITLE
Outdated apt packages index file

### ISSUE THREAD

**Issue by ksmets** [elastic/curator#841]
After upgrading elastic stack to 5.1.1 cron jobs running curator commands throw the following exception:

```
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.1.1 incompatible with this version of Curator (5.1.1)
```

Turns out that I was still running `curator, version 4.1.2`.  

The [deb-package](https://packages.elastic.co/curator/4/debian/pool/main/p/python/elasticsearch-curator_4.2.4_amd64.deb) is present, but it seems that the apt packages index file for `deb http://packages.elastic.co/curator/4/debian stable main` is outdated and therefore upgrading via apt-get no longer works.

Could you please update the apt packages index file?

Thx, Koen

**Comment by untergeek** [comment]
There's an issue upgrading from `elasticsearch-curator` 4.1.2.  See #821

I upgraded to 4.2.4 from 4.2.3 just fine, using APT:

```
$ sudo apt list | grep curator | grep installed
elasticsearch-curator/stable,stable,now 4.2.4 amd64 [installed]
```

**Comment by ksmets** [comment]
Thx, you're right, apparently package name changed from `python-elasticsearch-curator` to `elasticsearch-curator`. Installing it via apt-get removes `python-elasticsearch-curator` properly and installs fine.

Closing this issue.

**Comment by acasademont** [comment]
Sorry to chime in here again but I'm facing the same issue...APT reports 4.2.5 installed but "curator_cli --version" reports 4.2.3.post1

Am I missing something?

**Comment by acasademont** [comment]
Nevermind...someone had installed curator via PIP and there were 2 versions...
