### ISSUE TITLE
Document OR pattern filter use case

### ISSUE THREAD

**Issue by ppf2** [elastic/curator#842]
The way filtertype works today is that it will run through each filtertype and determine if they will remain or be dropped from the actionable list.  Which means that it is effectively doing an AND (so if you have multiple filtertype patterns in the action, it will not work the way you may expect).  To get an OR type of functionality, you will have to use a regex kind, eg. 

    filters:
    - filtertype: pattern
      kind: regex
      value: '^(logstash-123_|metricbeat-123_|winlogbeat-123_).*$'
      exclude:     
    - filtertype: age
      source: name 
      direction: older 
      timestring: '%Y.%m.%d' 
      unit: days 
      unit_count: 1 
      exclude: 

It will be nice to document this use case.

**Comment by untergeek** [comment]
@ppf2 Check it out now: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html

It's also redundantly added [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_pattern.html) and [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_kind.html) as well.

**Comment by ppf2** [comment]
Thanks for adding!
