### ISSUE TITLE
Elasticsearch version 5.1.1 incompatible with this version of Curator (5.1.1)

### ISSUE THREAD

**Issue by easonlau02** [elastic/curator#844]
Hi All, below is my installation information about elasitcstack.

```
Elasticsearch : 5.1.1
Elasticsearch curator : 4.2
```

curator 4.2 is working well with elasticsearch 5.0.1. But throw below error when housekeep elasticsearch 5.1.1.
> 2016-12-10 12:00:02,010 INFO      Preparing Action ID: 1, "delete_indices"
> Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.1.1 incompatible with this version of Curator (5.1.1)

Any idea? Thanks.

**Comment by untergeek** [comment]
Upgrade to Curator 4.2.4. See https://github.com/elastic/curator/issues/832
