### ISSUE TITLE
Apt-get (or dpkg) warns of weaks digest algorithm use by signature

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/curator#846]
Curator version: 4.2.4

OS version: Ubuntu 16.04.1

Description of the problem including expected versus actual behavior:
Warning from apt-get when doing an update after adding Curator repository: ```W: http://packages.elastic.co/curator/4/debian/dists/stable/Release.gpg: Signature by key 46095ACC8548582C1A2699A9D27D666CD88E42B4 uses weak digest algorithm (SHA1)```

Notes:

- It updates/installs just fine, it just warns.
- Was also an reported for Elasticsearch, Kibana and Logstash

Steps to reproduce:

1. Add elastic GPG key as explained in the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html)
2. Add curator repository to sources list and update: ```apt-get update```

**Comment by untergeek** [comment]
4.2.5 is released, and this has been corrected.
