### ISSUE TITLE
Requirement on elasticsearch < 3.0.0

### ISSUE THREAD

**Issue by cp2587** [elastic/curator#865]
Hello,

In requirements.txt, why do you have the following requirement: elasticsearch<3.0.0,>=2.4.0 ? The library seems to work with elasticsearch 5.0.1 which is the official python package for elasticsearch 5.x. Can you update the requirement accordingly ?

**Comment by untergeek** [comment]
It will be updated for Curator v5. Many of the tests do not pass because the API calls have changed slightly.

**Comment by cp2587** [comment]
OK. Thank you very much for the quick reply. Do you know when you will release curator 5 ?

**Comment by untergeek** [comment]
Not sure, honestly. No firm date yet.

**Comment by untergeek** [comment]
This change is already in master.
