### ISSUE TITLE
curator do not find Repository?

### ISSUE THREAD

**Issue by lglavas** [elastic/curator#876]
Hi I am new to ES and curator and are learning how to use the tools. I cant find info of a solution on this but please point me to it.

`$ curator --version
curator, version 4.2.5`

The ACTION_FILE.YML ID:3:
`  3:
    action: delete_snapshots
    description: >-
      Delete snapshots from the selected repository older than 1 days
      (based on creation_date), for 'curator-' prefixed snapshots.
    options:
      repository: MPST
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: curator-
      exclude:
    - filtertype: age
      source: creation_date
`

When i execute i get this error:
`XXXX@mpst06:~/git_repos/mpst/curator$ curator --config CONFIG.YML --dry-run ACTION_FILE.YML
2017-02-02 13:28:25,516 INFO      Action ID: 1: "delete_indices" not performed because "disable_action" is set to True
2017-02-02 13:28:25,516 INFO      Action ID: 2: "delete_indices" not performed because "disable_action" is set to True
2017-02-02 13:28:25,516 INFO      Preparing Action ID: 3, "delete_snapshots"
2017-02-02 13:28:25,528 INFO      Trying Action ID: 3, "delete_snapshots": Delete snapshots from the selected repository older than 1 days (based on creation_date), for 'curator-' prefixed snapshots.
2017-02-02 13:28:25,534 ERROR     Repository MPST not found.
2017-02-02 13:28:25,534 ERROR     Failed to complete action: delete_snapshots.  <class 'TypeError'>: argument of type 'bool' is not iterable
XXXX@mpst06:~/git_repos/mpst/curator$ `

In ES i have the repository. As seen when executing "GET _nodes/":
`{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "docker_MPST-cluster",
  "nodes": {
    "GEuGm00XRTuoiIw8teJCyQ": {
      "name": "LTesting",
      "transport_address": "172.17.0.3:9300",
      "host": "172.17.0.3",
      "ip": "172.17.0.3",
      "version": "5.1.2",
      "build_hash": "c8c4c16",
      "total_indexing_buffer": 211261849,
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "settings": {
        "cluster": {
          "name": "docker_MPST-cluster"
        },
        "node": {
          "name": "LTesting"
        },
        "path": {
          "logs": "/usr/share/elasticsearch/logs",
          "home": "/usr/share/elasticsearch",
          "repo": "/usr/share/elasticsearch/data/MPST"
        },
        "client": {
          "type": "node"
        },
        "http": {
          "type": {
            "default": "netty4"
          }
        },
        "transport": {
          "type": {
            "default": "netty4"
          }
        },
        "network": {
          "host": "0.0.0.0"
        }
      },
      "os": {
        "refresh_interval_in_millis": 1000,
        "name": "Linux",
        "arch": "amd64",
        "version": "4.4.0-45-generic",
        "available_processors": 4,
        "allocated_processors": 4
      },
...`

Suspect that **"repo": "/usr/share/elasticsearch/data/MPST"** is not what curator is looking for?

The elasticsearch.yml looks like this:
`cluster.name: "docker_MPST-cluster"
network.host: 0.0.0.0
path.repo: /usr/share/elasticsearch/data/MPST
node.name: "LTesting"
`
What I want is to set up and start the ES docker container with a predefined repo that curator can maintain and manage that repo. 

Or am I thinking all wrong?

**Comment by lglavas** [comment]
But when asking for snapshots:
`GET _snapshot/_status`

I get no results back:
`{
  "snapshots": []
}`

I know that if I PUT a snapshot name XXX and then change curator "ACTION_FILE.YML" to look for "repository: XXX". Then curator will find it. 
But i whant to be configured from start alredy when ES starts.
This is confusing curator want a **repo**. And in ES we make a **snapshot**!

But if it is a snapshot I need in ES in the docker image. What is the setting/name on the variable I probably put in the elasticsearch.yml??? :1st_place_medal:

**Comment by untergeek** [comment]
How did you create the repository?

The repository must be a shared file system, usually NFS for Linux systems, but s3 and HDFS are also available. Each master and data node must be able to both read and write to this shared file system, so with NFS this also requires matching user is permissions. 

The repository must be registered with elasticsearch via an API call _and_ the `path.repo` set to the shared file system mount point. In your case it seems that you've defined the path.repo as a sub folder in your regular elasticsearch data path. This would only work in a single node cluster, as that is the only way a local path is shared by all nodes, since there's only one. It defeats the purpose of a backup, too, since the storage is local. 

I'm not sure what your aiming for, but you'll need to figure out how to mount NFS (or some kind of shared fs) in your Docker containers to do snapshots.

**Comment by lglavas** [comment]
Thank you for your reply!
I am with a docker file making a image "FROM elasticsearch:5.1.2". And loading my own elasticsearch.yml: 
`cluster.name: "docker_MPST-cluster"
network.host: 0.0.0.0
path.repo: /usr/share/elasticsearch/data/MPST
node.name: "LTesting"`

(Yes, the above "docker_MPST-cluster" is only a single node cluster.)
I am aiming on to bring up some containers that are managing network traffic between them. And I want ES to capture logs and I also have containers with grafana and kibana to be able to present graphs/trends/results from ES.

The thing is that the containers and systems should be automatically/easy to set up and tear down. For shorter tests and configuration setups. So it is like you say running on one disc and it is yellow state without backup. 

I aiming for curator to delete the oldest data in ES when the one hard drive fills up. And a mandatory field are the "repository:" in the "action: delete_snapshots". 

So I have set the path.repo and what API call are you referring to? Maybe something i have overseen?

**Comment by untergeek** [comment]
You have to create the repository for Elasticsearch to recognize using the API.  See https://www.elastic.co/guide/en/elasticsearch/reference/5.2/modules-snapshots.html#_repositories

**Comment by untergeek** [comment]
You can also use the `es_repo_mgr` tool that ships with Curator.  It does the API call for you, using the command-line.

**Comment by lglavas** [comment]
Yes, thank you. 
But is it not strange that you can not set a specific repository automatically after you started your docker ES container/image?

I mean either in the Dockerfile for ES with something like ENTRYPOINT (and a curl command) mekanism (_but should instead execute after_ the docker image are up and running when started not before..)
But more naturally a setting in the elasticsearch.yml file. Regardless of filesystem.

**Comment by untergeek** [comment]
> But more naturally a setting in the elasticsearch.yml file. Regardless of filesystem.

I can see why that would be helpful in your case, and why you'd want it.  Unfortunately, it doesn't work that way.  Remember that Elasticsearch is a _distributed_ system.  You would have to guarantee that all nodes had the exact same line in the elasticsearch.yml file.  But the problem remains, that as nodes are added and removed, things can be changed.  Elasticsearch strives to do _everything_ via API.  As a repository must be recognized on all nodes, even in cases where you are only running a single node, it makes more sense to be able to add that via API call and have it applied to all nodes in the cluster.  You simply must add the repository to your node via the API call (or the `es_repo_mgr` script, which does the API call) or Elasticsearch cannot make use of it.

Sure, you could make use of ENTRYPOINT or some such, but it is moot if Elasticsearch is not already up and running.  You can't make an API call to a system that isn't running.

**Comment by lglavas** [comment]
Thank you for your help and explanation untergeek!
You have helped me to gain insights on ES and curator. Closing this issue.
