### ISSUE TITLE
Elasticsearch version 5.2.0 incompatible with this version of Curator (5.2.0)

### ISSUE THREAD

**Issue by matelukas** [elastic/curator#885]
Hi guys,

I am getting following error when  running curator against latest ES:

```
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.2.0 incompatible with this version of Curator (5.2.0)
```
```
curator, version 4.2.5
```

It works fine after bumping max version in `curator/defaults/settings.py`

Thanks.

**Comment by untergeek** [comment]
The curator version has already been bumped and this issue addressed. 4.2.5 isn't the latest version.
