### ISSUE TITLE
Undocumented `repository` option on `curator.create_repository()`

### ISSUE THREAD

**Issue by rcoh** [elastic/curator#888]
In `curator.create_repository()` the code expects a repository kwarg:

https://github.com/elastic/curator/blob/master/curator/utils.py#L893
```
    if not 'repository' in kwargs:
        raise MissingArgument('Missing required parameter --repository')
    else:
        repository = kwargs['repository']
```

However, the repository command isn't mentioned in the documentation at all. As best I can tell, the documented parameter `location` is unused -- perhaps this parameter was supposed to be called repository?

**Comment by untergeek** [comment]
There are only two lines of code that call this function, and they are both in [`repomgrcli.py`](https://github.com/elastic/curator/blob/v4.2.6/curator/repomgrcli.py#L54) (which is just the one for the fs repo type).

As you read this, you can see that it does, in fact, pass kwargs, including `repository`.  This function should probably be updated, as it's really only a holdover from Curator 3, with few (if any) modifications.  You can model your call after the one in `repomgrcli.py`, which are the `click.option` parameters/decorators above the main `fs` function.

**Comment by untergeek** [comment]
You are correct, though.  Somehow the `repository` arg is omitted from those docs.  I'll try to fix that.
