### ISSUE TITLE
Curator API Not Returning ".monitoring" Indices

### ISSUE THREAD

**Issue by kylegoch** [elastic/curator#900]
Elasticsearch: 5.2.1
Curator: 4.2.6

Been using curator to prune our Log cluster, however we recently started storing Monitoring data from xPack there. I wanted to start pruning those indices as well.

We use a slightly modified version of [this code](https://gist.github.com/jarpy/f65b24209e0a9240207599a73ce99bc9#file-serverless-curator-py) from [this blog post](https://www.elastic.co/blog/serverless-elasticsearch-curator-on-aws-lambda).

Currently all the logs are getting cleaned up, however when adding the prefix `.monitoring-es-2-` to the cleanup list, nothing occurs.

I checked the indices being pulled in by the initial IndexList creation, and its all of our logs indices, but none of the indices that start with `.`.

Code snippet in question:
```
index_list = curator.IndexList(es)
print (index_list.working_list())
```

That just returns all indices except those with starting with `.`. Is there some way to override that, that I may have missed in the docs somewhere? Or is this something by design? Or a bug? or PEBKAC?

**Comment by untergeek** [comment]
You mentioned that you have x-pack.  The Monitoring data will auto-prune at 7 days, so unless you want it for less than that, Curator is perhaps unnecessary.

The other likelihood is that you have some permissions issues that are protecting these indices.  I see the monitoring indices when I run this:

```
# curator_cli show_indices
.kibana
.monitoring-data-2
.monitoring-es-2-2017.02.23
.monitoring-es-2-2017.02.24
.monitoring-es-2-2017.02.25
.monitoring-es-2-2017.02.26
.monitoring-es-2-2017.02.27
.monitoring-es-2-2017.02.28
.monitoring-es-2-2017.03.01
.monitoring-kibana-2-2017.02.23
.monitoring-kibana-2-2017.02.24
.monitoring-kibana-2-2017.02.25
.monitoring-kibana-2-2017.02.26
.monitoring-kibana-2-2017.02.27
.monitoring-kibana-2-2017.02.28
.monitoring-kibana-2-2017.03.01
.monitoring-logstash-2-2017.02.23
.monitoring-logstash-2-2017.02.24
.monitoring-logstash-2-2017.02.25
.monitoring-logstash-2-2017.02.26
.monitoring-logstash-2-2017.02.27
.monitoring-logstash-2-2017.02.28
.monitoring-logstash-2-2017.03.01
.security
...(all of my other indices come after)
```

If I do it from the python console, it looks like this:

```
>>> import elasticsearch
>>> import curator
>>> client = elasticsearch.Elasticsearch(host='esclient', http_auth='user:pass')
>>> ilo = curator.IndexList(client)
>>> print (sorted(ilo.working_list()))
[u'.kibana', u'.monitoring-data-2', u'.monitoring-es-2-2017.02.23', u'.monitoring-es-2-2017.02.24',...]
```
That's why I'm guessing it's a permissions issue.  It works for me.

**Comment by kylegoch** [comment]
:facepalm:
I didnt even think of permissions. I had only given curator permissions to "logs-*". Adding a permission for ".monitoring-*" makes them show up now.

Also, thanks for the tip on the xpack auto pruning. I didn't know that, we didnt want to keep too much since we use DataDog so we have most stats there, but XPack Monitoring has been a super useful replacement for Kopf for insight into what the shards/etc are up to.

Thanks again!

**Comment by untergeek** [comment]
@kylegoch Auto-pruning won't work if you're sending the indices to another cluster.  I re-read and noticed that, so don't rely on auto-prune when you're sending the monitoring data to another cluster.

**Comment by kylegoch** [comment]
@untergeek awesome, thanks for that. We are sending the monitoring data from our main cluster to the log cluster, so auto-prune isnt going to work there.
