### ISSUE TITLE
Allocation doesn't work

### ISSUE THREAD

**Issue by psychoche** [elastic/curator#904]
OS: Ubuntu 14.04.5 LTS
Elasticsearch: 5.2.1
Curator: 4.2.6 installed via pip

I'm trying to follow this how-to: [https://www.elastic.co/blog/hot-warm-architecture-in-elasticsearch-5-x](https://www.elastic.co/blog/hot-warm-architecture-in-elasticsearch-5-x)

When I've got the error:
`2017-03-15 09:54:47,098 ERROR                curator.cli                    cli:193  Failed to complete action: allocation.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: TransportError(400, u'illegal_argument_exception', u'wait_for_relocating_shards has been removed, use wait_for_no_relocating_shards [true/false] instead')`
I found closed issue: [Action : Allocation fails with exception error #871 ](https://github.com/elastic/curator/issues/871)

I don't know why, but fix from [#896](https://github.com/elastic/curator/pull/896) is absent in version 4.2.6. So I did this fix manually in actions.py file.  
And now I'm getting a new error:

`2017-03-15 10:09:44,325 ERROR                curator.cli                    cli:193  Failed to complete action: allocation.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: global name 'version' is not defined`

**Comment by untergeek** [comment]
The fix is not in 4.2.6 because the patch came after 4.2.6 was released. 

You probably omitted this line in your patch:
```
version = get_version(self.client)
```

**Comment by psychoche** [comment]
You're right. I've just missed it when I reproduce it last time. 
Actual error is: 
`2017-03-15 14:26:07,527 ERROR                curator.cli                    cli:193  Failed to complete action: allocation.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: health() got an unexpected keyword argument 'wait_for_no_relocating_shards'`

**Comment by untergeek** [comment]
Hmm.  Not sure what might be going on for you, but it tested completely fine across all versions of Python (2.7, 3.4, 3.5) Elasticsearch (2.0, 2.1, 2.2, 2.3, 2.4, 5.0, 5.1). Subsequent builds also test this code against 5.2, and it all passes.

![Travis Buildl](https://cloud.githubusercontent.com/assets/1020383/23954089/fea5d024-095b-11e7-801c-791544725e73.png)

**Comment by untergeek** [comment]
That includes integration tests, so I know it works against Elasticsearch.

**Comment by untergeek** [comment]
No more response. Closing
