### ISSUE TITLE
Missing yaml dependency

### ISSUE THREAD

**Issue by cafuego** [elastic/curator#917]
It looks like the debian packaged elasticsearch-curator 4.2.6 is either built without libyaml support or missing the python-yaml dependency. This results in curator throwing a cryptic error on an otherwise valid yaml action file:

```
curator --config /etc/curator/curator.yml /etc/curator/delete_errors.action.yml 
/etc/curator/delete_errors.action.yml: 1: [: /usr/bin/curator: unexpected operator
```

Installing elasticsearch-curator via pip after installing both build-essential and python-yaml resolves my issue.

**Comment by untergeek** [comment]
The bundled package most assuredly does have py-yaml:

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

# apt list | grep ^elasticsearch-curator
elasticsearch-curator/stable,now 4.2.6 amd64 [installed]
```

```
# ls /opt/elasticsearch-curator/lib/python3.5/_yaml.cpython-35m-x86_64-linux-gnu.so
/opt/elasticsearch-curator/lib/python3.5/_yaml.cpython-35m-x86_64-linux-gnu.so
```

I have this running personally out of my own cron.

Do you have some other Python 3.5 on your system which might be in conflict?  This would be the very first time I have heard of _any_ issues with the frozen release (which is what you have). Please share your configuration, and os + patch level, I would love to spin up a VM and see if I can replicate what you are seeing.

**Comment by untergeek** [comment]
Is it possible you had an older version of Curator which wasn't completely cleaned out?

**Comment by cafuego** [comment]
Weird. It's unlikely I have multiple curators installed, this is all running in docker images. With python 2.7 and *not* 3.x.

I don't have an OS config for you, but the next best thing: docker images :-)

The image that throws the error is unocha/curator:4.2.6-201703-01, the one that works fine is unocha/curator:4.2.6-201704-04.

Note that in both cases, curator is installed via pip. The reason I mention the packaged one is that I tried using it after I found that the 4.2.6 images did NOT work after I bumped the version.

The previous image I had been using (unocha/curator:4.2.4-201612-01) *did* work fine and I had not modified the Dockerfile at all between those two builds.

**Comment by untergeek** [comment]
The debian packaged elasticsearch-curator does not need any python installed, as it is frozen, and comes with one bundled with all necessary libraries _except for ones it expects the system to provide_.  If you're using pip, you don't need the package.  So, if you tried the package and it failed, that sounds as if there's some other development dependency or missing library in your Docker images.  

It may take some time to track down.  I don't know when I'll get to it, but will when I can.  If you've got a valid work-around using pip, then that's great too.

**Comment by untergeek** [comment]
The bundled version of Python is 3.5, which you probably gathered.

**Comment by cafuego** [comment]
Yup, I'm happy to use the work-around via pip.

I expect then that my problem is that I use the python:2.7 base docker image to build the curator one. That comes with python 2.7 pre-installed and undoubtedly *it* gets picked as interpreter, meaning it can't load the bundled 3.5 yaml extension and making it barf^W exit ungracefully ;-)

**Comment by untergeek** [comment]
It shouldn't, though.  It's like running Python in a virtualenv.  Nothing outside of it should be considered.  That's why I'm leaning toward the missing system library idea...

**Comment by cafuego** [comment]
I did try installing libyaml with the packaged one but that seemed to not sort it :-/ That's not an image I ended up pushing, though.

**Comment by untergeek** [comment]
Installing pyyaml generally results in a compiled version of libyaml.  I wonder if the libraries this was compiled against are not present in your docker image.  It would be lovely if you could test that theory. No worries if you can't.

**Comment by untergeek** [comment]
This has been months without an update, and I cannot duplicate it.  I'm closing it for now.  If you feel this has been done in error, please feel free to reopen it.
