### ISSUE TITLE
support specifying new index name in the RollOver action

### ISSUE THREAD

**Issue by zumo64** [elastic/curator#938]
we would like to use in curator this feature available in the API : 
https://www.elastic.co/guide/en/elasticsearch/reference/5.3/indices-rollover-index.html#_naming_the_new_index

**Comment by jurajseffer** [comment]
@zumo64 I've just implemented it in https://github.com/mooprint/curator/commit/e3cd06e07db8bb7185196dc88b5aebaacf798b50?w=1

We need this to automate index/alias creation because increasing counter as suffix is not predictable which is a requirement when relying on default rollover behaviour.

**Comment by untergeek** [comment]
Why don't you submit it as a pull request?

**Comment by jurajseffer** [comment]
@untergeek Will do.

**Comment by untergeek** [comment]
Will close this after I add some integration tests and documentation.
