### ISSUE TITLE
DeleteSnapshot API timing out, failing immediately on retry

### ISSUE THREAD

**Issue by davekonopka** [elastic/curator#940]
I'm trying to delete snapshots on a recurring schedule via the Python API on AWS Lambda. I'm hitting long wait times for the deletion to complete. It eventually will fail with a 504 gateway timeout but then hits a 404 on retry because the snapshot no longer exists.

Example sequence for a single snapshot:
```
2017-04-25T00:59:51.214Z Deleting snapshot logs-20170424221413...
2017-04-25T01:00:51.85Z DELETE http://mysescluster:9200/_snapshot/some_snapshots/logs-20170424221413 [status:504 request:59.871s]
2017-04-25T01:00:51.258Z DELETE http://myescluster:9200/_snapshot/some_snapshots/logs-20170424221413 [status:404 request:0.173s]
```

The 1 minute timeout is coming from my Elasticsearch cluster being behind an AWS ELB with a 1 minute idle timeout. I can bump that and the Elasticsearch connection timeout to give it more room.

What's confusing though is that the Snapshot seems to delete since the retry hits a 404. So it looks like the delete succeeds but doesn't finish the request. 

Is there any way to avoid waiting for completion when calling `DeleteSnapshot` via API? It doesn't look like this method supports it in the underlying ES transport method.

Elasticsearch version: 5.2.2
Curator version: 5.0.1
Elasticsearch-py version: 5.1.0

**Comment by untergeek** [comment]
Unfortunately, no.

[Read about the native python client call](http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.client.SnapshotClient.delete) (note, no options for anything other than _master node_ timeout.)

[Read the official API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/modules-snapshots.html) (again, no options for timeout of any kind).

The call simply blocks until it's done.  That's all that can be said about it.

Ideas on what to try include trying to catch an [Elasticsearch  TransportError](http://elasticsearch-py.readthedocs.io/en/master/exceptions.html#elasticsearch.TransportError) and then test to see if the snapshot exists any more.  It seems like it gives the 404, even if the underlying delete is incomplete.

**Comment by untergeek** [comment]
By the way, the retry is a function of urllib3, not Curator or the Elasticsearch client module.

**Comment by davekonopka** [comment]
@untergeek Thank you for the quick response and pointers to details. It's clearly not Curator's issue.
