### ISSUE TITLE
curator_cli arguments usage

### ISSUE THREAD

**Issue by moshe-sa** [elastic/curator#942]
Hey, 
Can you show how can I use the ARGS feature with the curator_cli command-line? It's missing in the documentations.

I tried something like this:

`curator_cli show_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count": "$i" },{"filtertype":"pattern","kind":"prefix","value":"logstash"}]' i=14
`

Thanks

**Comment by untergeek** [comment]
It is possible, but you have to use double-quotes to encapsulate the `--filter_list`, and then escape every other double-quote, like this:
```
$ i=14; curator_cli show_indices --filter_list "[{\"filtertype\":\"age\",\"source\":\"creation_date\",\"direction\":\"older\",\"unit\":\"days\",\"unit_count\": \"$i\" },{\"filtertype\":\"pattern\",\"kind\":\"prefix\",\"value\":\"logstash\"}]"
logstash-2017.04.11
```

**Comment by untergeek** [comment]
And this isn't something I plan on putting in the documentation.  It's standard shell behavior.
