### ISSUE TITLE
Docker image published somewhere?

### ISSUE THREAD

**Issue by olalonde** [elastic/curator#943]
Is that Docker image published somewhere? I'd like to use it without having to checkout and build the repository.

**Comment by untergeek** [comment]
I don't publish it.  Someone else may, but I haven't kept track of it.  Duplicate of #528.

**Comment by olalonde** [comment]
Ok well, that was a feature request then :) Published `4.3.0` to https://hub.docker.com/r/olalonde/curator/ in the meantime.
