### ISSUE TITLE
Indices with epoch 0 are ignored by curator

### ISSUE THREAD

**Issue by 64r** [elastic/curator#951]
Hi,

I've encountered the following issue:

Assume someone created an index named `shakespeare-1970.01.01`. 
The following filters won't match the index, although it is clearly older than 30 days.:

```json
filters:
- filtertype: pattern
  kind: prefix
  value: shakespeare-
- filtertype: age
  source: name
  direction: older
  timestring: '%Y.%m.%d'
  unit: days
  unit_count: 30
```

The debug-log shows the following message:

`DEBUG  curator.indexlist  filter_by_age:456  Index "shakespeare-1970.01.01" does not meet provided criteria. Removing from list.`

Epoch 0 is considered neither older nor newer than any other timestamp so this index will never be deleted.

Thanks for looking into that issue.

Tobi

**Comment by untergeek** [comment]
Ah. I found it.  Simple fix.  Wait for the update.  Thanks for reporting this and making Curator better.
