### ISSUE TITLE
curator commands do nothing and silently terminate

### ISSUE THREAD

**Issue by jesaremi** [elastic/curator#955]
I'm running two curator examples like the following. Both of them exit with absolutely no print out:

python -m curator.cli --config curator.yml actions\delete_indices.yml
finishes after a split second with no output
python -m curator.curator_cli show_indices --verbose --header
does and shows absolutely nothing

I'm using this version: elasticsearch_curator-5.0.1 against ElasticSearch 5.4

thanks

**Comment by untergeek** [comment]
Why are you launching it as a module?  While there _is_ a module, you should be launching this as a regular command-line binary because `setup.py` builds `entry_point`s for both `curator` and `curator_cli`.   The `entry_point` will launch Curator appropriately.  

I assume you installed via `pip`, since you're running this via python. As such, the `entry_point` should have installed to either `/usr/bin/curator_cli` or `/usr/local/bin/curator_cli`.

If those are in your `PATH`, and a correctly configured `curator.yml` file is in `~/.curator/curator.yml`, then I expect you should be able to run (and see somewhat similar output to) the following:

```
$ curator_cli show_indices --verbose --header
Index                             State     Size      Docs Pri Rep   Creation Timestamp
.kibana                            open  653.7KB       418   1   1 2017-01-26T06:01:23Z
.ml-anomalies-shared               open   37.1MB    184100   5   1 2017-05-04T20:16:22Z
.ml-notifications                  open   37.9KB        44   1   1 2017-05-04T20:16:24Z
.ml-state                          open  115.4KB         4   5   1 2017-05-04T20:16:27Z
.monitoring-alerts-2               open   13.8KB         2   1   1 2017-05-04T19:13:00Z
.monitoring-data-2                 open   61.5KB        24   1   1 2017-01-26T04:10:33Z
.monitoring-es-2-2017.05.02        open    1.2GB   1597278   1   1 2017-05-01T23:59:59Z
.monitoring-es-2-2017.05.03        open    1.2GB   1610394   1   1 2017-05-03T00:00:01Z
.monitoring-es-2-2017.05.04        open    1.2GB   1653678   1   1 2017-05-04T00:00:03Z
.monitoring-es-2-2017.05.05        open    1.1GB   1753512   1   1 2017-05-05T00:00:01Z
... truncated output for brevity
```

**Comment by jesaremi** [comment]
The entry points don't work when you install as a virtualenv and then move the installation. That's how we need to get this to prod machines. Is there anyway to call it from the python scripts?

**Comment by untergeek** [comment]
If you've installed in a virtualenv, why not just call `run_singleton.py` in the base directory?

**Comment by jesaremi** [comment]
run_* scripts are not a part of the installation. I'll copy then over and see what happens

**Comment by jesaremi** [comment]
run_* scripts did the job. Thanks very much!

**Comment by rokka** [comment]
I have got the same problem. curator and curator_cli are doing nothing with no error message or something else.

```
$ cat ~/.curator/curator.yml
---

logging:
  loglevel: DEBUG
```

```
$ curator_cli show_indices --verbose --header
2017-12-31 00:57:53,309 DEBUG              curator.utils             get_client:803  kwargs = {'url_prefix': '', 'timeout': 30, 'hosts': ['127.0.0.1'], 'ssl_no_validate': False, 'master_only': False, 'port': 9200, 'aws_sign_request': False, 'use_ssl': False, 'certificate': None, 'aws_token': None, 'aws_secret_key': None, 'aws_key': None, 'client_cert': None, 'client_key': None, 'http_auth': None}
2017-12-31 00:57:53,312 DEBUG              curator.utils             get_client:880  Not using "requests_aws4auth" python module to connect.
```

Any ideas?


Greetings
Andre

**Comment by untergeek** [comment]
You almost certainly have a misconfiguration in `~/.curator/curator.yml`, to see nothing more in the logs.  Will you please show what you have there?

**Comment by rokka** [comment]
```
$ cat ~/.curator/curator.yml
---

logging:
  loglevel: DEBUG
```

**Comment by rokka** [comment]
Ah I have got the problem:

http_auth is missing

A little information that auth was failing would be nice ;-)

Thanks for your super fast answer!

**Comment by untergeek** [comment]
Oh, my.  You had nothing, so everything was default.  Yeah, that wouldn't provide any `http_auth`.  The only way for Curator to know that (and provide the message you wanted to see) is to set `blacklist: []` in the `logging` section.  The default blacklist omits some of those connection messages, as they can be quite verbose.

**Comment by ejoso** [comment]
I'm having this same problem but have http_auth configured.  I installed via rpm/yum.
Any suggestions?  curator/config.yml below:

# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ["_eth0_", "_local_"]
  port: 9200
  url_prefix:
  use_ssl: True
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth: elastic:<PASSWORD>
  timeout: 60
  master_only: False
logging:
  loglevel: DEBUG #INFO
  logfile: /var/log/curator/curator.log
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

**Comment by untergeek** [comment]
@ejoso, this ticket is closed.  Please start a thread at https://discuss.elastic.co/c/elasticsearch for usage questions like these.  The answers will be much more useful to the community there.
