### ISSUE TITLE
continue_if_exception bug

### ISSUE THREAD

**Issue by hexian55** [elastic/curator#960]
hi  all

config
actions:
  1:
    action: delete_indices
    description: "Delete indices passport_ngx_log"
    options:
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: passport_ngx_log-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
  2:
    action: delete_indices
    description: "Delete indices huyu_zhibo"
    options:
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: regex
      value: hy_zhibo_flow-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y-%m-%d'
      unit: days
      unit_count: 10

curator log
2017-05-11 18:32:41,452 INFO      Preparing Action ID: 1, "delete_indices"
2017-05-11 18:32:41,463 INFO      Trying Action ID: 1, "delete_indices": Delete indices passport_ngx_log
2017-05-11 18:32:42,285 ERROR     Unable to complete action "delete_indices".  No actionable items in list: <class 'curator.exceptions.NoIndices'>

I see this doc 
If continue_if_exception is set to True, Curator will attempt to continue on to the next action, if any, even if an exception is encountered. Curator will log but ignore the exception that was raised.

but I don't understand action 1 delete_indices  is null,  it's not continue run action 2?

**Comment by untergeek** [comment]
There are two kinds of exception. There's an empty list, which generates the `NoIndices` or `NoSnapshots` exceptions, and everything else. Try using [`ignore_empty_list'](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.0/option_ignore_empty.html) to continue past the exception you hit. 

The reason for two different kinds of exceptions is that an empty list might be a benign, expected condition for new clusters and indices. The other kind of exception is almost always bad.

**Comment by untergeek** [comment]
I'm adding a blurb to the `continue_if_exception` documentation to help inform about this.

**Comment by untergeek** [comment]
And I've merged and cherry-picked it into all doc branches, 4.2 and up.  Our doc builder should add the bits to these branches soon.

**Comment by hexian55** [comment]
I see   
thank you very much!
