### ISSUE TITLE
Add support for Clear Cache API

### ISSUE THREAD

**Issue by jakauppila** [elastic/curator#974]
We have a centralized logging cluster that has ~4TB of disk on it for 30 days worth of logs.

Since we have a number of fields that we want to do full-text searching against, we have some analyzed fields which results in fielddata consuming memory on the cluster.

I think it might be useful to configure Curator to clear out the fielddata from indices older than X days to free up some of that memory while keeping more recent data in memory.

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/indices-clearcache.html

Thoughts?

**Comment by untergeek** [comment]
Hmm.  Curator is specifically for index management.  I'm not sure this falls under Curator's index management scope.

**Comment by untergeek** [comment]
I can see the argument in favor of this, but clearing the cache is not exactly managing the indices, but rather Elasticsearch itself.  I'll have to keep thinking about this.  Clearing cache is not something we typically recommend, though there are obvious use cases for it (like yours).

Whether I add this to Curator or not, it would be rather trivial to use the Curator API to write your own way to do this right now.
