### ISSUE TITLE
Snapshots do not work with AWS ES 5.3

### ISSUE THREAD

**Issue by cjuroz** [elastic/curator#987]
As requested in #639 I open this issue:

AWS ES 5.3 has been released recently and they _now_ claim is compatible with Curator: https://aws.amazon.com/about-aws/whats-new/2017/06/elasticsearch-5-3-now-available-on-amazon-elasticsearch-service/
> Curator Support: Enabled usage of the popular Curator utility to simplify index management tasks.

I have been using Curator 5 API to create a Lambda function (here: https://gist.github.com/cjuroz/d45f4d73e74f068892c5e4f3d1c7fa7c) that will help to automate index cleaning and snapshots management. 

So far, index cleaning operations are working pretty fine *BUT* snapshot creation is failing because AWS guys still didn't expose `/_snapshot/_status` endpoint. I already reported this bug here: https://forums.aws.amazon.com/thread.jspa?threadID=257549.

Note: As a workaround, I am using ElasticSearch API to directly send signed request to ES to do snapshots.

**Comment by untergeek** [comment]
I addressed this in the documentation in https://github.com/elastic/curator/pull/988

**Comment by mkubenka** [comment]
It looks like `/_snapshot/_status` endpoint is working after AWS ES [add support for 5.5](https://aws.amazon.com/about-aws/whats-new/2017/09/elasticsearch-5_5-now-available-on-amazon-elasticsearch-service/). Probably related with availalibity to retore automated snapshots:

> Self-service restore of Amazon Elasticsearch Service domains is now available from the automated snapshots taken by the service. All automated snapshots are available for restore from the Elasticsearch API or Curator CLI. You no longer have to request support assistance for restore requests.

I have tried `examples/actions/snapshot.yml` and it worked even on 5.3!

**Comment by untergeek** [comment]
From what I understand, this has been corrected in AWS ES 5.5.  Closing for now.
