### ISSUE TITLE
Snapshot to External Location

### ISSUE THREAD

**Issue by shubhamverma27** [elastic/curator#991]
Hi, How to send the snap shots to an external location like in es quer we do :-

1: $ curl -XPUT  'http://localhost:9200/_snapshot/my_backup' -d '{
    "type": "fs",
    "settings": {
        "location": "/mount/backups/my_backup",
        "compress": true
    }
}'

How to Specify the location in curator?
Also Is there an option to Archive Snapshots in curator?
@

**Comment by untergeek** [comment]
This is a usage question, not a bug or an enhancement request.  

Please ask such questions at https://discuss.elastic.co in the Elasticsearch forum.
