### ISSUE TITLE
Older versions not visible in Curator 5 APT repository

### ISSUE THREAD

**Issue by DustinChaloupka** [elastic/curator#993]
I actually opened an issue for a similar problem but with the [Curator 4 apt packages](https://github.com/elastic/curator/issues/929) and am wondering if something has happened to the Curator 5 packages now. The only [package listed](http://packages.elastic.co/curator/5/debian/dists/stable/main/binary-amd64/Packages) seems to be the 5.1.1 version. Were the older versions removed on purpose?

**Comment by untergeek** [comment]
`reprepro` is to blame, as it doesn't seem to support the desired behavior (preserving older versions in `Packages`.  I switched to using `aptly` for the Curator 4 repository, but have not done so for Curator 5 (and may never do so for that branch).  It's a huge risk taking down one published repo to put up another, and hope it all goes smoothly, with all paths properly preserved.  This will probably be addressed in a more permanent fashion for Curator 6.

If you really need to pull down prior versions, you should be able to specify `MAJOR`.`MINOR`.`PATCH` for the URL:

```
https://packages.elastic.co/curator/5/debian/pool/main/e/elasticsearch-curator/elasticsearch-curator_MAJOR.MINOR.PATCH_amd64.deb
```

You should almost _never_ have to do this, though.  I strive to ensure reverse-compatibility and not break functionality in minor point releases.  Anything 5.1 will still do everything 5.0 will do, but with fewer bugs, and some new functionality.  You should be able to always feel comfortable upgrading.

**Comment by DustinChaloupka** [comment]
Upgrading is what we went with! Unsure if you want to keep this open or not so I'll leave that up to you.

**Comment by untergeek** [comment]
It _is_ a known issue. Thanks for reminding me to get stuff working.  I'll update the title and see what I can do.

**Comment by untergeek** [comment]
No longer releasing RPM/DEB packages, so this is moot.
