### ISSUE TITLE
Fix DeleteSnapshot retry logic

### ISSUE THREAD

**Issue by JD557** [elastic/curator#999]
Right now, the retry logic for the delete snapshot is handled by the `safe_to_snap` function.

Unfortunately, this function only checks if a snapshot is `IN_PROGRESS`. There are other problems (e.g. if a snapshot is being deleted) that are not handled by this method and that should be retried as well.

**Comment by untergeek** [comment]
How would those conditions be detected?

**Comment by JD557** [comment]
Using the`/_cat/snapshots` endpoint, you can look for `cluster:admin/snapshot/delete` tasks.

**Comment by untergeek** [comment]
What conditions lead to this? Is Curator deleting these and then, due to some slowness not able to delete a second batch?

I ask, because it will be hard for me to replicate those conditions in order to see what the API might return. Without having an accurate sample of real API returns in that case, it will be hard to catch. It's kind of hard to catch an edge case when you don't know the size or shape it takes.

**Comment by JD557** [comment]
Yes, that's what's happening here. Curator starts to delete one snapshot and then attempts to delete a second one and fails.

Also, I have multiple delete snapshot actions with `continue_if_exception: True`, so if the first one fails the next ones will fail as well, as there's a snapshot being deleted.

I'm not sure why curator is not waiting for the first snapshot to finish (I am connecting to elasticsearch via an internal load balancer, so I might have some timeout defined somewhere which drops the connection while the snapshot is being deleted).

**Comment by untergeek** [comment]
> I'm not sure why curator is not waiting for the first snapshot to finish
Curator doesn't expect it to take seconds (or longer) to delete, is why.   It just issues a "delete snapshot" API call, and if it's successful, moves on to the next action.  It's not a case I thought would come up, nor was I aware of API calls where I could catch long-running deletes in progress.  

I _really_ wish the tasks API handled this where a delete command issues a _task id.  That would make things much simpler. Unfortunately, it doesn't yet.

I'll try to add some generic polling of the tasks API to look for _anything_ snapshot related going on, and pause there until it's done.  It's going to be hard, still, to get reliable, accurate data from sample/test clusters that respond so quickly, the API calls don't appear.  I'll probably have to create some crazy loops to spool that data into a file as fast as it can go while I run some API calls and hope to capture the associated data.

**Comment by untergeek** [comment]
I won't be able to address this issue this week, unfortunately.  I'll be attending (and presenting at) OpenWest.  I'll get to this as soon as I otherwise can.
